#+title: ГАНКЕВИЧ ИВАН ГЕННАДЬЕВИЧ
#+subtitle: Тема диссертации: “Имитационное моделирование нерегулярного волнения для программ динамики морских объектов”
#+language: ru
#+options: toc:nil author:nil date:nil

* РЕФЕРАТ ДИССЕРТАЦИИ

Программы, моделирующие поведение судна на морских волнах, широко применяются
для расчета качки судна, оценки величины воздействия внешних сил на плавучую
платформу или другой морской объект, а также для оценки вероятности
опрокидывания судна при заданных погодных условиях; однако, большинство из них
используют линейную теорию для моделирования морского волнения, в рамках которой
сложно воспроизвести определенные особенности ветро-волнового климата.  Цель
данного исследования заключается в изучении и разработке математических моделей
и численных методов, которые бы позволили выйти за рамки линейной теории волн в
задаче имитационного моделирования морского волнения и стать альтернативами
моделям и методам, основанных на этой теории. В рамках данного исследования была
разработана трехмерная имитационная математическая модель морского волнения на
основе статистической модели авторегрессии скользящего среднего, метод
вычисления поля давлений под взволнованной морской поверхностью на основе
решения уравнений для несжимаемой невязкой жидкости методом Фурье и программный
комплекс, реализующий модель и метод, для систем с общей и распределенной
памятью. Разработанные средства позволяют моделировать волны произвольных
амплитуд и профилей и определять величину их воздействия на морские объекты, а
программный комплекс является основой для построения виртуального
полигона\nbsp{}--- универсального инструмента моделирования поведения морских
объектов в открытом океане.

* КОДЫ ГРНТИ

27.31.44 Краевые задачи. Общая теория\\
27.35.21 Математические модели гидродинамики\\
27.41.19 Численные методы решения дифференциальных и интегральных уравнений\\
27.43.51 Применение теоретико-вероятностных и статистических методов\\
29.17.19 Жидкости\\
37.25.21 Ветровые, длинные неприливные и внутренние волны\\
50.41.25 Прикладное программное обеспечение

* КЛЮЧЕВЫЕ СЛОВА

авторегрессия, скользящее среднее, быстрое преобразование Фурье, потенциальное
течение, метод Фурье, имитационное моделирование, нерегулярное волнение,
стохастический процесс, взволнованная поверхность, поле потенциала скорости,
поле давлений, линейная теория волн, теория волн малой амплитуды

