#+title: Ответы на вопросы рецензентов диссертации “Имитационное моделирование нерегулярного волнения для программ динамики морских объектов”
#+language: ru
#+options: num:nil toc:nil author:nil date:nil
#+latex_header_extra: \input{preamble}

* Овсянников Дмитрий Александрович

#+begin_quote
В формулах 18 и 24 потерян знаменатель в правой части уравнения, который,
однако, присутствует в формуле из приложения 10.2.
#+end_quote

В формулах 18 и 24 действительно потерян знаменатель в правой части уравнения.
Эта ошибка была замечена уже после сдачи работы. Тестирование программного
комплекса с исправленной формулой не показало качественно новых результатов.

#+begin_quote
Так ли нужен знаменатель в этих формулах, содержащий квадраты пространственных
производных, которые малы для океанских волн, поскольку их длина в несколько раз
больше их высоты?
#+end_quote

Для океанских волн знаменатель увеличивает значения потенциала скорости ближе к
гребню волны примерно на 20%. Хотя значения квадратов производных незначительны,
они суммируются, что в итоге увеличивает значение потенциала. Форма поля
скоростей при этом сохраняется (за исключением участков вблизи гребня).

#+begin_quote
Разница между выведенной в работе формулой для поля потенциала скорости и
формулой из линейной теории волн показана на обыкновенных синусоидах, а не на
морских волнах (рис. 7). На сколько велика разница в форме и магнитуде поля
потенциала скорости для волн, соотношение высоты и длины которых соответствует
реальным морским волнам?
#+end_quote

Для океанских волн знаменатель увеличивает значения потенциала скорости ближе к
гребню волны примерно на 20%. Хотя значения квадратов производных незначительны,
они суммируются, что в итоге увеличивает значение потенциала. Форма поля
скоростей при этом сохраняется (за исключением участков вблизи гребня).

* Кореньков Владимир Васильевич

#+begin_quote
Сформулированные во Введении "Положения, выносимые на защиту", более нигде в
диссертации не упоминаюся и не совсем точно соответствуют выводам, приводимым в
конце диссертации.
#+end_quote

Положения, выносимые на защиту, соответствуют основным главам диссертации.
Развернутое описание по каждому из положений представлено в заключении.
Неточное соответствие выводам объясняется тем, что в выводах описано то, что
было сделано фактически, и как это можно применить на практике.

#+begin_quote
Анализ алгоритмов, систем планирования и обеспечения надежного функционирования
параллельных приложений выполнен недостаточно глубоко.
#+end_quote

Действительно, в мире существует множество систем планирования, алгоритмов и
систем обеспечения надежности. В данной работе множество систем обеспечения
надежности сведено к двум системам: системы, которые основаны на контрольных
точках восстановления (SLURM), и систем, основанные на выборочном перезапуске
задач (Apache Spark, Hadoop), а алгоритмам планирования уделяется недостаточно
внимания. Причиной этому служит узкая специализация разработанного планировщика
задач: в данной работе он применяется только для задачи генерации взволнованной
морской поверхности и вычисления поля давлений. Создание универсального
планировщика, безусловно, потребует более тщательный анализ существующих систем
и алгоритмов.

* Константинос Спироу (Kostas Spyrou)

#+begin_quote
My understanding, although this is not completely clear from the text and I
intend to have it clarified during the presentation, is that the AR model is
basically a difference equation where a current property (e.g. wave elevation)
at a given location is determined from information at a number of earlier time
instants, with addition of a single stochastic impulse. In other words there is
no space-related information involved in this scheme. On the other hand, the MA
supplement of the ARMA model holds the spatial information (but not time) and
for this reason it is vital for obtaining a progressing wave. If I understand
correctly, the white noise of the MA model is handled through a convolution
integral which the author suggests that it can be 
#+end_quote

В данной работе обе модели используют все три координаты (две пространственные и
одну временную). Авторегрессионная модель используется для генерации стоячих
волн, а модель скользящего среднего --- для генерации прогрессивных. Комбинация
моделей возможна в одномерном случае при условии пересчета коэффициентов по
специальной формуле. Аналогичная формула для трехмерного случая мне не известна.
Комбинацию можно провести и без формулы, но тогда характеристики на входе не
будут соответствовать характеристикам на выходе. Термин "модель АРСС" в данной
работе носит собирательный характер и включает в себя модель авторегрессии и
модель скользящего среднего.

#+begin_quote
I would like to know how one can optimally select the required number of earlier
points in time and in space, respectively for the AR and MA processes. Is there
any rule that the author would suggest? 
#+end_quote

Итеративный метод вычисления коэффициентов для трехмерной модели авторегрессии
действительно существует, но не рассмотрен в данной работе. Метод на каждом шаге
вычисляет значения коэффициентов и увеличивает размерность матрицы на единицу.
Цикл завершается, когда дисперсия процесса достигает заданной с некоторой
точностью. Метод использует структуру автоковариационной матрицы, чтобы не
повторять одни и те же вычисления на каждом шаге, и может быть использован для
автоматического определения порядка модели авторегрессии.

Итеративный метод вычисления коэффициентов скользящего среднего мне не известен.

Универсальным методом, который работает для обоих моделей, является вычислением
заведомо большего количества коэффициентов и отбрасывания коэффициентов близких
к нулю и находящихся на правой границе многомерного массива коэффициентов.

#+begin_quote
The 3d formulation of the governing equations of the ARMA model are given in
section 3.2. However the author is advised to provide more explanations on how
this model works computationally. For example, the impression is created that
the AR model uses space-related information too. It is essential to explain what
exactly has been implemented and verified.
#+end_quote

В данной работе обе модели используют все три координаты (две пространственные и
одну временную). 

В работе верифицированы распределения подъема поверхности, высоты, периода и
длины волн. Для модели авторегрессии верифицируются характеристики стоячих
нерегулярных плоских волн. Для модели скользящего среднего верифицируются
характеристики прогрессивных нерегулярных плоских волн.

#+begin_quote
The use of the non-linear intertialess tansform (NIT) is invoked in the
paragraph with header “scientific novelty” (page 150) without any introduction
justifying the use of this technique.
#+end_quote

Нелинейное безынерционные преобразование (НБП) основано на том, что
распределение подъемов реальной взволнованной морской поверхности имеет
ненулевую асимметрию и эксцесс. Этот факт описан в книге Рожкова "Теория
вероятностей случайных событий, величин и функций с гидрометеорологическими
примерами". Ненулевой эксцесс и асимметрия можно моделировать напрямую, подавая
на вход модели автоковариационную функцию неплоской волны.

#+begin_quote
The calculation of the AR and MA processes coefficients (pages 157 to 162) is
presented in an algorithmic manner, the reader cannot see the logic behind these
computations. Some further explanations should be added, perhaps in an appendix.   
#+end_quote

Алгоритмы вычисления коэффициентов АР и СС описаны в книге Бокса и Дженкинса
"Анализ и прогнозирование временных рядов". Формулы для обоих алгоритмов
выводятся путем домножения основного уравнения на дисперсию процесса и взятия
математического ожидания от обоих частей уравнения.

#+begin_quote
Due to the stochastic nature of the ARMA scheme, one-to-one comparison with a
Longuet-Higgins deterministic wave realization, or indeed with a real wave
produced in a tank, seems not possible. It will be good if the author could
commend further on how his method could be validated in principle, beyond of
course the level of producing waves that look realistic.
#+end_quote

Модель АРСС моделирует взволнованную морскую поверхность как единое целое. В
связи с этим оценке поддаются только интегральные характеристики. Верификацию
можно усилить с помощью записи четырехмерного поля подъемов поверхности с
посредством датчиков, расставленных в открытом море в виде сетки. Затем для
полученной поверхности вычисляется автоковариационная функция и генерируется
аналогичная поверхность с помощью модели АРСС. После этого характеристики обоих
поверхностей сопоставляются. Для проверки можно использовать статистики более
высокого порядка, например, условное распределения высот волн в зависимости от
их периодов и длин. 

* Котина Елена Дмитриевна

#+begin_quote
[...] в работе говорится о том, что модель АРСС не основана на линейной теории
волн, однако формулы автоковариционных функций выводятся только для синусоид.
Возможно ли вычислить автоковариационную функцию для других волн, например для
волны Стокса?
#+end_quote

Да, это возможно. Можно использовать автоковариационную функцию любого волнения,
для которого можно записать потенциал скорости.

* Сотникова Маргарита Викторовна

#+begin_quote
В тексте диссертации упоминаются источники литературы, однако нет единого обзора
литературы.
#+end_quote

Обзор литературы приведен во вводных разделах основных глав диссертации (главы
3--5). В каждом разделе рассматриваются слабо связанные друг с другом работы,
поэтому было решено не объединять их в единую главу.

#+begin_quote
В работе отмечается, что для различных типов волн необходимо использовать
различные варианты моделей. Так для стоячих волн предлагается использовать АР
модель, а для прогрессивных волн – модель СС. Однако не обсуждается вопрос о
том, насколько точно можно представить различные спектры морского волнения с
помощью моделей АР и СС? То есть, каковы ограничения предлагаемого подхода к
моделированию волнения?
#+end_quote

Модели авторегрессии (АР) и скользящего среднего (СС) воспроизводят
взволнованную поверхность, автоковариационная функция которой соответствует
автоковариационной функции, поданной на вход этих моделей. Теорема
Винера---Хинчина устанавливает однозначное соответствие спектра и
автоковариационной функции процесса, поэтому спектр на входе соответствует
спектру на выходе.

Выбор автоковариационных функций ограничен теми функциями, для которых модели АР
и СС сходятся. Заранее определить сходимость невозможно, но экспериментально
установлено, что модели сходятся для плоских волн и волн Стокса.

#+begin_quote
В работе предлагается порядки АРСС модели (количество коэффициентов процесса
скользящего среднего и процесса авторегрессии) выбирать вручную. Представляется
возможным рассмотрение вариантов оптимизационных постановок задач, позволяющих
автоматически находить указанные параметры, например, приближая заданные
спектральные характеристики волнения.
#+end_quote

Итеративный метод вычисления коэффициентов для трехмерной модели авторегрессии
действительно существует, но не рассмотрен в данной работе. Метод на каждом шаге
вычисляет значения коэффициентов и увеличивает размерность матрицы на единицу.
Цикл завершается, когда дисперсия процесса достигает заданной с некоторой
точностью. Метод использует структуру автоковариационной матрицы, чтобы не
повторять одни и те же вычисления на каждом шаге, и может быть использован для
автоматического определения порядка модели авторегрессии.

Итеративный метод вычисления коэффициентов скользящего среднего мне не известен.

Универсальным методом, который работает для обоих моделей, является вычислением
заведомо большего количества коэффициентов и отбрасывания коэффициентов близких
к нулю и находящихся на правой границе многомерного массива коэффициентов.

#+begin_quote
В работе рассматриваются модели АР и СС для моделирования морского волнения.
Однако, естественно, что более точное представление можно было бы получить,
используя АРСС модель. Исследование данных вопросов представляется значимым для
повышения адекватности разрабатываемых моделей реальным процессам.
#+end_quote

Метод пересчета значений коэффициентов, который необходим для соответствия
автоковариационной функции результирующей взволнованной поверхности заданной,
описан Боксом и Дженкинсом только для одномерной модели АРСС. Обобщение данного
метода является одним из направлений дальнейших исследований.
