#+TITLE: High-performance ocean wave simulation model for studying marine object behaviour
#+AUTHOR: Ivan Gankevich
#+DATE: St. Petersburg, 2016
#+LANGUAGE: en
#+LATEX_CLASS: gost
#+LATEX_CLASS_OPTIONS: [hidelinks,fontsize=14pt,paper=a4,pagesize,DIV=calc]
#+LATEX_HEADER: \IfFileExists{./preamble.tex}{\input{preamble}}{}
#+LATEX_HEADER: \organization{Saint Petersburg State University}
#+LATEX_HEADER: \manuscript{}
#+LATEX_HEADER: \degree{thesis for candidate of sciences degree}
#+LATEX_HEADER: \speciality{Speciality 05.13.18\\Mathematical modeling, numerical methods and programme complexes}
#+LATEX_HEADER: \supervisor{Supervisor\\Alexander Degtyarev}
#+OPTIONS: todo:nil title:nil H:5

#+begin_latex
\clearpage
#+end_latex

* Introduction
**** Topic relevance.
**** State-of-the-art.
**** Goals and objectives.
**** Scientific novelty.
**** Theoretical and practical significance.
**** Methodology and research methods.
**** Theses for the defense.
**** Results verification and approbation.
* Problem statement
* Related work
* ARMA model for ocean wave simulation
** The reasons for the creation of a new ocean simulation model
ARMA model emerged in response to difficulties encountered by practitioners who
used wave simulation models developed in the framework of linear wave theory.
The problems they have encountered in their work can be summarised as the
following.
1. /Periodicity/. Linear wave theory approximates waves by a sum of harmonics,
   so period of the whole wavy surface realisation depends on the number of
   harmonics in the model. So, reasonably large realisations require large
   number of coefficients. This in turn results in overall bad performance of
   the model, no matter how optimised the software implementation is.
2. /Linearity/. Linear wave theory gives mathematical definition for ocean waves
   which have small amplitudes compared to their lengths. Waves of this type
   occur in the ocean, so waves in shallow water as well as storm waves, for
   which this assumption does not hold, are not perfectly captured by linear
   theory.
3. /Probabilistic convergence/. Wave phase, which is often generated by pseudo
   random number generator (PRNG), has uniform distribution, and this makes wavy
   surface characteristics (average wave height, wave period, wave length etc.)
   sometimes converge slowly to the desired values. Convergence rate depends on
   the values generated by PRNG, which makes it probabilistic.

** The shape of ACF for different types of waves
*** Two methods to find ocean wave's ACF
**** Analytic method of finding the ACF.
**** Empirical method of finding the ACF.
*** Examples of ACFs for various types of wave profiles
**** Standing wave.
**** Propagating wave.
*** Comparison of studied methods
** Governing equations for 3-dimensional ARMA process
*** Three possible processes
**** Autoregressive (AR) process.
**** Moving average (MA) process.
**** Mixed autoregressive moving average (ARMA) process.
*** Process selection criteria for different wave profiles
** Verification of wavy surface integral characteristics
** Modeling non-linearity of ocean waves
** Non-physical nature of ARMA model
ARMA model, owing to its non-physical nature, does not have the notion of ocean
wave; it simulates wavy surface as a whole instead. Motions of individual waves
and their shape are often rough, and the total number of waves can not be
predicted precisely. However, integral characteristics of wavy surface match the
ones of real ocean waves.

In theory, ocean waves themselves can be chosen as ACFs, the only pre-processing
step is to make them decay exponentially. This is required to make AR model
stationary and MA model parameters finding algorithm to converge.

* Determining wave pressures for discretely given wavy surface 
* High-performance software implementation of ocean wave simulation
* Conclusion
* Acknowledgments
* References
* Appendix
