#+TITLE: Высокопроизводительная модель морского волнения для программ динамики морских объектов
#+AUTHOR: Иван Ганкевич
#+LANGUAGE: ru
#+LATEX_CLASS: scrartcl
#+OPTIONS: H:2 num:0 todo:nil toc:nil

#+begin_latex
%\organization{Санкт-Петербургский государственный университет}
%\manuscript{на правах рукописи}
%\degree{Диссертация на соискание ученой степени\\кандидата физико-математических наук}
%\speciality{Специальность 05.13.18\\Математическое моделирование, численные методы и комплексы программ}
%\supervisor{Научный руководитель\\д.т.н Дегтярев Александр Борисович}
%\date{Санкт-Петербург, 2016}
#+end_latex

* Введение
** Актуальность темы
Программы, моделирующие воздействие морских волн на судно, плавучую платформу
или какой-либо другой морской объект, широко используются для расчета качки
судна, определения воздействия внешних сил на структуру морского объекта, а
также для моделирования затопления и других процессов, вызываемых
взаимодействием объекта с морскими волнами; однако, большинство из них
используют линейную теорию для моделирования морского волнения
cite:shin2003nonlinear,van2007forensic,kat2001prediction,van2002development, что
не позволяет моделировать некоторые особенности ветроволнового климата. Среди
них можно выделить переход от нормальных погодных условий к шторму и волнение,
вызванное наложением множества систем ветровых волн и волн зыби,
распространяющихся в разных направлениях. Другой особенностью этих программ
является использование теории волн малой амплитуды, т.е. волн, амплитуда которых
много меньше, чем их длина. Это делает расчеты грубыми, и не позволяет
моделировать качку судна в условиях нерегулярного волнения, когда такое
предположение несправедливо. Ввиду описанных сложностей разработка более
совершенных моделей и методов, используемых при расчете динамики судна, является
актуальной задачей на сегодняшний день.
** Степень разработанности
Особенностью комплексов расчета динамики судов является использование линейных
моделей ветрового волнения, и, хотя эти модели хорошо исследованы, их
вычислительная эффективность не всегда достаточна для проведения длительных
численных экспериментов. Например, в случае модели Лонге---Хиггинса для
увеличения временной протяженности реализации морского волнения может
понадобится увеличить количество частот спектра на входе для исключения
периодичности, что приводит к нелинейному увеличению времени генерации с ростом
длины реализации. В случае альтернативных моделей ветрового
волнения для расчета давлений используются методы вычислительной гидродинамики,
обладающие меньшей эффективностью, чем аналитические методы, разработанные для
для линейной модели. Таким образом, степень разработанности используемых на
практике моделей ветрового волнения и методов расчета давлений не позволяет
эффективно проводить длительные численные эксперименты, а уход от линейной
модели приведет к качественному улучшению результатов экспериментов и будет
способствовать проведению исследований возникающих редко экстремальных ситуаций,
связанных с потерей остойчивости (например, опрокидывание и брочинг).
** Цели и задачи
Основной целью работы является разработка математического и численного аппарата
имитационного моделирования морских волн для проведения длительных численных
экспериментов и определения величины создаваемого морскими волнами воздействия
на морские объекты. Основные задачи, решаемые в рамках работы:
- разработка модели ветрового волнения, способной генерировать реализации
  взволнованной морской поверхности, имеющие сверхбольшой период и состоящие из
  волн произвольной амплитуды;
- разработка метода расчета давлений, работающего с этой моделью и не
  использующего теорию волн малой амплитуды;
- разработка комплекса программ, реализующего созданную модель и метод расчета
  давлений и позволяющего проводить расчеты как на многопроцессорной машине с
  общей памятью, так и на компьютерном кластере.
** Научная новизна
Авторегрессионная модель в отличие от других моделей ветрового волнения не
основана на теории волн малой амплитуды, что позволяет учесть такие аспекты
океанских волн, как асимметричность распределения волновых аппликат. В то же
время математический аппарат этой модели хорошо разработан в других научных
областях, что позволяет обобщить модель для моделирования развития морского
волнения в условиях шторма с учетом климатических спектров и данных ассимиляции
определенных районов мирового океана.
** Теоретическая и практическая значимость работы
Применение альтернативной модели морского волнения и метода расчета давлений, не
использующего предположения о малости амплитуд волн и линейной теории волн,
позволит качественно повысить работу комплексов программ для расчета воздействия
океанских волн на морские объекты.
** Методология и методы исследования
Программная реализация авторегрессионной модели и методы вычислений давлений
была создана инкрементально: сначала был создан прототип на инженерном языке
высокого уровня (Mathematica, Octave), который затем бы лпреобразован в
программу на языке более низкого уровня (C++). Для вывода аналитической формулы
расчета давлений использовался математический аппарат, проверка полученных
выражений осуществлялась с помощью системы компьютерной алгебры Mathematica.
** Положения, выносимые на защиту
- Модель ветрового волнения, способная генерировать реализации взволнованной
  морской поверхности, имеющие сверхбольшой период и состоящие из волн
  произвольной амплитуды;
- Метод расчета давлений, работающий с этой моделью и не использующий теорию
  волн малой амплитуды;
- Комплекс программ, реализующий созданную модель и метод расчета давлений и
  позволяющий проводить расчеты как на многопроцессорной машине с общей памятью,
  так и на компьютерном кластере.
** Степень достоверности и апробация результатов
Достоверность полученных результатов как по модели авторегрессии так и по методу
вычислений давлений подтверждается многочисленными и всесторонними численными
экспериментами, целью которых было сравнение полученных результатов с поведением
реальных морских волн на основе имеющихся натурных данных. Апробация
производилась на системе Large Amplitude Motion Program (LAMP), в которой модель
авторегрессии и метод вычислений давлений были реализованы и сопоставлены с
используемыми ранее методами, основанными на теории волн малой амплитуды. Эти
проверки показали целесообразность применения и более высокую эффективность
альтернативной модели и метода расчета давлений ввиду их гидродинамической
адекватности и более высокой производительности.
* Постановка задачи
* Обзор литературы
* Применение модели АРСС в задаче имитационного моделирования морского волнения
* Определение поля давлений под дискретно заданной взволнованной поверзностью
* Высокопроизводительный программный комплекс для моделировани морского волнения
* Заключение
* Благодарности
* Список литературы
* Приложение
