#+TITLE: Высокопроизводительная модель морского волнения для программ динамики морских объектов
#+AUTHOR: Иван Ганкевич
#+DATE: Санкт-Петербург, 2016
#+LANGUAGE: ru
#+LATEX_CLASS: gost
#+LATEX_CLASS_OPTIONS: [hidelinks,fontsize=14pt,paper=a4,pagesize,DIV=calc]
#+LATEX_HEADER_EXTRA: \input{preamble}
#+LATEX_HEADER_EXTRA: \organization{Санкт-Петербургский государственный университет}
#+LATEX_HEADER_EXTRA: \manuscript{на правах рукописи}
#+LATEX_HEADER_EXTRA: \degree{Диссертация на соискание ученой степени\\кандидата физико-математических наук}
#+LATEX_HEADER_EXTRA: \speciality{Специальность 05.13.18\\Математическое моделирование, численные методы и комплексы программ}
#+LATEX_HEADER_EXTRA: \supervisor{Научный руководитель\\д.т.н Дегтярев Александр Борисович}
#+LATEX_HEADER_EXTRA: \newcites{published}{Список опубликованных по теме диссертации работ}
#+OPTIONS: todo:nil title:nil ':t H:5

# default export options
#+begin_src emacs-lisp :exports none :results silent
;; For the full list of options see
;; http://orgmode.org/manual/Publishing-options.html
;; move table/figure captions to the bottom
(setq org-latex-caption-above nil)
;; preserve original image width
(setq org-latex-image-default-width nil)
#+end_src

* Введение
**** Актуальность темы.
Программы, моделирующие поведение судна на морских волнах, широко применяются
для расчета качки судна, оценки величины воздействия внешних сил на плавучую
платформу или другой морской объект, а также для оценки вероятности
опрокидывания судна при заданных погодных условиях; однако, большинство из них
используют линейную теорию для моделирования морского волнения
cite:shin2003nonlinear,van2007forensic,kat2001prediction,van2002development, в
рамках которой сложно воспроизвести определенные особенности ветроволнового
климата. Среди них можно выделить переход от нормальных погодных условий к
шторму и волнение, вызванное наложением множества систем ветровых волн и волн
зыби, распространяющихся в нескольких направлениях. Другой недостаток линейной
теории волн заключается в предположении, что высота волн много меньше их длины.
Это делает расчеты грубыми при моделировании качки судна в условиях
нерегулярного волнения, когда такое предположение несправедливо. Разработка
новых и более совершенных моделей и методов, используемых при расчете динамики
судна, может увеличить количество сценариев ее применения и, в частности,
способствовать исследованию поведения судна в экстремальных условиях.

**** Степень разработанности.
Модель авторегрессии скользящего среднего АРСС возникла как ответ на сложности,
с которыми на практике сталкиваются ученые, использующие в свой работе модели
морского волнения, разработанные в рамках линейной теории волн. Проблемы, с
которыми они сталкиваются при использовании модели Лонге---Хиггинса (которая
полностью основана на линейной теории волн) перечислены ниже.
1. /Периодичность/. В рамках линейной теории волны аппроксимируются суммой
   гармоник, а период реализации взволнованной поверхности зависит от их
   количества. Чем больше размер реализации, тем больше коэффициентов требуется
   для исключения периодичности, поэтому с увеличением размера реализации время
   ее генерации растет нелинейно. Это приводит к тому, что любая модель,
   основанная на линейной теории, неэффективна при генерации больших реализаций
   взволнованной поверхности, независимо от того, насколько оптимизирован
   исходный код программы.
2. /Линейность/. В рамках линейной теории волн дается математическое определение
   морским волнам в предположении малости их амплитуд по сравнению с длинами.
   Такие волны, в основном, характерны для открытого моря и океана, а волны в
   прибрежных районах и штормовые волны, для которых это предположение
   несправедливо, грубо описываются в рамках линейной теории.
3. /Вероятностная сходимость/. Фаза волны, значение которой обычно получается с
   помощью генератора псевдослучайных чисел (ГПСЧ), имеет равномерное
   распределение, что иногда приводит к медленной сходимости интегральных
   характеристик взволнованной поверхности (таких как распределение высот волн,
   их периодов, длин и т.п.). Скорость сходимости зависит от значений,
   полученных от ГСПЧ, поэтому быстрая сходимость не гарантируется.

Эти сложности стали отправной точкой в поиске модели, не основанной на линейной
теории волн, и в исследованиях процесса авторегрессии скользящего среднего
(АРСС) был найден необходимый математический аппарат.
1. Параметром процесса АРСС является автоковариационная функция (АКФ), которая
   может быть напрямую получена из энергетического или частотно-направленного
   спектра морского волнения (который, в свою очередь является входным
   параметром для модели Лонге---Хиггинса). Так что входные параметры одной
   модели могут быть легко преобразованы во входные параметры другой.
2. Процесс АРСС не имеет ограничение на амплитуду генерируемых волн: их крутизна
   может быть увеличена на столько, на сколько это позволяет АКФ реальных
   морских волн.
3. Период реализации равен периоду ГПСЧ, поэтому время генерации растет линейно
   с увеличением размера реализации.
4. Белый шум, который является единственным вероятностным членом формулы
   процесса АРСС, имеет нормальное распределение; так что скорость сходимость не
   носит вероятностный характер.

**** Цели и задачи.
Процесс АРСС стал основой модели ветрового волнения АРСС, однако он нуждался в
доработке перед тем, как его можно было бы использовать на практике.
1. Необходимо было исследовать, как различные формы АКФ влияют на выбор
   параметров процесса АРСС (количество коэффициентов процесса скользящего
   среднего и процесса авторегрессии).
2. Затем исследовать возможность генерации волн с произвольным профилем, а не
   только профиль синусоиды (учесть асимметричность распределения волновых
   аппликат взволнованной поверхности).
3. Затем вывести формулы для определения поля давлений под взволнованной
   поверхностью. Такие формулы обычно выводятся для конкретной модели путем
   подстановки формулы профиля волны в eqref:eq:problem, однако процесс АРСС не
   содержит в себе формулу профиля волны в явном виде, поэтому для него
   необходимо было получить решение для взволнованной поверхности общего вида
   (для которой не существует аналитического выражения) без линеаризации
   граничных условий (ГУ) и предположении о малости амплитуд волн.
4. Наконец, верифицировать интегральные характеристики взволнованной поверхности
   на соответствие реальным морским волнам.
5. Заключительный этап состоял в разработке комплекса программ, реализующего
   созданную модель и метод расчета давлений и позволяющего проводить расчеты
   как на многопроцессорной машине с общей памятью (SMP), так и на компьютерном
   кластере (MPP).

**** Научная новизна.
Модель АРСС в отличие от других моделей ветрового волнения не основана на
линейной теории волн, что позволяет
- генерировать волны произвольной амплитуды, регулируя крутизну посредством АКФ;
- генерировать волны произвольной формы, регулируя асимметричность распределения
  волновых аппликат посредством нелинейного безынерционного преобразования
  (НБП).
В то же время математический аппарат этой процесса АРСС хорошо изучен в
других научных областях, что позволяет его обобщить для моделирования развития
морского волнения в условиях шторма с учетом климатических спектров и данных
ассимиляции определенных районов мирового океана, что невозможно сделать с
помощью модели, основанной на линейной теории волн.

**** Теоретическая и практическая значимость работы.
Применение модели АРСС и формулы поля давлений, не использующей предположения
линейной теории волн, качественно повысит работу комплексов программ для расчета
воздействия океанских волн на морские объекты.

1. Поскольку формула для поля давлений выводится для дискретно заданной
   взволнованной поверхности и без каких-либо предположений об амплитудах волн,
   то она применима для любой взволнованной поверхности невязкой несжимаемой
   жидкости (в частности она применима для поверхности, генерируемой моделью
   Лонге---Хиггинса). Это позволяет использовать формулу поля давлений без
   привязки к модели АРСС.
2. С вычислительной точки зрения эта формула более эффективна, чем
   соответствующая формула для модели ЛХ, поскольку интегралы в формуле сводятся
   к преобразованиям Фурье, для которых существует семейство алгоритмов быстрого
   преобразования Фурье (БПФ), оптимизированных под разные архитектуры
   процессоров.
3. Поскольку формула явная, то обмена данными между параллельными процессами
   можно избежать, что позволяет достичь высокой масштабируемости на
   компьютерном кластере.
4. Наконец, сама модель АРСС более эффективна, чем модель ЛХ, ввиду отсутствия
   тригонометрических функций в ее формуле. Взволнованная поверхность
   вычисляется как сумма большого числа многочленов, для которых существует
   низкоуровневая ассемблерная инструкция (Fused Multiply-Add), показывающая
   высокую производительность на процессорах.

**** Методология и методы исследования.
Программная реализация модели АРСС и формула вычисления давлений создавалась
поэтапно: прототип, написанный высокойровневом инженерном языке
cite:mathematica10,octave2015, был преобразован в программу на языке более
низкого уровня (C++). Реализация одних и тех же формул и алгоритмов на языках
разного уровня (ввиду использования различных абстракций и языковых примитивов)
позволяет выявить и исправить ошибки, которые остались бы незамеченными в случае
одного языка. Генерируемая моделью АРСС взволнованная поверхность, а также все
входные параметры (АКФ, формула распределения волновых аппликат и т.п.) были
проверены с помощью встроенных в язык программирования графических средств для
визуального контроля корректности работы программы.

**** Положения, выносимые на защиту.
- Модель ветрового волнения, способная генерировать реализации взволнованной
  морской поверхности, имеющие большой период и состоящие из волн произвольной
  амплитуды;
- Формула для поля давлений, выведенная для этой модели без предположений
  линейной теории волн;
- Программная реализация созданной модели и формулы для вычислительных систем с
  общей (SMP) и с распределенной памятью (MPP).

**** Степень достоверности и апробация результатов.
Верификация модели АРСС проводится путем сравнения интегральных характеристик
(распределений волновых аппликат, высот и длин волн и т.п.) генерируемой
взволнованной поверхности с характеристиками реальных морских волн. Формула для
поля давлений выводится с помощью языка Mathematica, в котором полученные
выражения проверяются с помощью встроенных в язык графических средств.

Модель АРСС и формула для поля давлений были реализованы в Large Amplitude
Motion Programme (LAMP), программе для моделирования качки судна, и сопоставлены
с используемой ранее моделью ЛХ. Предварительные численные эксперименты показали
более высокую вычислительную эффективность модели АРСС.

* Постановка задачи
Задача состоит в исследовании возможности применении математического аппарата
процесса АРСС для моделирования морских волн и в выводе формулы для поля
давлений под генерируемой взволнованной морской поверхностью для случая
идеальной несжимаемой жидкости без предположений линейной теории волн.
- Для случая волн малых амплитуд полученная формула должна быть сопоставимо с
  соответствующей формулой линейной теории волн; для остальных случаев формула
  не должна расходиться.
- Интегральные характеристики генерируемой взволнованной поверхности должны
  совпадать с характеристиками реальных морских волн.
- Программная реализация модели АРСС и формулы вычисления давлений должна
  работать на системах с общей (SMP) и распределенной памятью (MPP).

**** Формула для поля давлений.
Задача определения поля давлений под взволнованной морской поверхностью
представляет собой обратную задачу гидродинамики для несжимаемой невязкой
жидкости. Система уравнений для нее в общем виде записывается как
cite:kochin1966theoretical
\begin{align}
    & \nabla^2\phi = 0,\nonumber\\
    & \phi_t+\frac{1}{2} |\vec{\upsilon}|^2 + g\zeta=-\frac{p}{\rho}, & \text{на }z=\zeta(x,y,t),\label{eq:problem}\\
    & D\zeta = \nabla \phi \cdot \vec{n}, & \text{на }z=\zeta(x,y,t),\nonumber
\end{align}
где $\phi$ --- потенциал скорости, $\zeta$ --- подъем (аппликата) взволнованной
поверхности, $p$ --- давление жидкости, $\rho$ --- плотность жидкости,
$\vec{\upsilon} = (\phi_x, \phi_y, \phi_z)$ --- вектор скорости, $g$ ---
ускорение свободного падения и $D$ --- субстанциональная производная
(производная Лагранжа). Первое уравнение является уравнением неразрывности
(уравнение Лапласа), второе --- законом сохранения импульса (которое иногда
называют динамическим граничным условием); третье уравнение --- кинематическое
граничное условие, которое сводится к равенству скорости перемещения этой
поверхности ($D\zeta$) нормальной составляющей скорости жидкости ($\nabla \phi
\cdot \vec{n}$).

Обратная задача гидродинамики заключается в решении этой системы уравнений
относительно $\phi$. В такой постановке динамическое ГУ становится явной
формулой для определения поля давлений по значениям производных потенциалов
скорости, полученных из оставшихся уравнений. Таким образом, с математической
точки зрения обратная задача гидродинамики сводится к решению уравнения Лапласа
со смешанным ГУ --- задаче Робена.

* Обзор литературы
** Анализ моделей морского волнения
Вычисление давлений возможно только при условии знания формы взволнованной
поверхности, которая задается либо дискретно в каждой точке пространственной
сетки, либо непрерывно с помощью аналитической формулы. Как будет показано в
разделе [[#linear-boundary]], знание такой формулы может упростить вычисление
давлений, фактически сведя задачу к генерации поля давлений, а не самой
взволнованной поверхности.

*** Модель Лонге---Хиггинса
Наиболее простой моделью, формула которой выводится в рамках линейной теории
волн, является модель Лонге---Хиггинса (ЛХ) cite:longuet1957statistical.
Подробный сравнительный анализ этой модели и модели АРСС проведен в работах
cite:degtyarev2011modelling,boukhanovsky1997thesis.

Модель ЛХ представляет взволнованную морскую поверхность в виде суперпозиции
элементарных гармонических волн случайных амплитуд $c_n$ и фаз $\epsilon_n$,
непрерывно распределенных на интервале $[0,2\pi]$. Подъем (координата $z$)
поверхности определяется формулой
#+name: eq:longuet-higgins
\begin{equation}
    \zeta(x,y,t) = \sum\limits_n c_n \cos(u_n x + v_n y - \omega_n t + \epsilon_n).
\end{equation}
Здесь волновые числа $(u_n,v_n)$ непрерывно распределены на плоскости $(u,v)$,
т.е. площадка $du \times dv$ содержит бесконечно большое количество волновых
чисел. Частота связана с волновыми числами дисперсионным соотношением
$\omega_n=\omega(u_n,v_n)$. Функция $\zeta(x,y,t)$ является трехмерным
эргодическим стационарным однородным гауссовым процессом, определяемым
соотношением
\begin{equation*}
    2E_\zeta(u,v)\, du\,  dv = \sum\limits_n c_n^2,
\end{equation*}
где $E_\zeta(u,v)$ --- двумерная спектральная плотность энергии волн.
Коэффициенты $c_n$ определяются из энергетического спектра волнения $S(\omega)$
по формуле
\begin{equation*}
    c_n = \sqrt{ \textstyle\int\limits_{\omega_n}^{\omega_{n+1}} S(\omega) d\omega}.
\end{equation*}

*** Основные недостатки модели Лонге---Хиггинса
Модель Лонге---Хиггинса отличается простотой численного алгоритма и
наглядностью, однако, на практике она обладает рядом недостатков.

1. Модель рассчитана на представление стационарного гауссова поля. Это является
   следствием центральной предельной теоремы (ЦПТ): сумма большого числа
   гармоник со случайными амплитудами и фазами имеет нормальное распределение в
   независимости от спектра, подаваемого на вход модели. Использование меньшего
   количества коэффициентов может решить проблему, но также уменьшит период
   реализации. Таким образом, использование модели ЛХ для генерации волн с
   негауссовым распределением аппликат (которое имеют реальные морские волны
   cite:huang1980experimental,рожков1996теория) не реализуемо на практике.
2. С вычислительной точки зрения, недостатком модели является нелинейный рост
   времени генерации поверхности с увеличением размера реализации. Чем больше
   размер реализации, тем больше коэффициентов (дискретных точек
   частотно-направленного спектра) требуется для исключения периодичности. Это
   делает модель неэффективной для проведения длительных численных
   экспериментов.
3. Наконец, с инженерной точки зрения, модель обладает рядом особенностей,
   которые не позволяют использовать ее в качестве фундамента для построения
   более совершенных моделей.
   - В программной реализации скорость сходимости выражения ([[eq:longuet-higgins]])
     может быть низкой, т.к. фазы $\epsilon_n$ имеют вероятностный характер.
   - Обобщение модели для негауссовых и нелинейных процессов сопряжено с большой
     трудоемкостью вычислений cite:рожков1990вероятностные.
 
Таким образом, модель Лонге---Хиггинса применима для решения задачи генерации
взволнованной морской поверхности только в линейной постановке (в рамках теории
волн малой амплитуды), неэффективна для длительных экспериментов и имеет ряд
недостатков, не позволяющих использовать ее в качестве основы для построения
более совершенных моделей.

*** Модель АРСС
В cite:spanos1982arma модель АРСС используется для генерации временного ряда,
спектр которого совпадает с аппроксимацией Пирсона---Московица для спектров
морского волнения. Эксперименты проводятся для одномерных моделей АР, СС и АРСС.
Автор отмечает превосходное совпадение полученного и исходного спектров и
отмечает более высокую вычислительную эффективность модели АРСС по сравнению с
моделями, основанными на суммировании большого числа гармоник со случайными
фазами. Также отмечается, что для того чтобы спектр полученного временного ряда
совпадал с заданным, модели СС требуется меньшее количество коэффициентов, чем
модели АР. В cite:spanos1996efficient автор обобщает формулы для нахождения
коэффициентов модели АРСС для случая нескольких переменных (векторный процесс).

Отличие данной работы от вышеперечисленных отличается в исследовании трехмерной
модели АРСС (два пространственных и одно временное измерение), у которой есть
свои особенности.
1. Система уравнений Юла---Уокера, используемая для определения коэффициентов
   АР, имеет более сложную блочно-блочную структуру.
2. Для определения оптимального для совпадения заданного и исходного спектров
   порядка модели используется другой подход.
3. Исследуются спектры для разных стоячих и прогрессивных волн.
4. Трехмерная взволнованная поверхность должна быть сопоставима с реальной
   морской поверхностью не только по спектральным характеристикам, но и по форме
   волновых профилей, поэтому верификация модели производится и для
   распределений различных параметров генерируемых волн (длин, высот, периодов и
   др.).
Многомерность исследуемой модели не только усложняет задачу, но и позволяет
провести визуальную проверку генерируемой взволнованной поверхности. Именно
возможность визуализировать результат работы программы позволила удостовериться,
что генерируемая поверхность действительно похожа на реальное морское волнение,
а не является абстрактным многомерным случайным процессом, совпадающим с
реальным лишь статистически.

** Известные формулы определения поля давлений
*** Теория волн малых амплитуд
В cite:stab2012 дается решение обратной задачи гидродинамики для случая
идеальной несжимаемой жидкости в рамках теории волн малых амплитуд (в
предположении, что длина волны много больше ее высоты: $\lambda \gg h$). В этом
случае обратная задача линейна и сводится к уравнению Лапласа со смешанным
граничным условием, а уравнение движения используется только для нахождения
давлений по известным значениям производных потенциала скорости. Предположение о
малости амплитуд волн означает слабое изменение локального волнового числа во
времени и пространстве по сравнению с подъемом (аппликатой) взволнованной
поверхности. Это позволяет определить специальную формулу производной
$\zeta_z=k\zeta$, где $k$ --- волновое число. Формула является основой
предлагаемого решения. В двухмерном случае решение записывается явной формулой
\begin{align}
    \left.\frac{\partial\phi}{\partial x}\right|_{x,t}= &
        -\frac{1}{\sqrt{1+\alpha^{2}}}e^{-I(x)}
            \int\limits_{0}^x\frac{\partial\dot{\zeta}/\partial      
                z+\alpha\dot{\alpha}}{\sqrt{1+\alpha^{2}}}e^{I(x)}dx,\label{eq:old-sol-2d}\\
    I(x)= & \int\limits_{0}^x\frac{\partial\alpha/\partial z}{1+\alpha^{2}}dx,\nonumber
\end{align}
где $\alpha$ --- уклоны волн. В трехмерном случае решение записывается в виде
эллиптического дифференциального уравнения в частных производных
\begin{align*}
    & \frac{\partial^2 \phi}{\partial x^2} \left( 1 + \alpha_x^2 \right) +
    \frac{\partial^2 \phi}{\partial y^2} \left( 1 + \alpha_y^2 \right) +
    2\alpha_x\alpha_y \frac{\partial^2 \phi}{\partial x \partial y} + \\
    & \left(
        \frac{\partial \alpha_x}{\partial z} +
        \alpha_x \frac{\partial \alpha_x}{\partial x} +
        \alpha_y \frac{\partial \alpha_x}{\partial y}
    \right) \frac{\partial \phi}{\partial x} + \\
    & \left(
        \frac{\partial \alpha_y}{\partial z} +
        \alpha_x \frac{\partial \alpha_y}{\partial x} +
        \alpha_y \frac{\partial \alpha_y}{\partial y}
    \right) \frac{\partial \phi}{\partial y} + \\
    & \frac{\partial \dot{\zeta}}{\partial z} + 
    \alpha_x \dot{\alpha_x} + \alpha_y \dot{\alpha_y} = 0.
\end{align*}
Уравнение предполагается решать численно путем сведения к разностному.

Как будет показано в [[#sec:compare-formulae]] формула eqref:eq:old-sol-2d
расходится при попытке вычислить поле скоростей для волн больших амплитуд, а
значит не может быть использована вместе с моделью ветрового волнения,
генерирующей волны произвольных амплитуд.

*** Линеаризация граничного условия
:PROPERTIES:
:CUSTOM_ID: linear-boundary
:END:
Модель Лонге---Хиггинса позволяет вывести явную формулу для поля
скоростей путем линеаризации кинематического граничного условия. Формула для
потенциала скорости запишется как
\begin{equation*}
\phi(x,y,z,t) = \sum_n \frac{c_n g}{\omega_n} 
     e^{\sqrt{u_n^2+v_n^2} z}
     \sin(u_n x + v_n y - \omega_n t + \epsilon_n).
\end{equation*}
Формула дифференцируется для получения производных потенциала, а полученные
значения подставляются в динамическое граничное условие для вычисления давлений.

* Модель АРСС в задаче имитационного моделирования морского волнения
** Основные формулы трехмерного процесса AРСС
*** Три возможных процесса
**** Процесс авторегрессии (АР).
Авторегрессионная модель представляет взволнованную морскую поверхность в виде
пространственно-временного поля, каждая точка которого является взвешенной
суммой предыдущих по времени точек и некоторой случайной переменной (белого
шума). Таким образом, состояние взволнованной поверхности в заданный момент
времени находится в авторегрессионной зависимости от состояний в предыдущие
моменты времени и от случайной переменной с нормальным распределением. Такая
зависимость определяется соотношением
\begin{equation*}
    \zeta_{\vec i}
    =
    \sum\limits_{\vec j = \vec 0}^{\vec N} \Phi_{\vec j}
    \zeta_{\vec i - \vec j} +
    \epsilon_{\vec i},
\end{equation*}
где $\zeta$ --- подъем (аппликата) взволнованной поверхности, $\Phi$ ---
коэффициенты авторегрессии, $\Phi_{\vec 0} \equiv 0$ по определению, $\epsilon$
--- белый шум, $N$ --- порядок регрессии по каждому из измерений, а стрелки
обозначают многокомпонентные индексы, содержащие значение для каждого измерения.
В общем случае в качестве компонент могут выступать любые скалярные величины,
такие как температура, соленость и концентрация какого-либо раствора в воде.

% TODO куда деть соленость?

Коэффициенты авторегрессии опеределяются из многомерных уравнений Юла---Уокера,
которые получаются домножением на $\zeta_{\vec{i}-\vec{k}}$ обеих частей
уравнения и взятия математического ожидания. В общем виде уравнения Юла---Уокера
записываются как
\begin{equation}
    \label{eq:yule-walker}
    \gamma_{\vec k}
    =
    \sum\limits_{\vec j = \vec 0}^{\vec N}
    \Phi_{\vec j}
    \text{ }\gamma_{\vec{k}-\vec{j}}
    +
    \Var{\epsilon} \delta_{\vec{k}},
    \qquad
    \delta_{\vec{k}} =
    \begin{cases}
        1, \quad \text{if } \vec{k}=0 \\
        0, \quad \text{if } \vec{k}\neq0,
    \end{cases}
\end{equation}
где $\gamma$ --- \gls{АКФ} процесса $\zeta$, $\Var{\epsilon}$ --- дисперсия
белого шума. Матричная форма трехмерной системы уравнений Юла---Уокера,
используемой в данной работе, имеет следующий вид.
\begin{equation*}
    \Gamma
    \left[
        \begin{array}{l}
            \Phi_{\vec 0}\\
            \Phi_{0,0,1}\\
            \vdotswithin{\Phi_{\vec 0}}\\
            \Phi_{\vec N}
        \end{array}
    \right]
    =
    \left[
        \begin{array}{l}
            \gamma_{0,0,0}-\Var{\epsilon}\\
            \gamma_{0,0,1}\\
            \vdotswithin{\gamma_{\vec 0}}\\
            \gamma_{\vec N}
        \end{array}
    \right],
    \qquad
    \Gamma=
    \left[
        \begin{array}{llll}
            \Gamma_0 & \Gamma_1 & \cdots & \Gamma_{N_1} \\
            \Gamma_1 & \Gamma_0 & \ddots & \vdotswithin{\Gamma_0} \\
            \vdotswithin{\Gamma_0} & \ddots & \ddots & \Gamma_1 \\
            \Gamma_{N_1} & \cdots & \Gamma_1 & \Gamma_0
        \end{array}
    \right],
\end{equation*}
где $\vec N = \left( N_1, N_2, N_3 \right)$ и
\begin{equation*}
    \Gamma_i =
    \left[
    \begin{array}{llll}
        \Gamma^0_i & \Gamma^1_i & \cdots & \Gamma^{N_2}_i \\
        \Gamma^1_i & \Gamma^0_i & \ddots & \vdotswithin{\Gamma^0_i} \\
        \vdotswithin{\Gamma^0_i} & \ddots & \ddots & \Gamma^1_i \\
        \Gamma^{N_2}_i & \cdots & \Gamma^1_i & \Gamma^0_i
    \end{array}
    \right]
    \qquad
    \Gamma_i^j=
    \left[
    \begin{array}{llll}
        \gamma_{i,j,0} & \gamma_{i,j,1} & \cdots & \gamma_{i,j,N_3} \\
        \gamma_{i,j,1} & \gamma_{i,j,0} & \ddots &x \vdotswithin{\gamma_{i,j,0}} \\
        \vdotswithin{\gamma_{i,j,0}} & \ddots & \ddots & \gamma_{i,j,1} \\
        \gamma_{i,j,N_3} & \cdots & \gamma_{i,j,1} & \gamma_{i,j,0}
    \end{array}
    \right],
\end{equation*}
Поскольку по определению $\Phi_{\vec 0}\equiv0$, то первую строку и столбец
матрицы $\Gamma$ можно отбросить. Матрица $\Gamma$, как и оставшаяся от нее
матрица, будут блочно-теплицевы, положительно определены и симметричны, поэтому
систему уравнений Юла---Уокера можно решить методом Холецкого, предназначенного
для таких матриц.

После нахождения решения системы уравнений дисперсия белого шума определяется из
уравнения eqref:eq:yule-walker при $\vec k = \vec 0$ как
\begin{equation*}
    \Var{\epsilon} =
    \Var{\zeta}
    -
    \sum\limits_{\vec j = \vec 0}^{\vec N}
    \Phi_{\vec j}
    \text{ }\gamma_{\vec{j}}.
\end{equation*}

**** Процесс скользящего среднего (СС).
**** Смешанный процесс авторегрессии скользящего среднего (АРСС).
*** Критерии выбора процесса для моделирования разных профилей волн
** Моделирование нелинейности морских волн
Модель АРСС позволяет учесть асимметричность распределения волновых аппликат,
т.е. сгенерировать морские волны, закон распределения аппликат которых имеет
ненулевой экцесс и асимметрию. Такой закон распределения характерен для реальных
морских волн.

Асимметричность включается в модель нелинейным безынерционным преобразованием
случайного процесса. Однако, любое нелинейное преобразование случайного процесса
приводит к преобразованию его автоковариационной функции. Самый простой способ
подавить этот эффект состоит в предварительной трансформации автоковариационной
функции процесса. Подробный метод преобразования изложен в работе
cite:boukhanovsky1997thesis.

Формула $z=f(y)$ преобразования взволнованной поверхности к необходимому
одномерному закону распределения $F(z)$ получается путем решения нелинейного
трансцендентного уравнения $F(z) = \Phi(y)$, где $\Phi(y)$ --- функция
одномерного нормального закона распределения. Поскольку функция распределения
аппликат морских волн часто задается некоторой аппроксимацией, основанной на
натурных данных, то это уравнение целесообразно решать численно в каждой точке
$y_k|_{k=0}^N$ сетки сгенерированной поверхности относительно $z_k$, тогда оно
запишется в виде
\begin{equation}
    \label{eq:distribution-transformation}
    F(z_k)
    =
    \frac{1}{\sqrt{2\pi}}
    \int\limits_0^{y_k} \exp\left[ -\frac{t^2}{2} \right] dt
    ,
\end{equation}
а для его решения этого можно использовать простейший численный метод
половинного деления (метод бисекции).

Для предварительного преобразования автоковариационной функции $K_z$ процесса ее
необходимо разложить в ряд по полиномам Эрмита (ряд Грама---Шарлье)
\begin{equation*}
    K_z \left( \vec u \right)
    =
    \sum\limits_{m=0}^{\infty}
    C_m^2 \frac{K_y^m \left( \vec u \right)}{m!},
\end{equation*}
где
\begin{equation*}
    C_m = \frac{1}{\sqrt{2\pi}}
  \int\limits_{0}^\infty
    f(y) H_m(y) \exp\left[ -\frac{y^2}{2} \right],
\end{equation*}
$H_m$ --- полином Эрмита, а $f(y)$ --- решение
уравнения eqref:eq:distribution-transformation. Воспользовавшись
полиномиальной аппроксимацией $f(y) \approx \sum\limits_i d_i y^i$ и
аналитическими выражениями для полнимов Эрмита, формулу определения
коэффициентов можно упростить, используя следующее равенство:
\begin{equation*}
    \frac{1}{\sqrt{2\pi}}
    \int\limits_\infty^\infty
    y^k \exp\left[ -\frac{y^2}{2} \right]
    =
    \begin{cases}
        (k-1)!! & \text{для четных }k,\\
        0       & \text{для нечетных }k.
    \end{cases}
\end{equation*}
Вычисление коэффициентов $C_m$ ведется последовательно и критерий прекращения
счета определяется совпадением дисперсий обоих полей с требуемой точностью
$\epsilon$:
\begin{equation*}
    \left| \Var{z} - \sum\limits_{k=0}^m
    \frac{C_k^2}{k!} \right| \leq \epsilon.
\end{equation*}

В cite:boukhanovsky1997thesis автор предлагает использовать полиномиальную
аппроксимацию для $f(y)$ также для преобразования поверхности, однако на
практике в реализации взволнованной поверхности всегда находятся точки,
выпадающие за промежуток на котором построена аппроксимация, что приводит к
резкому уменьшению точности аппроксимации. В этих точках
уравнение eqref:eq:distribution-transformation эффективнее решать методом
бисекции. Использование полиномиальной аппроксимацией в формулах для
коэффициентов ряда Грама---Шарлье не приводит к аналогичным ошибкам.

** Определение поля давлений под дискретно заданной взволнованной поверхностью
Поиск аналитических решений граничных задач для классических уравнений часто
связан с исследованием различных свойств решения, и для таких исследований
запись формулы общего решения неудобна ввиду своей сложности и наличия
интегралов от неизвестных функций. Одним из методов нахождения аналитических
решений ДУЧП является метод Фурье. Основой метода служит преобразование Фурье,
применение которого к любому ДУЧП позволяет свести его к алгебраическому, а его
решение записывается как обратное преобразование Фурье от некоторой функции
(которая часто содержит преобразования Фурье от других функций). Поскольку
преобразования не всегда можно записать аналитически, то вместо этого ищутся
частные решения задачи и анализируется их поведение в различных областях. В то
же время, вычисление дискретных преобразований Фурье на компьютере не
представляет сложности ввиду наличия многочисленного семейства алгоритмов БПФ.
Эти алгоритмы используют симметрию для понижения асимптотической сложности с
квадратичной $\mathcal{O}(n^2)$ до $\mathcal{O}(n \log_2 n)$. Таким образом,
метод Фурье подходит для поиска аналитических частных решений ДУЧП, а общее
решение, полученное этим методом, может стать основой для построения
высокопроизводительных \emph{гибридных} методов решения ДУЧП, в которых
преобразования Фурье от неизвестных функций производятся численно.

Альтернативным подходом, который повсеместно применяется в решении ДУЧП,
является сведение их к разностным уравнениям, решаемым с помощью построения
различных численных схем. При этом решение получается приближенным, а сложность
алгоритмов сопоставима со сложностью алгоритма БПФ. Например, стационарное
эллиптическое уравнение в частных производных преобразуется в неявную разностную
схему, решаемую итерационным методом, на каждом шаге которого ищется решение
трехдиагональной или пятидиагональной СЛАУ методом прогонки (алгоритм Томаса).
Асимптотическая сложность алгоритма составляет $\mathcal{O}(n m)$, где $n$ ---
количество точек на сетке взволнованной поверхности, $m$ --- число итераций.

С вычислительной точки зрения наличие большого количества преобразований Фурье в
решении является преимуществом. Решения полученные с помощью метода Фурье явные,
а значит хорошо масштабируются на большое количество параллельно работающих
вычислительных ядер с использованием простейших приемов параллельного
программирования. Эти преимущества обусловили выбор метода Фурье в качестве
рабочего для получения явного аналитического решения задачи определения давлений
под взволнованной морской поверхностью.

*** Двухмерное поле скоростей
:PROPERTIES:
:CUSTOM_ID: sec:pressure-2d
:END:
**** Формула для жидкости бесконечной глубины.
Задача Робена для уравнения Лапласа в двух измерениях записывается как
\begin{align}
    \label{eq:problem-2d}
    & \phi_{xx}+\phi_{zz}=0,\\
    & \zeta_t + \zeta_x\phi_x = \frac{\zeta_x}{\sqrt{1 + \zeta_x^2}} \phi_x - \phi_z, & \text{на }z=\zeta(x,t).\nonumber
\end{align}
Для ее решения воспользуемся методом Фурье. Возьмем преобразование Фурье от
обоих частей уравнений Лапласа и получим
\begin{equation*}
    -4 \pi^2 \left( u^2 + v^2 \right)
    \Fourier{\phi(x,z)}(u,v) = 0,
\end{equation*}
откуда имеем $v = \pm i u$. Здесь и далее будет использоваться следующая
симметричная форма преобразования Фурье:
\begin{equation*}
    \Fourier{f(x,y)}(u,v) =
    \iint\limits_{-\infty}^{\phantom{--}\infty}
    f(x,y)
    e^{-2\pi i (x u + y v)}
    dx dy
\end{equation*}
Решение уравнения будем искать в виде обратного преобразования Фурье
$\phi(x,z) = \InverseFourier{E(u,v)}(x,z)$. Применяя полученное равенство со знаком
"+"\footnote{Выражение $v = - i u$ не подходит в данной задаче, поскольку
потенциал скорости должен стремиться к нулю с увеличением глубины (с уменьшением
$z$).}, решение можно переписать как
\begin{equation}
    \label{eq:guessed-sol-2d}
    \phi(x,z) = \InverseFourier{e^{2\pi u z}E(u)}(x).
\end{equation}
Для того чтобы подстановка $z=\zeta(x,t)$ не помешала использованию
преобразований Фурье в решении, перепишем eqref:eq:guessed-sol-2d в виде
свертки:
\begin{equation*}
    \phi(x,z)
    =
    \Fun{z}
    \ast
    \InverseFourier{E(u)}(x),
\end{equation*}
где $\Fun{z}$ --- некоторая функция, вид которой будет определен в
[[#sec:compute-delta]] и для которой выполняется соотношение
$\Fourier{\Fun{z}}(u) = e^{2\pi u z}$. Подставляя выражение для
$\phi$ в граничное условие, получим
\begin{equation*}
    \zeta_t
    =
    \left( i f(x) - 1 \right)
    \left[
        \Fun{z}
        \ast
        \InverseFourier{2\pi u E(u)}(x)
    \right],
\end{equation*}
где $f(x) = {\zeta_x}/{\sqrt{1 + \zeta_x^2}} - \zeta_x$. Применяя преобразование
Фурье к обеим частям, получаем выражение для коэффициентов $E$:
\begin{equation*}
    E(u) =
    \frac{1}{2\pi u}
    \frac{
    \Fourier{\zeta_t / \left(i f(x) - 1\right)}(u)
    }{
    \Fourier{\Fun{z}}(u)
    }
\end{equation*}
Выполняя подстановку $z=\zeta(x,t)$ и подставляя полученное выражение в
eqref:eq:guessed-sol-2d, получаем окончательное выражение для $\phi(x,z)$:
\begin{equation}
    \label{eq:solution-2d}
    \boxed{
        \phi(x,z)
        =
        \InverseFourier{
            \frac{e^{2\pi u z}}{2\pi u}
            \frac{
            \Fourier{ \zeta_t / \left(i f(x) - 1\right) }(u)
            }{
            \Fourier{ \Fun{\zeta(x,t)} }(u)
            }
        }(x).
    }
\end{equation}

Множитель $e^{2\pi u z}/(2\pi u)$ делает график функции от которой берется
обратное преобразования Фурье несимметричным относительно оси OY. Это затрудняет
применение БПФ, поскольку оно требует периодичную функцию, которая на концах
промежутка принимает нулевое значение. Реализация же этого обратного
преобразования с помощью численного интегрирования не позволит получить
преимущество над решением всей системы уравнений с помощью разностных схем.
Решением проблемы является использование формулы eqref:eq:solution-2d-full для
жидкости конечной глубины с заведомо большим значением глубины водоема $h$.

**** Формула для жидкости конечной глубины.
На дне водоема вертикальная составляющая скорости перемещения жидкости должна
равняться нулю, т.е. $\phi_z=0$ на $z=-h$, где $h$ --- глубина водоема. В этом
случае пренебречь равенством $v = -i u$, полученным из уравнения Лапласа,
нельзя, и решение ищется в виде
\begin{equation}
    \phi(x,z)
    =
    \InverseFourier{
        \left( C_1 e^{2\pi u z} + C_2 e^{-2\pi u z} \right)
        E(u)
    }(x).
    \label{eq:guessed-sol-2d-full}
\end{equation}
Подставляя $\phi$ в условие на дне водоема, получим
\begin{equation*}
    C_1 e^{-2\pi u h} - C_2 e^{2\pi u h} = 0,
\end{equation*}
откуда имеем $C_1=\frac{1}{2} C e^{2\pi u h}$ и $C_2=-\frac{1}{2}C e^{-2\pi u
h}$. Константа $C$ здесь произвольна, поскольку при подстановке станет частью
неизвестных коэффициентов $E(u)$. Подставляя полученные выражения для $C_1$ и
$C_2$ в eqref:eq:guessed-sol-2d-full, получаем выражение
\begin{equation*}
    \phi(x,z) = \InverseFourier{ \Sinh{2\pi u (z+h)} E(u) }(x).
\end{equation*}
Выполняя аналогичные предыдущему разделу операции, получаем окончательное
выражение для $\phi(x,z)$:
\begin{equation}
\boxed{
    \phi(x,z,t)
    =
  \InverseFourier{
        \frac{\Sinh{2\pi u (z+h)}}{2\pi u}
        \frac{
            \Fourier{ \zeta_t / \left(i f(x) - 1\right) }(u)
        }{
            \Fourier{ \FunSecond{\zeta(x,t)} }(u)
        }
    }(x),
}
    \label{eq:solution-2d-full}
\end{equation}
где $\FunSecond{z}$ --- некоторая функция, вид которой будет определен в
[[#sec:compute-delta]] и для которой выполняется соотношение
$\Fourier{\FunSecond{z}}(u) = \Sinh{2\pi u z}$.

**** Сведение к формулам линейной теории волн.
Справедливость полученных формул проверим, подставив в качестве $\zeta(x,t)$
известные аналитические выражения для плоских волн. Для вычисления
преобразований Фурье символьно воспользуемся пакетом Mathematica
cite:mathematica10. В линейной теории широко используется предположение о
малости амплитуд волн, что позволяет упростить исходную систему уравнений
eqref:eq:problem-2d до
\begin{align*}
    & \phi_{xx}+\phi_{zz}=0,\\
    & \zeta_t = -\phi_z & \text{на }z=\zeta(x,t),
\end{align*}
решение которой запишется как
\begin{equation*}
    \phi(x,z,t)
    =
    -\InverseFourier{
        \frac{e^{2\pi u z}}{2\pi u}
        \Fourier{\zeta_t}(u)
    }(x)
    .
\end{equation*}
# Таким образом, в линейном случае потенциал скорости волн малых амплитуд равен
# свертке производной по времени от функции, описывающей взволнованную
# поверхность, с ... (TODO).

\noindent Профиль прогрессивной волны описывается формулой
$\zeta(x,t)=A\cos(2\pi (k x - t))$. Подстановка этого выражения в формулу для
бесконечной глубины дает равенство $\phi(x,z,t)=-\frac{A}{k} \sin (2 \pi (k x -
t)) \Sinh{2 \pi k z}$. Чтобы свести его к формуле линейной теории волн,
необходимо представить гиперболический синус в экспоненциальной форме и
отбросить член, содержащий $e^{-2\pi k z}$, как противоречащий условию
$\phi\underset{z\rightarrow-\infty}{\longrightarrow}0$. После взятия
действительной части выражения получится формула линейной теории $\phi(x,z,t) =
\frac{A}{k} e^{2 \pi k z} \sin(2 \pi (k x - t))$. Аналогично, предположение о
малости амплитуд волн позволяет упростить формулу eqref:eq:solution-2d-full до
\begin{equation*}
    \phi(x,z,t)
    =
    -\InverseFourier{
        \frac{\Sinh{2\pi u (z+h)}}{2\pi u \Sinh{2\pi u h}}
        \Fourier{\zeta_t}(u)
    }(x).
\end{equation*}
Подстановка формулы для прогрессивной плоской волны в это выражение дает
равенство
\begin{equation}
\label{eq:solution-2d-linear}
\phi(x,z,t)=\frac{A}{k} \frac{\Sinh{2 \pi k (z+h)}}{ \Sinh{2 \pi k h} } \sin (2 \pi (k x-t)),
\end{equation}
что соответствует формуле линейной теории для конечной глубины.

Различная запись решения уравнения Лапласа, в котором затухающая экспонента
может встречаться как со знаком "+", так и со знаком "-", может стать
причиной разницы в формуле, где вместо $\cosh$ будет использоваться $\sinh$.
Выражение $\frac{\Sinh{2 \pi k (z+h)}}{ \Sinh{2 \pi k h} } \approx \frac{\cosh
(2 \pi k (z+h))}{ \cosh (2 \pi k h) }$ превращается в строгое равенство на
поверхности, и разница между правой левой частью увеличивается при приближении к
дну водоема (для достаточно большой глубины ошибка вблизи поверхности жидкости
незначительна), поэтому на практике для расчетов вблизи взволнованной поверности
можно использовать любую из функций.

Сведение формул eqref:eq:solution-2d и eqref:eq:solution-2d-full к формулам
линейной теории волн показало, что формула eqref:eq:solution-2d не подходит для
расчета потенциала на бесконечной глубине с использованием численных методов,
т.к. не обладает необходимой для применения быстрого преобразования Фурье
симметрией. Для такого случая можно использовать формулу для конечной глубины,
полагая $h$ равным характерному значению глубины исследуемого водоема. Для
стоячих волн сведение к формулам линейной теории происходит с аналогичными
предположениями.
*** Трехмерное поле скоростей
В трех измерениях исходная система уравнений eqref:eq:problem переписывается как
\begin{align}
    \label{eq:problem-3d}
    & \phi_xx + \phi_yy + \phi_zz = 0,\\
    & \zeta_t + \zeta_x\phi_x + \zeta_y\phi_y
    =
    \frac{\zeta_x}{\sqrt{1 + \zeta_x^2}} \phi_x
    +\frac{\zeta_y}{\sqrt{\vphantom{\zeta_x^2}\smash[b]{1 + \zeta_y^2}}} \phi_y
    - \phi_z, & \text{на }z=\zeta(x,y,t).\nonumber
\end{align}
Для ее решения воспользуемся методом Фурье. Возьмем преобразование Фурье от
обоих частей уравнений Лапласа и получим
\begin{equation*}
    -4 \pi^2 \left( u^2 + v^2 + w^2 \right)
    \Fourier{\phi(x,y,z)}(u,v,w) = 0,
\end{equation*}
откуда имеем $w = \pm i \sqrt{u^2 + v^2}$. Решение уравнения будем искать в виде
обратного преобразования Фурье $\phi(x,y,z) = \InverseFourier{E(u,v,w)}(x,y,z)$.
Применяя полученное равенство, получаем
\begin{equation*}
    \phi(x,y,z) = \InverseFourier{
        \left(
            C_1 e^{2\pi \sqrt{u^2+v^2} z}
            -C_2 e^{-2\pi \sqrt{u^2+v^2} z}
        \right)
        E(u,v)
    }(x,y).
\end{equation*}
Подставляя $\phi$ в условие на дне водоема аналогично двухмерному случаю,
получаем
\begin{equation}
    \label{eq:guessed-sol-3d}
    \phi(x,y,z) = \InverseFourier{
        \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)
    }(x,y).
\end{equation}
Подставляя выражение для $\phi$ в граничное условие, получим
\begin{equation*}
    \arraycolsep=1.4pt
    \begin{array}{rl}
        \zeta_t = & i f_1(x) \InverseFourier{2 \pi u \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}(x,y) \\
        + & i f_2(x) \InverseFourier{2 \pi v \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}(x,y) \\
        - & \InverseFourier{2 \pi \sqrt{u^2+v^2} \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}(x,y)
    \end{array}
\end{equation*}
где $f_1(x,y) = {\zeta_x}/{\sqrt{1 + \zeta_x^2}} - \zeta_x$ и
$f_2(x,y) = {\zeta_y}/{\sqrt{\vphantom{\zeta_x^2}\smash[b]{1 + \zeta_y^2}}} - \zeta_y$.
Применяя преобразование Фурье к обеим частям, получаем выражение для коэффициентов $E$:
\begin{equation*}
    \arraycolsep=1.4pt
    \begin{array}{rl}
        \Fourier{\zeta_t}(u,v) = &
        \Fourier{i f_1(x) \InverseFourier{2 \pi u \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}}(x,y)}(u,v)  E(u,v)\\
        + & \Fourier{i f_2(x) \InverseFourier{2 \pi v \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}}(x,y)}(u,v)  E(u,v)\\
        - & 2 \pi \sqrt{u^2+v^2} \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)
    \end{array}
\end{equation*}
Окончательное решение получается при подстановке выражения для $E(u,v)$
в eqref:eq:guessed-sol-3d.

* Численные методы и результаты экспериментов
** Форма АКФ для разных волновых профилей
*** Два метода для определения формы АКФ
**** Аналитический метод.
**** Эмпирический метод.
*** Примеры АКФ для различных волновых профилей
**** АКФ стоячей волны.
**** АКФ прогрессивной волны.
*** Сравнение изученных методов
** Дополнительные формулы, методы и алгоритмы для модели АРСС
*** Аппроксимация распределения аппликат
Одним из входных параметров генератора взволвнованной морской поверхности служит
фнукция распределения волновых аппликат, которая может быть задана
полиномиальной аппроксимацией натурных данных или аналитически.

В cite:huang1980experimental было экспериментально показано, что распределение
аппликат взволнованной морской поверхности отличается от нормального ненулевым
экцессом и асимметрией. В cite:рожков1996теория показано, что такое
распределение можно разложить в ряд Грама---Шарлье:
\begin{align}
    \label{eq:skew-normal-1}
    F(z; \gamma_1, \gamma_2) & = \phi(z) - \gamma_1 \frac{\phi'''(z)}{3!} + \gamma_2 \frac{\phi''''(z)}{4!} \nonumber \\
    & =
    \frac{1}{2} \text{erf}\left[\frac{z}{\sqrt{2}}\right]
    -
    \frac{e^{-\frac{z^2}{2}}}{\sqrt{2\pi}}
    \left[
        \frac{1}{6} \gamma_1 \left(z^2-1\right)
        + \frac{1}{24} \gamma_2 z \left(z^2-3\right)
    \right]
    ,\nonumber \\
    f(z; \gamma_1, \gamma_2) & =
    \frac{e^{-\frac{z^2}{2}}}{\sqrt{2 \pi }}
    \left[
        \frac{1}{6} \gamma_1 z \left(z^2-3\right)
        + \frac{1}{24} \gamma_2 \left(z^4-6z^2+3\right)
        +1
    \right],
\end{align}
где $\phi(z)=\frac{1}{2}\mathrm{erf}(z/\sqrt{2})$, $\gamma_1$ --- асимметрия,
$\gamma_2$ --- эксцесс, $f$ --- плотность распределения, $F$ --- функция
распределения. Согласно cite:рожков1990вероятностные для аппликат морских волн
значение асимметрии выбирается на интервале $0.1 \leq \gamma_1 \leq 0,52]$, а
значение эксцесса на интервале $0,1 \leq \gamma_2 \leq 0,7$. Вид плотности
распределения при различных параметрах показан на [[fig:skew-normal-1]].

#+begin_src gnuplot :exports none
set loadpath GPVAL_PWD."/gnuplot"
system "mkdir -p build"
cd "build"

load 'style.gnuplot'
#load 'style-paper.gnuplot'

set terminal svg fixed enhanced size 1920/5,900/3 font 'Old Standard, 12' dashed rounded
set key top center Left reverse width -10 maxrows 2
set xlabel 'z' offset 0,0.33
set ylabel 'f(z)' offset 2,0

set xrange [-3:3]
set ytics 0,0.1
set yrange [0:0.6]

skew_normal_1(z, skewness, kurtosis) = (24 + 4*z*(-3 + z**2)* \
      skewness + (3 - 6*z**2 + z**4)* kurtosis)/(24*(exp((z**2)/2)*sqrt(2*pi)))

#print skew_normal_1(1, 0.6, 1.0)
# regular gamma γ

set output 'skew-normal-1.svg'
plot \
skew_normal_1(x, 0, 0) with lines ls 1 title '𝛾_1=0, 𝛾_2=0', \
skew_normal_1(x, 0.52, 0) with lines ls 2 title '𝛾_1=0.52, 𝛾_2=0', \
skew_normal_1(x, 0, 0.7) with lines ls 3 title '𝛾_1=0, 𝛾_2=0.7', \
skew_normal_1(x, 0.52, 0.7) with lines ls 4 title '𝛾_1=0.52, 𝛾_2=0.7'
system "inkscape --without-gui --export-eps=skew-normal-1.eps skew-normal-1.svg

skew_normal_2(z, alpha) = \
  erfc( -((z*alpha)/sqrt(2)) ) / \
  (exp((z**2)/2)*sqrt(2*pi))

skewness(alpha) = \
  (sqrt(2) * (4 - pi) * (alpha**3)) \
  / \
  (sqrt(pi + (pi-2) * (alpha**2))**3)

kurtosis(alpha) = \
  (8*(-3 + pi)*(alpha**4))/ \
  ((pi + (-2 + pi)*(alpha**2))**2)

set terminal svg fixed enhanced size 1920/4,900/3 font 'Times, 12' dashed rounded
set key top left Left reverse maxcols 1 maxrows 4
set yrange [0:0.8]
set output 'skew-normal-2.svg'
alphas="0.00 0.87 2.25 4.90"
a(i) = word(alphas, i)
plot for [i=1:words(alphas)] \
skew_normal_2(x, a(i)) with lines ls i \
title 'α='.a(i).', 𝛾_1='.sprintf('%.2f',skewness(a(i))).', 𝛾_2='.sprintf('%.2f',kurtosis(a(i)))
system "inkscape --without-gui --export-eps=skew-normal-2.eps skew-normal-2.svg

exit
#+end_src

#+RESULTS:


#+name: fig:skew-normal-1
#+caption: Вид плотности распределения eqref:eq:skew-normal-1 волновых аппликат при различных значениях асимметрии $\gamma_1$ и эксцесса $\gamma_2$.
[[file:build/skew-normal-1.eps]]

Альтернативной аппроксимацией распределения волновых аппликат служит формула
асимметричного нормального распределения:
\begin{align}
    \label{eq:skew-normal-2}
    F(z; \alpha) & = \frac{1}{2}
   \mathrm{erfc}\left[-\frac{z}{\sqrt{2}}
   \right]-2 T(z,\alpha ), \nonumber \\
    f(z; \alpha) & = \frac{e^{-\frac{z^2}{2}}}{\sqrt{2 \pi }}
   \mathrm{erfc}\left[-\frac{\alpha z}{\sqrt{2}}\right],
\end{align}
где $T$ --- функция Оуэна cite:owen1956tables. Эта формула не позволяет задать
значения аимметрии и эксцесса по отдельности --- оба значения регулируются
параметром $\alpha$. Преимущество данной формулы лишь в относительной простоте
вычисления: в некоторые программы и библиотеки математических функций встроена
либо она сама, либо функция Оуэна и функция ошибки. График функции для разных
значений $\alpha$ представлен на рис. [[fig:skew-normal-2]].

#+name: fig:skew-normal-2
#+caption: Вид плотности распределения eqref:eq:skew-normal-2 волновых аппликат при различных значениях коэффициента асимметрии $\alpha$.
[[file:build/skew-normal-2.eps]]

Решение уравнения eqref:eq:distribution-transformation с выбранной функцией
распределения можно произвести в каждой точке сгенерированной поверхности, что
даст наиболее точные результаты, но с вычислительной точки зрения эффективнее
решить это уравнение в фиксированных узлах, а затем интерполировать решение
методом наименьших квадратов (МНК). В этом случае точность будет меньше. Так для
многочлена 12-го порядка и интерполяционной сетке из 500 узлов, построенной на
промежутке $-5\sigma_z \leq z \leq 5\sigma_z$, погрешность составляет
$\approx0,43\cdot10^{-3}$. Увеличение порядка многочлена приводит либо к переполнениям
при интерполяции МНК, либо к дополнительным коэффициентам близким к нулю;
увеличение количества узлов влияет на результат незначительно. В большинстве
случаев трех коэффициентов ряда Грама---Шарлье было достаточно для
преобразования автоковариационной функции; относительная погрешность без
интерполяции составляет $10^{-5}$.

*** Алгоритм генерации белого шума
Чтобы исключить периодичность из сгенерированной моделью ветрового волнения
реализации взволнованной поверхности, нужно использовать ГПСЧ с достаточно
большим периодом. В качестве такого генератора в работе используется
параллельная реализация вихря Мерсенна cite:matsumoto1998mersenne с периодом
$2^{19937}-1$. Если предположить, что взволнованная поверхность генерируется на
сетке размера $1000\times1000$ и шаг по времени составляет 1 сек., то вихрь
Мерсенна позволяет сгенерировать неповторяющуюся последовательность
астрономической временной протяженности. Этого более чем достаточно для
практического применения генератора в задаче моделирования морского волнения.

Запуск нескольких ГПСЧ с разными начальными состояниями в параллельных
потоках не гарантирует некоррелированность генерируемых последовательностей
псевдослучайных чисел, и, чтобы избежать этого, в работе используется алгоритм
динамического создания вихрей Мерсенна cite:matsumoto1998dynamic. Суть
алгоритма заключается в поиске таких матриц начальных состояний генераторов,
которые бы дали максимально некоррелированные последовательности
псевдослучайных чисел при параллельном запуске нескольких вихрей Мерсенна с
этими начальными состоянями. Поскольку поиск начальных состояний может занимать
значительно большее время чем генерация белого шума, то вектор состояний
создается предварительно для заведомо большего количества параллельных потоков.
Вектор состояний сохраняется в файл, который впоследствиии считывается основной
программой перед началом генерации псевдослучаных чисел.

*** Алгоритм генерации взволнованной поверхности
В модели АРСС значение подъема взволнованной поверхности в каждой точке зависит
от предыдующих по пространству и времени значений, из-за чего в начале
реализации образуется \emph{интервал разгона} --- промежуток, на котором
реализация не соответствуют заданной АКФ. Способ решения этой проблемы зависит
от контекста, в котором используется реализация.
- Если реализация используется в контексте расчета остойчивости судна без учета
  маневрирования, то интервал никак не повлияет результаты эксперимента,
  поскольку находится на границе (далеко от исследуемого морского объекта).
- Если изучается остойчивость судна в условиях маневрирования, то интервал проще
  всего исключить из реализации (размер интервала примерно равен числу
  коэффициентов авторегрессии по каждому из измерений). Однако, это приводит к
  потере большого числа точек, поскольку исключение происходит по каждому из
  трех измерений.
- Альтернативным подходом является предварительная генерация
  взволнованной поверхности на интервале разгона моделью Лонге---Хиггинса
  и генерация остальной реализации с помощью авторегрессионной модели.

В алгоритме генерации взволнованной поверхности используется
параллелизм по данным: реализация делится на равные части, каждая из которых
генерируется независимо, --- однако, в начале каждой из частей также
присутствует интервал разгона. Для его исключения подходит метод
\emph{сшивания}, часто применяемый в обработке цифровых
сигналов cite:oppenheim1989discrete,svoboda2011efficient,pavel2013algorithms.
Суть метода заключается в добавлении интервала равного по размеру интервалу
разгона в конец каждой из частей. На этом интервале также генерируется
взволнованная поверхность, а после генерации интервал в конце части $N$
накладывается на интервал разгона в начале части $N+1$, и значения в
соответсвтующих точках складываются.

*** Формулы нормировки для потенциалов скоростей
:PROPERTIES:
:CUSTOM_ID: sec:compute-delta
:END:

В решениях двухмерной задачи eqref:eq:solution-2d и eqref:eq:solution-2d-full
присутствуют функции $\Fun{z}=\InverseFourier{e^{2\pi u z}}(x)$ и
$\FunSecond{z}=\InverseFourier{\Sinh{2\pi u z}}(x)$, которые могут быть
представлены аналитически различными выражениями, представляющими сложность для
вычислений на компьютере. Каждая из функций является преобразованием Фурье от
линейной комбинации экспонент, которое для таких функций определено неоднозначно
(см. [[tab:delta-functions]]). Для получения однозначного аналитического выражения
можно воспользоваться нормировкой $1/\Sinh{2 \pi u h}$, которая также включается
в выражение для коэффициентов $E(u)$. Численные эксперименты показывают, что
нормировка хоть и позволяет получить решение с адекватными величинами
потенциалов скорости, оно мало отличается от выражений из линейной теории волн,
в которых члены с $\zeta$ опускаются.

#+name: tab:delta-functions
#+caption: Формулы вычисления функций $\Fun{z}$ и $\FunSecond{z}$ из [[#sec:pressure-2d]], использующие нормировку для исключения неоднозначности определения дельта функции комплексного аргумента.
#+attr_latex: :booktabs t
| Функция         | Без нормировки                                             | С нормировкой                                                                                                                        |
|-----------------+------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------|
| $\Fun{z}$       | $\delta (x+i z)$                                           | $\frac{1}{2 h}\mathrm{sech}\left(\frac{\pi  (x-i (h+z))}{2 h}\right)$                                                                |
| $\FunSecond{z}$ | $\frac{1}{2}\left[\delta (x-i z) + \delta (x+i z) \right]$ | $\frac{1}{4 h}\left[\text{sech}\left(\frac{\pi  (x-i (h+z))}{2 h}\right)+\text{sech}\left(\frac{\pi  (x+i(h+z))}{2 h}\right)\right]$ |

** Верификация модели АРСС
:PROPERTIES:
:CUSTOM_ID: sec:verification
:END:
*** Методика постановки численных экспериментов
*** Верификация интегральных характеристик взволнованной поверхности
Отличительной особенностью авторегрессионной модели ветрового волнения является
ее нефизическое происхождение: она возникла не в результате решения системы
уравнений Навье---Стокса в некотором приближении, а как решение ряда проблем, с
которыми столкнулись исследователи, использовавшие модель Лонге---Хиггинса на
практике. Для использования авторегрессионной модели на практике в ряде
экспериментов были исследованы различные характеристики генерируемой ей
реализации и сопоставлены с соответствующими характеристиками реальной
взволнованной морской поверхности.

Для авторегрессионной модели в работах
cite:degtyarev2011modelling,degtyarev2013synoptic,boukhanovsky1997thesis
экспериментальным путем были верифицированы
- распределения различных характеристик волн (высоты волн, длины волн, длины гребней, период волн, уклон волн, показатель трехмерности),
- дисперсионное соотношение,
- сохранение интегральных характеристик для случая смешанного волнения.

*** Верификация полей потенциалов скоростей
:PROPERTIES:
:CUSTOM_ID: sec:compare-formulae
:END:
Сравнение полученных общих формул eqref:eq:solution-2d и
eqref:eq:solution-2d-full с известными формулами линейной теории волн позволяет
оценить различие между полями скоростей для волн как больших, так и малых
амплитуд. В общем случае получить аналитическое выражение даже для плоских волн
не представляется возможным, поэтому сравнение производится численно. Имея ввиду
выводы раздела [[#sec:pressure-2d]], сравниваются только формулы для случая конечной
глубины.

**** Отличие от формул линейной теории.
В ходе численного эксперимента результаты, полученные по формуле
eqref:eq:solution-2d-full для конечной глубины были сопоставлены с результатами,
полученными по соответсвующей формуле eqref:eq:solution-2d-linear линейной
теории, и проверка показала качественные различия в получившихся полях
потенциалов скоростей (см. [[fig:potential-field-nonlinear]]). Во-первых,
потенциальные линии имеют вид затухающей синусоиды, что отличается от овальной
формы, описываемой в линейой теории волн. Во-вторых, по мере приближения к дну
водоема потенциал гораздо быстрее затухает, чем описывается в линейной теории, а
область, где сконцентрирована большая часть энергии волны, еще больше приближена
к ее гребню. Аналогичный численный эксперимент, в котором из формулы
eqref:eq:solution-2d-full были исключены члены, которыми пренебрегают в рамках
линейной теории волн, показал, что полное соотвествие получившихся полей
потенциалов скоростей (насколько это позволяет сделать машинная точность).

#+name: fig:potential-field-nonlinear
#+caption: Поле потенциала скорости прогрессивной волны $\zeta(x,y,t) = \cos(2\pi x - t/2)$. Поле, полученное по формуле eqref:eq:solution-2d-full (слева) и по формуле линейной теории волн (справа).
#+attr_latex: :width 0.47\textwidth
#+begin_figure
[[file:graphics/pressure/potential-5.eps]]
[[file:graphics/pressure/potential-6.eps]]
#+end_figure

**** Отличие от формул теории волн малой амплитуды.
В ходе численного эксперимента результаты, полученные по формуле
eqref:eq:solution-2d-full были сопоставлены с результатами, полученными по
формуле для волн малой амплитуды eqref:eq:old-sol-2d, и проверка показала
схожесть полей скоростей, вычисленных этими методами. Для определения скоростей
использовалась реализации морской поверхности, построенные по авторегрессионной
модели и различающиеся амплитудой волн. При этом интегрирование в формуле
eqref:eq:solution-2d-full велось по соответствующему сгенерированной морской
поверхности интервал волновых чисел. Эксперименты проводились для волн разных
амплитуд, и для волн малой амплитуды оба метода показывают сопоставимые
результаты, в то время как для волн высоких амплитуд стабильное поле скоростей
дает только формула eqref:eq:solution-2d-full (см. [[fig:velocity-field-2d]]). Таким
образом, полученная формула показывает удовлетворительные результаты для
различных морских поверхностей, не вводя ограничения на величины амплитуд волн.

#+begin_src gnuplot :exports none
set loadpath GPVAL_PWD."/gnuplot" GPVAL_PWD."/data/velocity"
system "mkdir -p build"
cd "build"

set terminal svg size 320, 200 font "Open Sans Regular, 12" linewidth 1 enhanced rounded dashed

load 'linestyle.gnuplot'

unset border
set border 3
set xtics nomirror out offset 0,0.5
set ytics nomirror out offset 0.5,0

set xrange [0:90]
set yrange [-2:4]
set xtics 0,30
set ytics -2,2,4
set xlabel 'x' offset 0,1
set ylabel 'u(x)' offset 1.75,0

set output 'high-amp-nocolor.svg'
plot 'high-amp'   title 'u_1(x)' ls 1 smooth csplines, \
     'high-amp-0' title 'u_2(x)' ls 2 smooth csplines
system "inkscape --without-gui --export-eps=high-amp-nocolor.eps high-amp-nocolor.svg

set output 'low-amp-nocolor.svg'
plot 'low-amp'   title 'u_1(x)' ls 1 smooth csplines, \
     'low-amp-0' title 'u_2(x)' ls 2 smooth csplines
system "inkscape --without-gui --export-eps=low-amp-nocolor.eps low-amp-nocolor.svg

exit
#+end_src

#+RESULTS:

#+name: fig:velocity-field-2d
#+caption: Сравнение полей скоростей на поверхности моря, полученных по общей формуле ($u_1$) и формуле для волн малой амплитуды ($u_2$). Поле скоростей для поверхности волн малой амплитуды (слева) и большой амплитуды (справа).
#+begin_figure
[[file:build/low-amp-nocolor.eps]]
[[file:build/high-amp-nocolor.eps]]
#+end_figure

*** TODO Нефизическая природа модели
* Высокопроизводительный программный комплекс для моделирования морского волнения
** Модель вычислений
*** Основополагающие принципы модели
*** Отображение алгоритма генерации взволнованной поверхности на вычислительную модель
** Реализация для систем с общей памятью (SMP)
*** Алгоритм распределения нагрузки
*** Результаты тестирования
**** Производительности реализаций на MPI, OpenMP и OpenCL.
**** Производительность алгоритма распределения нагрузки.
** Реализация для систем с распределенной памятью (MPP)
*** Алгоритм обнаружения узлов кластера
*** Алгоритм восстановления после сбоев
**** Обеспечение отказоустойчивости.
**** Обеспечение высокой доступности.
* Заключение
**** Итоги исследования.
В изучении возможностей математического аппарата для имитационного моделирования
морского волнения, выходящего за рамки линейной теории волн, были достигнуты
следующие основные результаты.
- Разработана модель ветрового волнения для генерации волн произвольных
  амплитуд.
- Разработан гибридный метод расчета давлений в двухмерной постановке,
  использующий как аналитические выражения, так и численное интегрирование по
  алгоритму быстрого преобразования Фурье.
- Разработанный метод позволил упростить программную реализацию комплекса, и
  свести реализацию алгоритма к параллельному вычислению большого количества
  преобразований Фурье.
- Предварительная апробация авторегрессионной модели и метода расчета давлений
  была произведена в пакете Large Amplitude Motion Program 4.

**** Перспективы дальнейших исследований.
Хотя задача генерации взволнованной морской поверхности была решена в трехмерной
постановке, для задачи расчета гидродинамических давлений было найдено
аналитическое решение только в двухмерном случае. В трехмерной постановке
полученные формулы не были всесторонне исследованы. Таким образом, дальнейшие
исследования предполагают изучение аналитического решения для трехмерный случая,
а также создание виртуального полигона на основе модели АРСС и метода расчета
давлений по результатам апробации в пакете Large Amplitude Motion Program 4.

* Выводы
Результаты исследования позволяют сделать вывод о том, что задача вычисления
давлений под реальной морской поверхностью может быть решена аналитически в
двухмерной постановке, минуя предположения линейной теории волн и теории волн
малой амплитуды. Это аналитическое решение в паре с моделью АРСС ветрового
волнения, способной генерировать волны произвольных амплитуд, может быть
использовано для расчета влияния колебаний волн на поведение динамического
объекта в открытом море, и дает более точные результаты чем аналогичное решение
для волн малых амплитуд. Результаты проведенных экспериментов позволяют сделать
вывод о том, что как генерация взволнованной поверхности так и расчет
гидродинамических давлений могут быть реализованы эффективно с использованием
алгоритмов быстрого преобразования Фурье, а распределенная система научных
расчетов может быть использвана для длительных сессий имитационного
моделирования. Разработанный в работе математический аппарат и его программная
реализация могут стать основой виртуального полигона, предназанченного для
расчетов динамики морских объектов.

* TODO Благодарности
Исследования были проведены с использованием вычислительных ресурсов Ресурсного
Центра "Вычислительный центр СПбГУ" ([[http://cc.spbu.ru/]]) при поддержке
грантами РФФИ №16-07-01111, №16-07-00886 и грантом СПбГУ №0.37.155.2014.

#+latex: \clearpage
* Список сокращений и условных обозначений

#+attr_latex: :booktabs t :align lp{0.8\linewidth}
| <<<MPP>>>  | Massively Parallel Processing, класс вычислительных систем с разделенной памятью            |
| <<<SMP>>>  | Symmetric Multi-Processing, класс вычислительных систем с общей памятью                     |
| <<<АКФ>>>  | автоковариационная функция                                                                  |
| <<<БПФ>>>  | быстрое преобразование Фурье                                                                |
| <<<ГПСЧ>>> | генератор псевдослучайных чисел                                                             |
| <<<ГУ>>>   | граничное условие                                                                           |
| <<<ДУЧП>>> | дифференциальное уравнение в частных производных                                            |
| <<<НБП>>>  | нелинейное безынерционное преобразование                                                    |
| <<<АР>>>   | процесс авторегрессии                                                                       |
| <<<АРСС>>> | процесс авторегрессии скользящего среднего                                                  |
| <<<СС>>>   | процесс скользящего среднего                                                                |
| <<<ЛХ>>>   | модель Лонге---Хиггинса                                                                     |
| <<<LAMP>>> | Large Amplitude Motion Programme, программа для моделирования качки судна на морских волнах |
| <<<ЦПТ>>>  | центральная предельная теорема                                                              |

#+begin_latex
\input{postamble}
#+end_latex

bibliographystyle:ugost2008
bibliography:bib/refs.bib

* Приложение
** TODO Вывод формулы модели Лонге---Хиггинса
