#+TITLE: Высокопроизводительная модель морского волнения для программ динамики морских объектов
#+AUTHOR: Иван Ганкевич
#+DATE: Санкт-Петербург, 2016
#+LANGUAGE: ru
#+LATEX_CLASS: gost
#+LATEX_CLASS_OPTIONS: [hidelinks,fontsize=14pt,paper=a4,pagesize,DIV=calc]
#+LATEX_HEADER: \IfFileExists{./preamble.tex}{\input{preamble}}{}
#+LATEX_HEADER: \organization{Санкт-Петербургский государственный университет}
#+LATEX_HEADER: \manuscript{на правах рукописи}
#+LATEX_HEADER: \degree{Диссертация на соискание ученой степени\\кандидата физико-математических наук}
#+LATEX_HEADER: \speciality{Специальность 05.13.18\\Математическое моделирование, численные методы и комплексы программ}
#+LATEX_HEADER: \supervisor{Научный руководитель\\д.т.н Дегтярев Александр Борисович}
#+OPTIONS: todo:nil title:nil toc:nil H:5

#+begin_latex
\tableofcontents
\clearpage
#+end_latex

* Введение
**** Актуальность темы.
Программы, моделирующие воздействие морских волн на судно, плавучую платформу
или какой-либо другой морской объект, широко используются для расчета качки
судна, определения воздействия внешних сил на структуру морского объекта, а
также для моделирования затопления и других процессов, вызываемых
взаимодействием объекта с морскими волнами; однако, большинство из них
используют линейную теорию для моделирования морского волнения
cite:shin2003nonlinear,van2007forensic,kat2001prediction,van2002development, что
не позволяет моделировать некоторые особенности ветроволнового климата. Среди
них можно выделить переход от нормальных погодных условий к шторму и волнение,
вызванное наложением множества систем ветровых волн и волн зыби,
распространяющихся в разных направлениях. Другой особенностью этих программ
является использование теории волн малой амплитуды, т.е. волн, амплитуда которых
много меньше, чем их длина. Это делает расчеты грубыми, и не позволяет
моделировать качку судна в условиях нерегулярного волнения, когда такое
предположение несправедливо. Ввиду описанных сложностей разработка более
совершенных моделей и методов, используемых при расчете динамики судна, является
актуальной задачей на сегодняшний день.
**** Степень разработанности.
Особенностью комплексов расчета динамики судов является использование линейных
моделей ветрового волнения, и, хотя эти модели хорошо исследованы, их
вычислительная эффективность не всегда достаточна для проведения длительных
численных экспериментов. Например, в случае модели Лонге---Хиггинса для
увеличения временной протяженности реализации морского волнения может
понадобится увеличить количество частот спектра на входе для исключения
периодичности, что приводит к нелинейному увеличению времени генерации с ростом
длины реализации. В случае альтернативных моделей ветрового
волнения для расчета давлений используются методы вычислительной гидродинамики,
обладающие меньшей эффективностью, чем аналитические методы, разработанные для
для линейной модели. Таким образом, степень разработанности используемых на
практике моделей ветрового волнения и методов расчета давлений не позволяет
эффективно проводить длительные численные эксперименты, а уход от линейной
модели приведет к качественному улучшению результатов экспериментов и будет
способствовать проведению исследований возникающих редко экстремальных ситуаций,
связанных с потерей остойчивости (например, опрокидывание и брочинг).
**** Цели и задачи.
Основной целью работы является разработка математического и численного аппарата
имитационного моделирования морских волн для проведения длительных численных
экспериментов и определения величины создаваемого морскими волнами воздействия
на морские объекты. Основные задачи, решаемые в рамках работы:
- разработка модели ветрового волнения, способной генерировать реализации
  взволнованной морской поверхности, имеющие сверхбольшой период и состоящие из
  волн произвольной амплитуды;
- разработка метода расчета давлений, работающего с этой моделью и не
  использующего теорию волн малой амплитуды;
- разработка комплекса программ, реализующего созданную модель и метод расчета
  давлений и позволяющего проводить расчеты как на многопроцессорной машине с
  общей памятью, так и на компьютерном кластере.
**** Научная новизна.
Авторегрессионная модель в отличие от других моделей ветрового волнения не
основана на теории волн малой амплитуды, что позволяет учесть такие аспекты
океанских волн, как асимметричность распределения волновых аппликат. В то же
время математический аппарат этой модели хорошо разработан в других научных
областях, что позволяет обобщить модель для моделирования развития морского
волнения в условиях шторма с учетом климатических спектров и данных ассимиляции
определенных районов мирового океана.
**** Теоретическая и практическая значимость работы.
Применение альтернативной модели морского волнения и метода расчета давлений, не
использующего предположения о малости амплитуд волн и линейной теории волн,
позволит качественно повысить работу комплексов программ для расчета воздействия
океанских волн на морские объекты.
**** Методология и методы исследования.
Программная реализация авторегрессионной модели и методы вычислений давлений
была создана поэтапно: сначала был создан прототип на инженерном языке
высокого уровня (Mathematica, Octave), который затем был преобразован в
программу на языке более низкого уровня (C++). Для вывода аналитической формулы
расчета давлений использовался математический аппарат, проверка полученных
выражений осуществлялась с помощью системы компьютерной алгебры Mathematica.
**** Положения, выносимые на защиту.
- Модель ветрового волнения, способная генерировать реализации взволнованной
  морской поверхности, имеющие сверхбольшой период и состоящие из волн
  произвольной амплитуды;
- Метод расчета давлений, работающий с этой моделью и не использующий теорию
  волн малой амплитуды;
- Комплекс программ, реализующий созданную модель и метод расчета давлений и
  позволяющий проводить расчеты как на многопроцессорной машине с общей памятью,
  так и на компьютерном кластере.
**** Степень достоверности и апробация результатов.
Достоверность полученных результатов как по авторегрессионной модели так и по методу
вычислений давлений подтверждается многочисленными и всесторонними численными
экспериментами, целью которых было сравнение полученных результатов с поведением
реальных морских волн на основе имеющихся натурных данных. Апробация
производилась на системе Large Amplitude Motion Program (LAMP), в которой модель
авторегрессии и метод вычислений давлений были реализованы и сопоставлены с
используемыми ранее методами, основанными на теории волн малой амплитуды. Эти
проверки показали целесообразность применения и более высокую эффективность
альтернативной модели и метода расчета давлений ввиду их гидродинамической
адекватности и более высокой производительности.
* Постановка задачи
Задача состоит в применении авторегрессионной модели ветрового волнения для
генерации морских волн произвольной амплитуды и в определении поля давлений под
взволнованной морской поверхностью, сгенерированной этой моделью. Поле давлений
для случая идеальной несжимаемой жидкости определяется уравнением Лапласа со
смешанным граничным условием. Для случая волн малых амплитуд полученный решение
должно быть сопоставимо с известными формулами линейной теории волн; для
остальных случаев решение не должно расходиться. Результатом работы должна стать
программная реализация авторегрессионной модели и метода вычисления давлений,
эффективно работающая в распределенной вычислительной среде и на
многопроцессорной системе с общей памятью.
* Обзор литературы
** Анализ моделей ветрового волнения
*** Модель Лонге---Хиггинса
Вычисление давлений возможно только при условии знания формы взволнованной
поверхности, которая задается либо дискретно в каждой точке пространственной
сетки, либо непрерывно с помощью аналитической формулы, используемой для
генерации поверхности. Как будет показано в разделе [[#linear-boundary]], знание
такой формулы может упростить вычисление давлений, фактически сведя задачу к
генерации поля давлений, а не самой взволнованной поверхности.

Наиболее изученной и широко распространенной моделью ветрового волнения
является модель Лонге---Хиггинса cite:longuet1957statistical. Подробный
сравнительный анализ этой модели и модели авторегрессии проведен в работах
cite:degtyarev2011modelling,boukhanovsky1997thesis.

Модель Лонге---Хиггинса представляет взволнованную морскую поверхность в виде
суперпозиции элементарных гармонических волн случайных амплитуд $c_n$ и фаз
$\epsilon_n$, непрерывно распределенных на интервале $[0,2\pi]$, определяемую
формулой
\begin{equation}
    \label{eq:longuet-higgins}
    \zeta(x,y,t) = \sum\limits_n c_n \cos(u_n x + v_n y - \omega_n t + \epsilon_n)
\end{equation}
Волновые числа $(u_n,v_n)$ непрерывно распределены на плоскости $(u,v)$, т.е.
площадка $du \times dv$ содержит бесконечно большое количество волновых чисел.
Частота связана с волновыми числами дисперсионным соотношением
$\omega_n=\omega(u_n,v_n)$. Функция $\zeta(x,y,t)$ является трехмерным
эргодическим стационарным однородным гауссовым процессом, определяемым
соотношением
\begin{equation*}
    2E_\zeta(u,v)\, du\,  dv = \sum\limits_n c_n^2
\end{equation*}
где $E_\zeta(u,v)$ --- двумерная спектральная плотность энергии волн.
Коэффициенты $c_n$ определяются из энергетического спектра волнения $S(\omega)$
по формуле
\begin{equation*}
    c_n = \sqrt{ \textstyle\int\limits_{\omega_n}^{\omega_{n+1}} S(\omega) d\omega}.
\end{equation*}

*** Основные недостатки модели
Модель Лонге---Хиггинса отличается простотой численного алгоритма и
наглядностью, моделируя физически адекватную морскую поверхность. Однако, на
практике она обладает рядом недостатков cite:degtyarev2011modelling.

Модель рассчитана на представление стационарного гауссова поля и не подходит для
решения более общих задач: сумма большого числа гармоник со случайной амплитудой
и фазой будет иметь нормальное распределение в независимости от исходного
распределения фаз и амплитуд, что является следствием центральной предельной
теоремы. Исследования показывают (XXX), что особенностью океанских волн и волн
на поверхности жидкости ограниченной глубины является асимметричное
распределение волновых аппликат, которое не воспроизводится моделью.

С вычислительной точки зрения, недостатком модели является нелинейный рост
времени генерации поверхности с ростом временной протяженности реализации. При
увеличении временной протяженности необходимо увеличивается количество гармоник,
которые требуется просуммировать для исключения периодичности. Другими словами,
для исключения периодичности модель требует высокой степени дискретизации
частотно‑направленного спектра волн, а значит и большого количества частот. Это
приводит к нелинейному росту времени генерации поверхности, что делает модель
неэффективной для проведения длительных численных экспериментов.

Наконец, с инженерной точки зрения, модель обладает рядом особенностей, которые
не позволяют использовать ее в качестве фундамента для построения более
совершенных моделей.
- В численных экспериментах скорость сходимости
  выражения eqref:eq:longuet-higgins низка и имеет вероятностный характер,
  т.к. не обеспечена сходимость по фазам $\epsilon_n$.
- Обобщение модели для негауссовых и нелинейных процессов сопряжено с большой
  трудоемкостью вычислений cite:рожков1990вероятностные.
 
Таким образом, модель Лонге---Хиггинса применима для решения задачи генерации
взволнованной морской поверхности только в линейной постановке (в рамках теории
волн малой амплитуды), неэффективна для длительных экспериментов и имеет ряд
недостатков, не позволяющих использовать ее в качестве основы для построения
более совершенных моделей.

** Известные методы определения поля давлений
*** Общая постановка задачи
Задача определения поля давлений под взволнованной морской поверхностью
представляет собой обратную задачу гидродинамики для несжимаемой невязкой
жидкости. Система уравнений для нее в общем виде записывается как
cite:kochin1966theoretical
\begin{align}
    & \nabla^2\phi = 0,\nonumber\\
    & \phi_t+\frac{1}{2} |\vec{\upsilon}|^2 + g\zeta=-\frac{p}{\rho}, & \text{на }z=\zeta(x,y,t),\label{eq:problem}\\
    & D\zeta = \nabla \phi \cdot \vec{n}, & \text{на }z=\zeta(x,y,t),\nonumber
\end{align}
где $\phi$ --- потенциал скорости, $\zeta$ --- подъем (аппликата) взволнованной
поверхности, $p$ --- давление жидкости, $\rho$ --- плотность жидкости,
$\vec{\upsilon} = (\phi_x, \phi_y, \phi_z)$ --- вектор скорости, $g$ ---
ускорение свободного падения и $D$ --- субстанциональная производная (производная
Лагранжа). Первое уравнение является уравнением неразрывности (уравнение
Лапласа), второе --- законом сохранения импульса, которое иногда называют
динамическим граничным условием; третье уравнение --- кинематическое граничное
условие, которое сводится к равенству нормальной составляющей скорости жидкости
($\nabla \phi \cdot \vec{n}$) в каждой точке взволнованной поверхности
$\zeta(x,y,t)$ скорости перемещения этой поверхности ($D\zeta$).

Обратная задача гидродинамики заключается в решении этой системы уравнений
относительно $\phi$. В такой постановке уравнение Лапласа и кинематическое ГУ
используются для нахождения потенциала скорости, а динамическое ГУ --- для
вычисления давлений по известным производным потенциала. Таким образом, с
математической точки зрения обратная задача гидродинамики сводится к решению
уравнения Лапласа со смешанным ГУ --- задаче Робена для уравнения Лапласа.

*** Теория волн малых амплитуд
В cite:stab2012 дается решение обратной задачи гидродинамики для случая
идеальной несжимаемой жидкости в рамках теории волн малых амплитуд (в
предположении, что длина волны много больше ее высоты: $\lambda \gg h$). В этом
случае обратная задача линейна и сводится к уравнению Лапласа со смешанным
граничным условием, а уравнение движения используется только для нахождения
давлений по известным значениям производных потенциала скорости. Предположение о
малости амплитуд волн означает слабое изменение локального волнового числа во
времени и пространстве по сравнению с подъемом (аппликатой) взволнованной
поверхности. Это позволяет определить специальную формулу производной
$\zeta_z=k\zeta$, где $k$ --- волновое число. Формула является основой
предлагаемого решения. В двухмерном случае решение записывается явной формулой
\begin{align}
    \left.\frac{\partial\phi}{\partial x}\right|_{x,t}= &
        -\frac{1}{\sqrt{1+\alpha^{2}}}e^{-I(x)}
            \int\limits_{0}^x\frac{\partial\dot{\zeta}/\partial      
                z+\alpha\dot{\alpha}}{\sqrt{1+\alpha^{2}}}e^{I(x)}dx,\label{eq:old-sol-2d}\\
    I(x)= & \int\limits_{0}^x\frac{\partial\alpha/\partial z}{1+\alpha^{2}}dx,\nonumber
\end{align}
где $\alpha$ --- уклоны волн. В трехмерном случае решение записывается в виде
эллиптического дифференциального уравнения в частных производных
\begin{align*}
    & \frac{\partial^2 \phi}{\partial x^2} \left( 1 + \alpha_x^2 \right) +
    \frac{\partial^2 \phi}{\partial y^2} \left( 1 + \alpha_y^2 \right) +
    2\alpha_x\alpha_y \frac{\partial^2 \phi}{\partial x \partial y} + \\
    & \left(
        \frac{\partial \alpha_x}{\partial z} +
        \alpha_x \frac{\partial \alpha_x}{\partial x} +
        \alpha_y \frac{\partial \alpha_x}{\partial y}
    \right) \frac{\partial \phi}{\partial x} + \\
    & \left(
        \frac{\partial \alpha_y}{\partial z} +
        \alpha_x \frac{\partial \alpha_y}{\partial x} +
        \alpha_y \frac{\partial \alpha_y}{\partial y}
    \right) \frac{\partial \phi}{\partial y} + \\
    & \frac{\partial \dot{\zeta}}{\partial z} + 
    \alpha_x \dot{\alpha_x} + \alpha_y \dot{\alpha_y} = 0.
\end{align*}
Уравнение предполагается решать численно путем сведения к разностному.

Как будет показано в~\cref{sec:compare-formulae} формула~\eqref{eq:old-sol-2d}
расходится при попытке вычислить поле скоростей для волн больших амплитуд, а
значит не может быть использована вместе с моделью ветрового волнения,
генерирующей волны произвольных амплитуд.

*** Линеаризация граничного условия
:PROPERTIES:
:CUSTOM_ID: linear-boundary
:END:
Модель Лонге---Хиггинса позволяет вывести явную формулу для поля
скоростей путем линеаризации кинематического граничного условия. Формула для
потенциала скорости запишется как
\begin{equation*}
\phi(x,y,z,t) = \sum_n \frac{c_n g}{\omega_n} 
     e^{\sqrt{u_n^2+v_n^2} z}
     \sin(u_n x + v_n y - \omega_n t + \epsilon_n).
\end{equation*}
Формула дифференцируется для получения производных потенциала, а полученные
значения подставляются в динамическое граничное условие для вычисления давлений.

* Применение модели АРСС в задаче имитационного моделирования морского волнения
* Определение поля давлений под дискретно заданной взволнованной поверхностью
* Высокопроизводительный программный комплекс для моделирования морского волнения
* Заключение
* Благодарности
* Список литературы
* TODO Список условных обозначений
* Приложение
** TODO Вывод формулы модели Лонге---Хиггинса
