#+TITLE: Высокопроизводительная модель морского волнения для программ динамики морских объектов
#+AUTHOR: Иван Ганкевич
#+DATE: Санкт-Петербург, 2016
#+LANGUAGE: ru
#+LATEX_CLASS: gost
#+LATEX_CLASS_OPTIONS: [hidelinks,fontsize=14pt,paper=a4,pagesize,DIV=calc]
#+LATEX_HEADER_EXTRA: \input{preamble}
#+LATEX_HEADER_EXTRA: \organization{Санкт-Петербургский государственный университет}
#+LATEX_HEADER_EXTRA: \manuscript{на правах рукописи}
#+LATEX_HEADER_EXTRA: \degree{Диссертация на соискание ученой степени\\кандидата физико-математических наук}
#+LATEX_HEADER_EXTRA: \speciality{Специальность 05.13.18\\Математическое моделирование, численные методы и комплексы программ}
#+LATEX_HEADER_EXTRA: \supervisor{Научный руководитель\\д.т.н Дегтярев Александр Борисович}
#+LATEX_HEADER_EXTRA: \newcites{published}{Список опубликованных по теме диссертации работ}
#+OPTIONS: todo:nil title:nil ':t H:5
#+STARTUP: indent

* Config                                                           :noexport:
# default export options
#+begin_src emacs-lisp :exports none :results silent
;; For the full list of options see
;; http://orgmode.org/manual/Publishing-options.html
;; move table/figure captions to the bottom
(setq org-latex-caption-above nil)
;; preserve original image width
(setq org-latex-image-default-width nil)
#+end_src

** Plot distributions                                         :noexport:
#+begin_src gnuplot :exports none
set loadpath GPVAL_PWD."/gnuplot"
system "mkdir -p build"
cd "build"

load 'style.gnuplot'
#load 'style-paper.gnuplot'

set terminal svg fixed enhanced size 1920/5,900/3 font 'Old Standard, 12' dashed rounded
set key top center Left reverse width -10 maxrows 2
set xlabel 'z' offset 0,0.33
set ylabel 'f(z)' offset 2,0

set xrange [-3:3]
set ytics 0,0.1
set yrange [0:0.6]

skew_normal_1(z, skewness, kurtosis) = (24 + 4*z*(-3 + z**2)* \
      skewness + (3 - 6*z**2 + z**4)* kurtosis)/(24*(exp((z**2)/2)*sqrt(2*pi)))

#print skew_normal_1(1, 0.6, 1.0)
# regular gamma γ

set output 'skew-normal-1.svg'
plot \
skew_normal_1(x, 0, 0) with lines ls 1 title '𝛾_1=0, 𝛾_2=0', \
skew_normal_1(x, 0.52, 0) with lines ls 2 title '𝛾_1=0.52, 𝛾_2=0', \
skew_normal_1(x, 0, 0.7) with lines ls 3 title '𝛾_1=0, 𝛾_2=0.7', \
skew_normal_1(x, 0.52, 0.7) with lines ls 4 title '𝛾_1=0.52, 𝛾_2=0.7'
system "inkscape --without-gui --export-eps=skew-normal-1.eps skew-normal-1.svg

skew_normal_2(z, alpha) = \
  erfc( -((z*alpha)/sqrt(2)) ) / \
  (exp((z**2)/2)*sqrt(2*pi))

skewness(alpha) = \
  (sqrt(2) * (4 - pi) * (alpha**3)) \
  / \
  (sqrt(pi + (pi-2) * (alpha**2))**3)

kurtosis(alpha) = \
  (8*(-3 + pi)*(alpha**4))/ \
  ((pi + (-2 + pi)*(alpha**2))**2)

set terminal svg fixed enhanced size 1920/4,900/3 font 'Times, 12' dashed rounded
set key top left Left reverse maxcols 1 maxrows 4
set yrange [0:0.8]
set output 'skew-normal-2.svg'
alphas="0.00 0.87 2.25 4.90"
a(i) = word(alphas, i)
plot for [i=1:words(alphas)] \
skew_normal_2(x, a(i)) with lines ls i \
title 'α='.a(i).', 𝛾_1='.sprintf('%.2f',skewness(a(i))).', 𝛾_2='.sprintf('%.2f',kurtosis(a(i)))
system "inkscape --without-gui --export-eps=skew-normal-2.eps skew-normal-2.svg

exit
#+end_src

#+RESULTS:

** Plot velocities                                            :noexport:
#+begin_src gnuplot :exports none
set loadpath GPVAL_PWD."/gnuplot" GPVAL_PWD."/data/velocity"
system "mkdir -p build"
cd "build"

set terminal svg size 320, 200 font "Open Sans Regular, 12" linewidth 1 enhanced rounded dashed

load 'linestyle.gnuplot'

unset border
set border 3
set xtics nomirror out offset 0,0.5
set ytics nomirror out offset 0.5,0

set xrange [0:90]
set yrange [-2:4]
set xtics 0,30
set ytics -2,2,4
set xlabel 'x' offset 0,1
set ylabel 'u(x)' offset 1.75,0

set output 'high-amp-nocolor.svg'
plot 'high-amp'   title 'u_1(x)' ls 1 smooth csplines, \
     'high-amp-0' title 'u_2(x)' ls 2 smooth csplines
system "inkscape --without-gui --export-eps=high-amp-nocolor.eps high-amp-nocolor.svg

set output 'low-amp-nocolor.svg'
plot 'low-amp'   title 'u_1(x)' ls 1 smooth csplines, \
     'low-amp-0' title 'u_2(x)' ls 2 smooth csplines
system "inkscape --without-gui --export-eps=low-amp-nocolor.eps low-amp-nocolor.svg

exit
#+end_src

#+RESULTS:
* Введение
**** Актуальность темы.
Программы, моделирующие поведение судна на морских волнах, широко применяются
для расчета качки судна, оценки величины воздействия внешних сил на плавучую
платформу или другой морской объект, а также для оценки вероятности
опрокидывания судна при заданных погодных условиях; однако, большинство из них
используют линейную теорию для моделирования морского волнения
cite:shin2003nonlinear,van2007forensic,kat2001prediction,van2002development, в
рамках которой сложно воспроизвести определенные особенности ветроволнового
климата. Среди них можно выделить переход от нормальных погодных условий к
шторму и волнение, вызванное наложением множества систем ветровых волн и волн
зыби, распространяющихся в нескольких направлениях. Другой недостаток линейной
теории волн заключается в предположении, что высота волн много меньше их длины.
Это делает расчеты грубыми при моделировании качки судна в условиях
нерегулярного волнения, когда такое предположение несправедливо. Разработка
новых и более совершенных моделей и методов, используемых при расчете динамики
судна, может увеличить количество сценариев ее применения и, в частности,
способствовать исследованию поведения судна в экстремальных условиях.

**** Степень разработанности.
Модель авторегрессии скользящего среднего АРСС возникла как ответ на сложности,
с которыми на практике сталкиваются ученые, использующие в свой работе модели
морского волнения, разработанные в рамках линейной теории волн. Проблемы, с
которыми они сталкиваются при использовании модели Лонге---Хиггинса (которая
полностью основана на линейной теории волн) перечислены ниже.
1. /Периодичность/. В рамках линейной теории волны аппроксимируются суммой
   гармоник, а период реализации взволнованной поверхности зависит от их
   количества. Чем больше размер реализации, тем больше коэффициентов требуется
   для исключения периодичности, поэтому с увеличением размера реализации время
   ее генерации растет нелинейно. Это приводит к тому, что любая модель,
   основанная на линейной теории, неэффективна при генерации больших реализаций
   взволнованной поверхности, независимо от того, насколько оптимизирован
   исходный код программы.
2. /Линейность/. В рамках линейной теории волн дается математическое определение
   морским волнам в предположении малости их амплитуд по сравнению с длинами.
   Такие волны, в основном, характерны для открытого моря и океана, а волны в
   прибрежных районах и штормовые волны, для которых это предположение
   несправедливо, грубо описываются в рамках линейной теории.
3. /Вероятностная сходимость/. Фаза волны, значение которой обычно получается с
   помощью генератора псевдослучайных чисел (ГПСЧ), имеет равномерное
   распределение, что иногда приводит к медленной сходимости интегральных
   характеристик взволнованной поверхности (таких как распределение высот волн,
   их периодов, длин и т.п.). Скорость сходимости зависит от значений,
   полученных от ГПСЧ, поэтому быстрая сходимость не гарантируется.

Эти сложности стали отправной точкой в поиске модели, не основанной на линейной
теории волн, и в исследованиях процесса авторегрессии скользящего среднего
(АРСС) был найден необходимый математический аппарат.
1. Параметром процесса АРСС является автоковариационная функция (АКФ), которая
   может быть напрямую получена из энергетического или частотно-направленного
   спектра морского волнения (который, в свою очередь является входным
   параметром для модели Лонге---Хиггинса). Так что входные параметры одной
   модели могут быть легко преобразованы во входные параметры другой.
2. Процесс АРСС не имеет ограничение на амплитуду генерируемых волн: их крутизна
   может быть увеличена на столько, на сколько это позволяет АКФ реальных
   морских волн.
3. Период реализации равен периоду ГПСЧ, поэтому время генерации растет линейно
   с увеличением размера реализации.
4. Белый шум, который является единственным вероятностным членом формулы
   процесса АРСС, имеет нормальное распределение; так что скорость сходимость не
   носит вероятностный характер.

**** Цели и задачи.
Процесс АРСС стал основой модели ветрового волнения АРСС, однако он нуждался в
доработке перед тем, как его можно было бы использовать на практике.
1. Необходимо было исследовать, как различные формы АКФ влияют на выбор
   параметров процесса АРСС (количество коэффициентов процесса скользящего
   среднего и процесса авторегрессии).
2. Затем исследовать возможность генерации волн с произвольным профилем, а не
   только профиль синусоиды (учесть асимметричность распределения волновых
   аппликат взволнованной поверхности).
3. Затем вывести формулы для определения поля давлений под взволнованной
   поверхностью. Такие формулы обычно выводятся для конкретной модели путем
   подстановки формулы профиля волны в eqref:eq:problem, однако процесс АРСС не
   содержит в себе формулу профиля волны в явном виде, поэтому для него
   необходимо было получить решение для взволнованной поверхности общего вида
   (для которой не существует аналитического выражения) без линеаризации
   граничных условий (ГУ) и предположении о малости амплитуд волн.
4. Наконец, верифицировать интегральные характеристики взволнованной поверхности
   на соответствие реальным морским волнам.
5. Заключительный этап состоял в разработке комплекса программ, реализующего
   созданную модель и метод расчета давлений и позволяющего проводить расчеты
   как на многопроцессорной машине с общей памятью (SMP), так и на компьютерном
   кластере (MPP).

**** Научная новизна.
Модель АРСС в отличие от других моделей ветрового волнения не основана на
линейной теории волн, что позволяет
- генерировать волны произвольной амплитуды, регулируя крутизну посредством АКФ;
- генерировать волны произвольной формы, регулируя асимметричность распределения
  волновых аппликат посредством нелинейного безынерционного преобразования
  (НБП).
В то же время математический аппарат этой процесса АРСС хорошо изучен в
других научных областях, что позволяет его обобщить для моделирования развития
морского волнения в условиях шторма с учетом климатических спектров и данных
ассимиляции определенных районов мирового океана, что невозможно сделать с
помощью модели, основанной на линейной теории волн.

**** Теоретическая и практическая значимость работы.
Применение модели АРСС и формулы поля давлений, не использующей предположения
линейной теории волн, качественно повысит работу комплексов программ для расчета
воздействия океанских волн на морские объекты.

1. Поскольку формула для поля давлений выводится для дискретно заданной
   взволнованной поверхности и без каких-либо предположений об амплитудах волн,
   то она применима для любой взволнованной поверхности невязкой несжимаемой
   жидкости (в частности она применима для поверхности, генерируемой моделью
   Лонге---Хиггинса). Это позволяет использовать формулу поля давлений без
   привязки к модели АРСС.
2. С вычислительной точки зрения эта формула более эффективна, чем
   соответствующая формула для модели ЛХ, поскольку интегралы в формуле сводятся
   к преобразованиям Фурье, для которых существует семейство алгоритмов быстрого
   преобразования Фурье (БПФ), оптимизированных под разные архитектуры
   процессоров.
3. Поскольку формула явная, то обмена данными между параллельными процессами
   можно избежать, что позволяет достичь высокой масштабируемости на
   компьютерном кластере.
4. Наконец, сама модель АРСС более эффективна, чем модель ЛХ, ввиду отсутствия
   тригонометрических функций в ее формуле. Взволнованная поверхность
   вычисляется как сумма большого числа многочленов, для которых существует
   низкоуровневая ассемблерная инструкция (Fused Multiply-Add), показывающая
   высокую производительность на процессорах.

**** Методология и методы исследования.
Программная реализация модели АРСС и формула вычисления давлений создавалась
поэтапно: прототип, написанный высокойровневом инженерном языке
cite:mathematica10,octave2015, был преобразован в программу на языке более
низкого уровня (C++). Реализация одних и тех же формул и алгоритмов на языках
разного уровня (ввиду использования различных абстракций и языковых примитивов)
позволяет выявить и исправить ошибки, которые остались бы незамеченными в случае
одного языка. Генерируемая моделью АРСС взволнованная поверхность, а также все
входные параметры (АКФ, формула распределения волновых аппликат и т.п.) были
проверены с помощью встроенных в язык программирования графических средств для
визуального контроля корректности работы программы.

**** Положения, выносимые на защиту.
- Модель ветрового волнения, способная генерировать реализации взволнованной
  морской поверхности, имеющие большой период и состоящие из волн произвольной
  амплитуды;
- Формула для поля давлений, выведенная для этой модели без предположений
  линейной теории волн;
- Программная реализация созданной модели и формулы для вычислительных систем с
  общей (SMP) и с распределенной памятью (MPP).

**** Степень достоверности и апробация результатов.
Верификация модели АРСС проводится путем сравнения интегральных характеристик
(распределений волновых аппликат, высот и длин волн и т.п.) генерируемой
взволнованной поверхности с характеристиками реальных морских волн. Формула для
поля давлений выводится с помощью языка Mathematica, в котором полученные
выражения проверяются с помощью встроенных в язык графических средств.

Модель АРСС и формула для поля давлений были реализованы в Large Amplitude
Motion Programme (LAMP), программе для моделирования качки судна, и сопоставлены
с используемой ранее моделью ЛХ. Предварительные численные эксперименты показали
более высокую вычислительную эффективность модели АРСС.

* Постановка задачи
Задача состоит в исследовании возможности применении математического аппарата
процесса АРСС для моделирования морских волн и в выводе формулы для поля
давлений под генерируемой взволнованной морской поверхностью для случая
идеальной несжимаемой жидкости без предположений линейной теории волн.
- Для случая волн малых амплитуд полученная формула должна быть сопоставимо с
  соответствующей формулой линейной теории волн; для остальных случаев формула
  не должна расходиться.
- Интегральные характеристики генерируемой взволнованной поверхности должны
  совпадать с характеристиками реальных морских волн.
- Программная реализация модели АРСС и формулы вычисления давлений должна
  работать на системах с общей (SMP) и распределенной памятью (MPP).

**** Формула для поля давлений.
Задача определения поля давлений под взволнованной морской поверхностью
представляет собой обратную задачу гидродинамики для несжимаемой невязкой
жидкости. Система уравнений для нее в общем виде записывается как
cite:kochin1966theoretical
\begin{align}
    & \nabla^2\phi = 0,\nonumber\\
    & \phi_t+\frac{1}{2} |\vec{\upsilon}|^2 + g\zeta=-\frac{p}{\rho}, & \text{на }z=\zeta(x,y,t),\label{eq:problem}\\
    & D\zeta = \nabla \phi \cdot \vec{n}, & \text{на }z=\zeta(x,y,t),\nonumber
\end{align}
где $\phi$ --- потенциал скорости, $\zeta$ --- подъем (аппликата) взволнованной
поверхности, $p$ --- давление жидкости, $\rho$ --- плотность жидкости,
$\vec{\upsilon} = (\phi_x, \phi_y, \phi_z)$ --- вектор скорости, $g$ ---
ускорение свободного падения и $D$ --- субстанциональная производная
(производная Лагранжа). Первое уравнение является уравнением неразрывности
(уравнение Лапласа), второе --- законом сохранения импульса (которое иногда
называют динамическим граничным условием); третье уравнение --- кинематическое
граничное условие, которое сводится к равенству скорости перемещения этой
поверхности ($D\zeta$) нормальной составляющей скорости жидкости ($\nabla \phi
\cdot \vec{n}$).

Обратная задача гидродинамики заключается в решении этой системы уравнений
относительно $\phi$. В такой постановке динамическое ГУ становится явной
формулой для определения поля давлений по значениям производных потенциалов
скорости, полученных из оставшихся уравнений. Таким образом, с математической
точки зрения обратная задача гидродинамики сводится к решению уравнения Лапласа
со смешанным ГУ --- задаче Робена.

* Обзор литературы
** Анализ моделей морского волнения
Вычисление давлений возможно только при условии знания формы взволнованной
поверхности, которая задается либо дискретно в каждой точке пространственной
сетки, либо непрерывно с помощью аналитической формулы. Как будет показано в
разделе [[#linearisation]], знание такой формулы может упростить вычисление
давлений, фактически сведя задачу к генерации поля давлений, а не самой
взволнованной поверхности.

*** Модель Лонге---Хиггинса
Наиболее простой моделью, формула которой выводится в рамках линейной теории
волн, является модель Лонге---Хиггинса (ЛХ) cite:longuet1957statistical.
Подробный сравнительный анализ этой модели и модели АРСС проведен в работах
cite:degtyarev2011modelling,boukhanovsky1997thesis.

Модель ЛХ представляет взволнованную морскую поверхность в виде суперпозиции
элементарных гармонических волн случайных амплитуд $c_n$ и фаз $\epsilon_n$,
непрерывно распределенных на интервале $[0,2\pi]$. Подъем (координата $z$)
поверхности определяется формулой
#+name: eq:longuet-higgins
\begin{equation}
    \zeta(x,y,t) = \sum\limits_n c_n \cos(u_n x + v_n y - \omega_n t + \epsilon_n).
\end{equation}
Здесь волновые числа $(u_n,v_n)$ непрерывно распределены на плоскости $(u,v)$,
т.е. площадка $du \times dv$ содержит бесконечно большое количество волновых
чисел. Частота связана с волновыми числами дисперсионным соотношением
$\omega_n=\omega(u_n,v_n)$. Функция $\zeta(x,y,t)$ является трехмерным
эргодическим стационарным однородным гауссовым процессом, определяемым
соотношением
\begin{equation*}
    2E_\zeta(u,v)\, du\,  dv = \sum\limits_n c_n^2,
\end{equation*}
где $E_\zeta(u,v)$ --- двумерная спектральная плотность энергии волн.
Коэффициенты $c_n$ определяются из энергетического спектра волнения $S(\omega)$
по формуле
\begin{equation*}
    c_n = \sqrt{ \textstyle\int\limits_{\omega_n}^{\omega_{n+1}} S(\omega) d\omega}.
\end{equation*}

*** Основные недостатки модели Лонге---Хиггинса
Модель Лонге---Хиггинса отличается простотой численного алгоритма и
наглядностью, однако, на практике она обладает рядом недостатков.

1. Модель рассчитана на представление стационарного гауссова поля. Это является
   следствием центральной предельной теоремы (ЦПТ): сумма большого числа
   гармоник со случайными амплитудами и фазами имеет нормальное распределение в
   независимости от спектра, подаваемого на вход модели. Использование меньшего
   количества коэффициентов может решить проблему, но также уменьшит период
   реализации. Таким образом, использование модели ЛХ для генерации волн с
   негауссовым распределением аппликат (которое имеют реальные морские волны
   cite:huang1980experimental,рожков1996теория) не реализуемо на практике.
2. С вычислительной точки зрения, недостатком модели является нелинейный рост
   времени генерации поверхности с увеличением размера реализации. Чем больше
   размер реализации, тем больше коэффициентов (дискретных точек
   частотно-направленного спектра) требуется для исключения периодичности. Это
   делает модель неэффективной для проведения длительных численных
   экспериментов.
3. Наконец, с инженерной точки зрения, модель обладает рядом особенностей,
   которые не позволяют использовать ее в качестве фундамента для построения
   более совершенных моделей.
   - В программной реализации скорость сходимости выражения ([[eq:longuet-higgins]])
     может быть низкой, т.к. фазы $\epsilon_n$ имеют вероятностный характер.
   - Обобщение модели для негауссовых и нелинейных процессов сопряжено с большой
     трудоемкостью вычислений cite:рожков1990вероятностные.
 
Таким образом, модель Лонге---Хиггинса применима для решения задачи генерации
взволнованной морской поверхности только в линейной постановке (в рамках теории
волн малой амплитуды), неэффективна для длительных экспериментов и имеет ряд
недостатков, не позволяющих использовать ее в качестве основы для построения
более совершенных моделей.

*** Модель АРСС
В cite:spanos1982arma модель АРСС используется для генерации временного ряда,
спектр которого совпадает с аппроксимацией Пирсона---Московица для спектров
морского волнения. Авторы проводят эксперименты для одномерных моделей АР, СС и
АРСС. Они отмечают превосходное совпадение полученного и исходного спектров и
более высокую вычислительную эффективность модели АРСС по сравнению с
моделями, основанными на суммировании большого числа гармоник со случайными
фазами. Также отмечается, что для того чтобы спектр полученного временного ряда
совпадал с заданным, модели СС требуется меньшее количество коэффициентов, чем
модели АР. В cite:spanos1996efficient автор обобщает формулы для нахождения
коэффициентов модели АРСС для случая нескольких (векторов) переменных.

Отличие данной работы от вышеперечисленных отличается в исследовании трехмерной
модели АРСС (два пространственных и одно временное измерение), что во многом
является другой задачей.
1. Система уравнений Юла---Уокера, используемая для определения коэффициентов
   АР, имеет более сложную блочно-блочную структуру.
2. Оптимальный (для совпадения заданного и исходного спектров) порядок модели
   определяется вручную.
3. Вместо аппроксимации ПМ в качестве входа модели используются аналитические
   выражения для АКФ стоячих и прогрессивных волн.
4. Трехмерная взволнованная поверхность должна быть сопоставима с реальной
   морской поверхностью не только по спектральным характеристикам, но и по форме
   волновых профилей, поэтому верификация модели производится и для
   распределений различных параметров генерируемых волн (длин, высот, периодов и
   др.).
Многомерность исследуемой модели не только усложняет задачу, но и позволяет
провести визуальную проверку генерируемой взволнованной поверхности. Именно
возможность визуализировать результат работы программы позволила удостовериться,
что генерируемая поверхность действительно похожа на реальное морское волнение,
а не является абстрактным многомерным случайным процессом, совпадающим с
реальным лишь статистически.

** Известные формулы определения поля давлений
*** Теория волн малых амплитуд
В cite:stab2012,детярев1998моделирование,degtyarev1997analysis дается решение
обратной задачи гидродинамики для случая идеальной несжимаемой жидкости в рамках
теории волн малых амплитуд (в предположении, что длина волны много больше ее
высоты: $\lambda \gg h$). В этом случае обратная задача линейна и сводится к
уравнению Лапласа со смешанным граничным условием, а уравнение движения
используется только для нахождения давлений по известным значениям производных
потенциала скорости. Предположение о малости амплитуд волн означает слабое
изменение локального волнового числа во времени и пространстве по сравнению с
подъемом (аппликатой) взволнованной поверхности. Это позволяет вычислить
производную подъема поверхности по $z$ как $\zeta_z=k\zeta$, где $k$ ---
волновое число. В двухмерном случае решение записывается явной формулой
\begin{align}
    \left.\frac{\partial\phi}{\partial x}\right|_{x,t}= &
        -\frac{1}{\sqrt{1+\alpha^{2}}}e^{-I(x)}
            \int\limits_{0}^x\frac{\partial\dot{\zeta}/\partial      
                z+\alpha\dot{\alpha}}{\sqrt{1+\alpha^{2}}}e^{I(x)}dx,\label{eq:old-sol-2d}\\
    I(x)= & \int\limits_{0}^x\frac{\partial\alpha/\partial z}{1+\alpha^{2}}dx,\nonumber
\end{align}
где $\alpha$ --- уклоны волн. В трехмерном случае решение записывается в виде
эллиптического дифференциального уравнения в частных производных
\begin{align*}
    & \frac{\partial^2 \phi}{\partial x^2} \left( 1 + \alpha_x^2 \right) +
    \frac{\partial^2 \phi}{\partial y^2} \left( 1 + \alpha_y^2 \right) +
    2\alpha_x\alpha_y \frac{\partial^2 \phi}{\partial x \partial y} + \\
    & \left(
        \frac{\partial \alpha_x}{\partial z} +
        \alpha_x \frac{\partial \alpha_x}{\partial x} +
        \alpha_y \frac{\partial \alpha_x}{\partial y}
    \right) \frac{\partial \phi}{\partial x} + \\
    & \left(
        \frac{\partial \alpha_y}{\partial z} +
        \alpha_x \frac{\partial \alpha_y}{\partial x} +
        \alpha_y \frac{\partial \alpha_y}{\partial y}
    \right) \frac{\partial \phi}{\partial y} + \\
    & \frac{\partial \dot{\zeta}}{\partial z} + 
    \alpha_x \dot{\alpha_x} + \alpha_y \dot{\alpha_y} = 0.
\end{align*}
Уравнение предполагается решать численно путем сведения к разностному.

Как будет показано в [[#sec:compare-formulae]] формула eqref:eq:old-sol-2d
расходится при попытке вычислить поле скоростей для волн больших амплитуд, а
значит не может быть использована вместе с моделью ветрового волнения,
генерирующей волны произвольных амплитуд.

*** Линеаризация граничного условия
:PROPERTIES:
:CUSTOM_ID: linearisation
:END:
Модель Лонге---Хиггинса позволяет вывести явную формулу для поля
скоростей путем линеаризации кинематического граничного условия. Формула для
потенциала скорости запишется как
\begin{equation*}
\phi(x,y,z,t) = \sum_n \frac{c_n g}{\omega_n} 
     e^{\sqrt{u_n^2+v_n^2} z}
     \sin(u_n x + v_n y - \omega_n t + \epsilon_n).
\end{equation*}
Формула дифференцируется для получения производных потенциала, а полученные
значения подставляются в динамическое граничное условие для вычисления давлений.

* Модель АРСС в задаче имитационного моделирования морского волнения
** Основные формулы трехмерного процесса AРСС
*** Три возможных процесса
Модель АРСС для морского волнения определяет взволнованную морскую поверхность
как трехмерный (два пространственных и одно временное измерение) процесс
авторегрессии скользящего среднего: каждая точка взволнованной поверхности
представляется в виде взвешенной суммы предыдущих по времени и пространству
точек и взвешенной суммы предыдущих по времени и пространству нормально
распределенных случайных импульсов. Основным уравнением для трехмерного процесса
АРСС является
\begin{equation}
    \zeta_{\vec i}
    =
    \sum\limits_{\vec j = \vec 0}^{\vec N}
    \Phi_{\vec j} \zeta_{\vec i - \vec j}
    +
    \sum\limits_{\vec j = \vec 0}^{\vec M}
    \Theta_{\vec j} \epsilon_{\vec i - \vec j}
    ,
    \label{eq:arma-process}
\end{equation}
где $\zeta$ --- подъем (аппликата) взволнованной поверхности, $\Phi$ ---
коэффициенты процесса АР, $\Theta$ --- коэффициенты процесса СС, $\epsilon$ ---
белый шум, имеющий Гауссово распределение, $\vec N$ --- порядок процесса АР,
$\vec M$ --- порядок процесса СС, причем $\Phi_{\vec{0}}\equiv0$,
$\Theta_{\vec{0}}\equiv0$. Здесь стрелки обозначают многокомпонентные индексы,
содержащие отдельную компоненту для каждого измерения. В общем случае в качестве
компонент могут выступать любые скалярные величины (температура, соленость,
концентрация какого-либо раствора в воде и т.п.). Параметрами уравнения служат
коэффициенты и порядки процессов АР и СС.

**** Процесс авторегрессии (АР).
Процесс АР --- это процесс АРСС только лишь с одним случайным импульсом вместо их
взвешенной суммы:
\begin{equation}
    \zeta_{\vec i}
    =
    \sum\limits_{\vec j = \vec 0}^{\vec N}
    \Phi_{\vec j} \zeta_{\vec i - \vec j}
    +
    \epsilon_{i,j,k}
    .
    \label{eq:ar-process}
\end{equation}
Коэффициенты авторегрессии $\Phi$ определяются из многомерных уравнений
Юла---Уокера, получаемых после домножения на $\zeta_{\vec{i}-\vec{k}}$ обеих
частей уравнения и взятия математического ожидания. В общем виде уравнения
Юла---Уокера записываются как
\begin{equation}
    \label{eq:yule-walker}
    \gamma_{\vec k}
    =
    \sum\limits_{\vec j = \vec 0}^{\vec N}
    \Phi_{\vec j}
    \text{ }\gamma_{\vec{k}-\vec{j}}
    +
    \Var{\epsilon} \delta_{\vec{k}},
    \qquad
    \delta_{\vec{k}} =
    \begin{cases}
        1, \quad \text{if } \vec{k}=0 \\
        0, \quad \text{if } \vec{k}\neq0,
    \end{cases}
\end{equation}
где $\gamma$ --- АКФ процесса $\zeta$, $\Var{\epsilon}$ --- дисперсия
белого шума. Матричная форма трехмерной системы уравнений Юла---Уокера,
используемой в данной работе, имеет следующий вид.
\begin{equation*}
    \Gamma
    \left[
        \begin{array}{l}
            \Phi_{\vec 0}\\
            \Phi_{0,0,1}\\
            \vdotswithin{\Phi_{\vec 0}}\\
            \Phi_{\vec N}
        \end{array}
    \right]
    =
    \left[
        \begin{array}{l}
            \gamma_{0,0,0}-\Var{\epsilon}\\
            \gamma_{0,0,1}\\
            \vdotswithin{\gamma_{\vec 0}}\\
            \gamma_{\vec N}
        \end{array}
    \right],
    \qquad
    \Gamma=
    \left[
        \begin{array}{llll}
            \Gamma_0 & \Gamma_1 & \cdots & \Gamma_{N_1} \\
            \Gamma_1 & \Gamma_0 & \ddots & \vdotswithin{\Gamma_0} \\
            \vdotswithin{\Gamma_0} & \ddots & \ddots & \Gamma_1 \\
            \Gamma_{N_1} & \cdots & \Gamma_1 & \Gamma_0
        \end{array}
    \right],
\end{equation*}
где $\vec N = \left( N_1, N_2, N_3 \right)$ и
\begin{equation*}
    \Gamma_i =
    \left[
    \begin{array}{llll}
        \Gamma^0_i & \Gamma^1_i & \cdots & \Gamma^{N_2}_i \\
        \Gamma^1_i & \Gamma^0_i & \ddots & \vdotswithin{\Gamma^0_i} \\
        \vdotswithin{\Gamma^0_i} & \ddots & \ddots & \Gamma^1_i \\
        \Gamma^{N_2}_i & \cdots & \Gamma^1_i & \Gamma^0_i
    \end{array}
    \right]
    \qquad
    \Gamma_i^j=
    \left[
    \begin{array}{llll}
        \gamma_{i,j,0} & \gamma_{i,j,1} & \cdots & \gamma_{i,j,N_3} \\
        \gamma_{i,j,1} & \gamma_{i,j,0} & \ddots &x \vdotswithin{\gamma_{i,j,0}} \\
        \vdotswithin{\gamma_{i,j,0}} & \ddots & \ddots & \gamma_{i,j,1} \\
        \gamma_{i,j,N_3} & \cdots & \gamma_{i,j,1} & \gamma_{i,j,0}
    \end{array}
    \right],
\end{equation*}
Поскольку по определению $\Phi_{\vec 0}\equiv0$, то первую строку и столбец
матрицы $\Gamma$ можно отбросить. Матрица $\Gamma$, как и оставшаяся от нее
матрица, будут блочно-теплицевы, положительно определены и симметричны, поэтому
систему уравнений Юла---Уокера можно эффективно решить методом Холецкого,
специально предназначенного для таких матриц.

После нахождения решения системы уравнений дисперсия белого шума определяется из
уравнения eqref:eq:yule-walker при $\vec k = \vec 0$ как
\begin{equation*}
    \Var{\epsilon} =
    \Var{\zeta}
    -
    \sum\limits_{\vec j = \vec 0}^{\vec N}
    \Phi_{\vec j}
    \text{ }\gamma_{\vec{j}}.
\end{equation*}

**** Процесс скользящего среднего (СС).
Процесс СС --- это процесс АРСС, в котором $\Phi\equiv0$:
\begin{equation}
    \zeta_{\vec i}
    =
    \sum\limits_{\vec j = \vec 0}^{\vec M}
    \Theta_{\vec j} \epsilon_{\vec i - \vec j}
    .
    \label{eq:ma-process}
\end{equation}
Коэффициенты СС $\Theta$ определяются неявно из системы нелинейных уравнений
\begin{equation*}
  \gamma_{\vec i} =
  \left[
    \displaystyle
    \sum\limits_{\vec j = \vec i}^{\vec M}
    \Theta_{\vec j}\Theta_{\vec j - \vec i}
  \right]
  \Var{\epsilon}.
\end{equation*}
Система решается численно с помощью метода простой итерации по формуле
\begin{equation*}
  \Theta_{\vec i} =
    -\frac{\gamma_{\vec 0}}{\Var{\epsilon}}
    +
    \sum\limits_{\vec j = \vec i}^{\vec M}
    \Theta_{\vec j} \Theta_{\vec j - \vec i}.
\end{equation*}
Здесь новые значения коэффициентов $\Theta$ вычисляются, начиная с последнего:
от $\vec{i}=\vec{M}$ до $\vec{i}=\vec{0}$. Дисперсия белого шума вычисляется из
\begin{equation*}
    \Var{\epsilon} = \frac{\gamma_{\vec 0}}{
    1
    +
    \sum\limits_{\vec j = \vec 0}^{\vec M}
    \Theta_{\vec j}^2
    }.
\end{equation*}
Авторы cite:box1976time предлагают использовать метод Ньютона---Рафсона для
решения этого уравнения с большей точностью, однако, этот метод не подходит для
трех измерений. Использование более медленного метода не оказывает большого
эффекта на общую производительность программы, потому что количество
коэффициентов мало, и большую часть времени программа тратит на генерацию
взволнованной поверхности.

**** TODO Стационарность и обратимость процессов АР и СС
**** Смешанный процесс авторегрессии скользящего среднего (АРСС).
:PROPERTIES:
:CUSTOM_ID: sec:how-to-mix-ARMA
:END:
В общем и целом, процесс АРСС получается путем подстановки сгенерированной
процессом СС взволнованной поверхности в качестве случайного импульса процесса
АР, однако, для того чтобы АКФ результирующего процесса соответствовала
заданной, необходимо предварительно скорректировать значения коэффициентов АР.
Существует несколько способов "смешивания" процессов АР и СС.
- Подход, предложенный авторами cite:box1976time, который включается в себя
  разделение АКФ на часть для процесса АР и часть для процесса СС по каждому из
  измерений, не подходит в данной ситуации, поскольку в трех измерениях
  невозможно таким образом разделить АКФ: всегда останутся части, которые не
  будут учтены ни в процессе АР, ни в процессе СС.
- Альтернативный подход состоит в использование одной и той же (неразделенной)
  АКФ для обоих процессов разных порядков, однако, тогда характеристики
  реализации (математической ожидание, дисперсия и др.) будут смещены: они
  станут характеристика двух наложенных друг на друга процессов.
Для первого подхода авторами cite:box1976time предложена формула корректировки
коэффициентов процесса АР, для второго же подхода такой формулы нет. Таким
образом, лучшим решением на данный момент является использование процессов АР и
СС по отдельности.

*** Критерии выбора процесса для моделирования разных профилей волн
Одной из проблем в применении модели АРСС для генерации взволнованной морской
поверхности является то, что для разных профилей волн /необходимо/ использовать
разные процессы: стоячие волны моделируются только процессом АР, а прогрессивные
волны --- только процессом СС. Это утверждение пришло из практики: если
попытаться использовать процессы наоборот, результирующая реализация либо
расходится, либо не представляет собой реальные морские волны (такое происходит
в случае необратимого процесса СС, который всегда стационарен). Таким образом,
процесс АР может быть использован только для моделирования стоячих волн, а
процесс СС --- для прогрессивных волн.

Другой проблемой является невозможность автоматического определения оптимального
количества коэффициентов для трехмерных процессов АР и СС. Для одномерных
процессов существуют итеративные методы cite:box1976time, однако они расходятся
в трехмерном случае.

Последней проблемой, которая описана в разделе [[#sec:how-to-mix-ARMA]], является
невозможность "смешать" процесс АР и СС в трех измерениях.

Практика показывает, что некоторые утверждения авторов cite:box1976time не
выполняются для трехмерной модели АРСС. Например, авторы утверждают, что АКФ
процесса СС обрывается на отсчете $q$, а АКФ процесса АР затухает на
бесконечности, однако, на практике при использовании слабо затухающей и
обрывающейся на отсчете $q$ АКФ для трехмерного процесса СС получается
необратимый процесс СС и реализация, не соответствующая реальными морским
волнам, в то время как при использовании той же самой АКФ для трехмерного
процесса АР получается стационарный обратимый процесс и адекватная реализация.
Также, авторы утверждают, что первые $q$ точек АКФ смешанного процесса
необходимо выделить процессу СС (поскольку он обычно используется для описания
пиков АКФ) и отдать остальные точки процессу АР, однако, на практике в случае
АКФ прогрессивной волны процесс АР стационарен только для начального временного
среза АКФ, а остальные точки отдаются процессу СС.

Суммируя вышесказанное, наиболее разработанным сценарием применения модели АРСС
для генерации взволнованной морской поверхности является использование процесса
АР для стоячих волн и процесса СС для прогрессивных волн. Смешанный процесс АРСС
может сделать модель более точной при условии наличия соответствующих формул
пересчета коэффициентов, что является целью дальнейших исследований.

** Моделирование нелинейности морских волн
Модель АРСС позволяет учесть асимметричность распределения волновых аппликат,
т.е. генерировать морские волны, закон распределения аппликат которых имеет
ненулевой эксцесс и асимметрию. Такой закон распределения характерен для реальных
морских волн cite:longuet1963nonlinear.

Асимметричность волн моделируется с помощью нелинейного безынерционного
преобразования (НБП) случайного процесса, однако, любое нелинейное
преобразование случайного процесса приводит к преобразованию его АКФ. Для того
чтобы подавить этот эффект, необходимо предварительно преобразовать АКФ, как
показано в cite:boukhanovsky1997thesis.

**** Преобразование взволнованной поверхности.
Формула $z=f(y)$ преобразования взволнованной поверхности к необходимому
одномерному закону распределения $F(z)$ получается путем решения нелинейного
трансцендентного уравнения $F(z) = \Phi(y)$, где $\Phi(y)$ --- функция
одномерного нормального закона распределения. Поскольку функция распределения
аппликат морских волн часто задается некоторой аппроксимацией, основанной на
натурных данных, то это уравнение целесообразно решать численно в каждой точке
$y_k|_{k=0}^N$ сетки сгенерированной поверхности относительно $z_k$. Тогда
уравнение запишется в виде
\begin{equation}
    \label{eq:distribution-transformation}
    F(z_k)
    =
    \frac{1}{\sqrt{2\pi}}
    \int\limits_0^{y_k} \exp\left[ -\frac{t^2}{2} \right] dt
    .
\end{equation}
Поскольку функции распределения монотонны, для решения этого уравнения
используется простейший численный метод половинного деления (метод бисекции).

**** Предварительное преобразование АКФ.
Для преобразования АКФ $\gamma_z$ процесса ее необходимо разложить в ряд по
полиномам Эрмита (ряд Грама---Шарлье)
\begin{equation*}
    \gamma_z \left( \vec u \right)
    =
    \sum\limits_{m=0}^{\infty}
    C_m^2 \frac{\gamma_y^m \left( \vec u \right)}{m!},
\end{equation*}
где
\begin{equation*}
    C_m = \frac{1}{\sqrt{2\pi}}
  \int\limits_{0}^\infty
    f(y) H_m(y) \exp\left[ -\frac{y^2}{2} \right],
\end{equation*}
$H_m$ --- полином Эрмита, а $f(y)$ --- решение уравнения
eqref:eq:distribution-transformation. Воспользовавшись полиномиальной
аппроксимацией $f(y) \approx \sum\limits_i d_i y^i$ и аналитическими выражениями
для полнимов Эрмита, формулу определения коэффициентов можно упростить,
используя следующее равенство:
\begin{equation*}
    \frac{1}{\sqrt{2\pi}}
    \int\limits_\infty^\infty
    y^k \exp\left[ -\frac{y^2}{2} \right]
    =
    \begin{cases}
        (k-1)!! & \text{для четных }k,\\
        0       & \text{для нечетных }k.
    \end{cases}
\end{equation*}
Оптимальное количество коэффициентов $C_m$ определяется путем вычисления их
последовательно и критерий прекращения счета определяется совпадением дисперсий
обоих полей с требуемой точностью $\epsilon$:
\begin{equation*}
    \left| \Var{z} - \sum\limits_{k=0}^m
    \frac{C_k^2}{k!} \right| \leq \epsilon.
\end{equation*}

В cite:boukhanovsky1997thesis автор предлагает использовать полиномиальную
аппроксимацию для $f(y)$ также для преобразования поверхности, однако на
практике в реализации взволнованной поверхности часто находятся точки,
выпадающие за промежуток на котором построена аппроксимация, что приводит к
резкому уменьшению ее точности. В этих точках уравнение
eqref:eq:distribution-transformation эффективнее решать методом бисекции.
Использование полиномиальной аппроксимации в формулах для коэффициентов ряда
Грама---Шарлье не приводит к аналогичным ошибкам.

** Определение поля давлений под дискретно заданной взволнованной поверхностью
Аналитические решения граничных задач для классических уравнений часто
используются для исследования различных свойств уравнений, и для таких
исследований запись формулы общего решения неудобна ввиду своей сложности и
наличия интегралов от неизвестных функций. Одним из методов нахождения
аналитических решений ДУЧП является метод Фурье. Основой метода служит
преобразование Фурье, применение которого к любому ДУЧП позволяет свести его к
алгебраическому, а его решение записывается как обратное преобразование Фурье от
некоторой функции (которая может содержать преобразования Фурье от других
функций). Поскольку эти преобразования не всегда можно записать аналитически, то
вместо этого ищутся частные решения задачи и анализируется их поведение в
различных областях. В то же время, вычисление дискретных преобразований Фурье на
компьютере возможно для любой дискретно заданной функции и эффективно при
использовании алгоритмов БПФ. Эти алгоритмы используют симметрию комплексных
экспонент для понижения асимптотической сложности с $\mathcal{O}(n^2)$ до
$\mathcal{O}(n\log_{2}n)$. Таким образом, даже если общее решение содержит
преобразования Фурье от неизвестных функций, они все равно могут быть взяты
численно, а использование алгоритмов БПФ делает этот подход эффективным.

Альтернативным подходом является сведение их к разностным уравнениям, решаемым с
помощью построения различных численных схем. При этом решение получается
приближенным, а асимптотическая сложность соответствующих алгоритмов сопоставима
со сложностью алгоритма БПФ. Например, стационарное эллиптическое уравнение в
частных производных преобразуется в неявную разностную схему, решаемую
итерационным методом, на каждом шаге которого ищется решение трехдиагональной
или пятидиагональной СЛАУ методом прогонки (алгоритм Томаса). Асимптотическая
сложность алгоритма составляет $\mathcal{O}({n}{m})$, где $n$ --- количество
точек на сетке взволнованной поверхности, $m$ --- число итераций. Несмотря на
широкое распространение, итеративные алгоритмы неэффективно отображаются на
архитектуру параллельных машин; в частности, отображение на сопроцессоры может
включать в себя копирование данных на сопроцессор и обратно на каждой итерации,
что отрицательно сказывается на их производительности. В то же время, наличие
большого количества преобразований Фурье в решении является скорее
преимуществом, чем недостатком. Во-первых, решения, полученные с помощью метода
Фурье, явные, а значит хорошо масштабируются на большое количество параллельно
работающих вычислительных ядер с использованием простейших приемов параллельного
программирования. Во-вторых, для алгоритмов БПФ существуют готовые
оптимизированные реализация для различных архитектур процессоров и сопроцессоров
(GPU, MIC). Эти преимущества обусловили выбор метода Фурье в качестве рабочего
для получения явного аналитического решения задачи определения давлений под
взволнованной морской поверхностью.

*** Двухмерное поле скоростей
:PROPERTIES:
:CUSTOM_ID: sec:pressure-2d
:END:
**** Формула для жидкости бесконечной глубины.
Задача Робена для уравнения Лапласа в двух измерениях записывается как
\begin{align}
    \label{eq:problem-2d}
    & \phi_{xx}+\phi_{zz}=0,\\
    & \zeta_t + \zeta_x\phi_x = \frac{\zeta_x}{\sqrt{1 + \zeta_x^2}} \phi_x - \phi_z, & \text{на }z=\zeta(x,t).\nonumber
\end{align}
Для ее решения воспользуемся методом Фурье. Возьмем преобразование Фурье от
обоих частей уравнений Лапласа и получим
\begin{equation*}
    -4 \pi^2 \left( u^2 + v^2 \right)
    \FourierY{\phi(x,z)}{u,v} = 0,
\end{equation*}
откуда имеем $v = \pm i u$. Здесь и далее будет использоваться следующая
симметричная форма преобразования Фурье:
\begin{equation*}
    \FourierY{f(x,y)}{u,v} =
    \iint\limits_{-\infty}^{\phantom{--}\infty}
    f(x,y)
    e^{-2\pi i (x u + y v)}
    dx dy.
\end{equation*}
Решение уравнения будем искать в виде обратного преобразования Фурье
$\phi(x,z)=\InverseFourierY{E(u,v)}{x,z}$. Подставляя[fn::Выражение $v={-i}{u}$
не подходит в данной задаче, поскольку потенциал скорости должен стремиться к
нулю с увеличением глубины до бесконечности.} $v={i}{u}$ в формулу, решение
перепишется как
\begin{equation}
    \label{eq:guessed-sol-2d}
    \phi(x,z) = \InverseFourierY{e^{2\pi u z}E(u)}{x}.
\end{equation}
Для того чтобы подстановка $z=\zeta(x,t)$ не помешала использованию
преобразований Фурье в решении, перепишем eqref:eq:guessed-sol-2d в виде
свертки:
\begin{equation*}
    \phi(x,z)
    =
    \Fun{z}
    \ast
    \InverseFourierY{E(u)}{x},
\end{equation*}
где $\Fun{z}$ --- некоторая функция, вид которой будет определен в
[[#sec:compute-delta]] и для которой выполняется соотношение
$\FourierY{\Fun{z}}{u}=e^{2\pi{u}{z}}$. Подставляя выражение для $\phi$ в
граничное условие, получим
\begin{equation*}
    \zeta_t
    =
    \left( i f(x) - 1 \right)
    \left[
        \Fun{z}
        \ast
        \InverseFourierY{2\pi u E(u)}{x}
    \right],
\end{equation*}
где $f(x) = {\zeta_x}/{\sqrt{1 + \zeta_x^2}} - \zeta_x$. Применяя преобразование
Фурье к обеим частям, получаем выражение для коэффициентов $E$:
\begin{equation*}
    E(u) =
    \frac{1}{2\pi u}
    \frac{
    \FourierY{\zeta_t / \left(i f(x) - 1\right)}{u}
    }{
    \FourierY{\Fun{z}}{u}
    }
\end{equation*}
Выполняя подстановку $z=\zeta(x,t)$ и подставляя полученное выражение в
eqref:eq:guessed-sol-2d, получаем окончательное выражение для $\phi(x,z)$:
\begin{equation}
    \label{eq:solution-2d}
    \boxed{
        \phi(x,z)
        =
        \InverseFourierY{
            \frac{e^{2\pi u z}}{2\pi u}
            \frac{
            \FourierY{ \zeta_t / \left(i f(x) - 1\right) }{u}
            }{
            \FourierY{ \Fun{\zeta(x,t)} }{u}
            }
        }{x}.
    }
\end{equation}

Множитель $e^{2\pi u z}/(2\pi u)$ делает график функции от которой берется
обратное преобразования Фурье несимметричным относительно оси $OY$. Это
затрудняет применение БПФ, поскольку оно требует периодичную функцию, которая на
концах промежутка принимает нулевое значение. Использование численного
интегрирования вместо БПФ не позволит получить преимущество над решением всей
системы уравнений с помощью разностных схем. Эту проблему можно обойти,
используя формулу eqref:eq:solution-2d-full для жидкости конечной глубины с
заведомо большим значением глубины водоема $h$. Вывод формулы дан в следующем
разделе.

**** Формула для жидкости конечной глубины.
На дне водоема вертикальная составляющая скорости перемещения жидкости должна
равняться нулю, т.е. $\phi_z=0$ на $z=-h$, где $h$ --- глубина водоема. В этом
случае пренебречь равенством $v = -i u$, полученным из уравнения Лапласа,
нельзя, и решение ищется в виде
\begin{equation}
    \phi(x,z)
    =
    \InverseFourierY{
        \left( C_1 e^{2\pi u z} + C_2 e^{-2\pi u z} \right)
        E(u)
    }{x}.
    \label{eq:guessed-sol-2d-full}
\end{equation}
Подставляя $\phi$ в условие на дне водоема, получим
\begin{equation*}
    C_1 e^{-2\pi u h} - C_2 e^{2\pi u h} = 0,
\end{equation*}
откуда имеем $C_1=\frac{1}{2}C{e}^{2\pi{u}{h}}$ и
$C_2=-\frac{1}{2}C{e}^{-2\pi{u}{h}}$. Константа $C$ здесь произвольна, поскольку
при подстановке станет частью неизвестных коэффициентов $E(u)$. Подставляя
полученные выражения для $C_1$ и $C_2$ в eqref:eq:guessed-sol-2d-full, получаем
выражение
\begin{equation*}
    \phi(x,z) = \InverseFourierY{ \Sinh{2\pi u (z+h)} E(u) }{x}.
\end{equation*}
Подставляя $\phi$ в граничное условие на свободной поверхности, получаем
\begin{equation*}
    \zeta_t = f(x) \InverseFourierY{ 2\pi i u \Sinh{2\pi u (z+h)} E(u) }{x}
            - \InverseFourierY{ 2\pi u \SinhX{2\pi u (z+h)} E(u) }{x}.
\end{equation*}
Здесь $\sinh$ и $\cosh$ дают схожие результаты вблизи свободной поверхности, и,
поскольку эта область является наиболее интересной с точки зрения практического
применения, положим $\Sinh{2\pi{u}(z+h)}\approx\SinhX{2\pi{u}(z+h)}$. Выполняя
аналогичные предыдущему разделу операции, получаем окончательное выражение для
$\phi(x,z)$:
\begin{equation}
\boxed{
    \phi(x,z,t)
    =
  \InverseFourierY{
        \frac{\Sinh{2\pi u (z+h)}}{2\pi u}
        \frac{
            \FourierY{ \zeta_t / \left(i f(x) - 1\right) }{u}
        }{
            \FourierY{ \FunSecond{\zeta(x,t)} }{u}
        }
    }{x},
}
    \label{eq:solution-2d-full}
\end{equation}
где $\FunSecond{z}$ --- некоторая функция, вид которой будет определен в
[[#sec:compute-delta]] и для которой выполняется соотношение
$\FourierY{\FunSecond{z}}{u}=\Sinh{2\pi{u}{z}}$.

**** Сведение к формулам линейной теории волн.
Справедливость полученных формул проверим, подставив в качестве $\zeta(x,t)$
известные аналитические выражения для плоских волн. Символьные вычисления
преобразований Фурье в этом разделе производились с помощью пакета Mathematica
cite:mathematica10. В линейной теории широко используется предположение о
малости амплитуд волн, что позволяет упростить исходную систему уравнений
eqref:eq:problem-2d до
\begin{align*}
    & \phi_{xx}+\phi_{zz}=0,\\
    & \zeta_t = -\phi_z & \text{на }z=\zeta(x,t),
\end{align*}
решение которой запишется как
\begin{equation*}
    \phi(x,z,t)
    =
    -\InverseFourierY{
        \frac{e^{2\pi u z}}{2\pi u}
        \FourierY{\zeta_t}{u}
    }{x}
    .
\end{equation*}
Профиль прогрессивной волны описывается формулой $\zeta(x,t)=A\cos(2\pi(kx-t))$.
Подстановка этого выражения в eqref:eq:solution-2d дает равенство
$\phi(x,z,t)=-\frac{A}{k}\sin(2\pi(kx-t))\Sinh{2\pi{k}{z}}$. Чтобы свести его к
формуле линейной теории волн, представим гиперболический синус в
экспоненциальной форме и отбросим член, содержащий $e^{-2\pi{k}{z}}$, как
противоречащий условию $\phi\underset{z\rightarrow-\infty}{\longrightarrow}0$.
После взятия действительной части выражения получится известная формула линейной
теории $\phi(x,z,t)=\frac{A}{k}e^{2\pi{k}{z}}\sin(2\pi(kx-t))$. Аналогично,
предположение о малости амплитуд волн позволяет упростить формулу
eqref:eq:solution-2d-full до
\begin{equation*}
    \phi(x,z,t)
    =
    -\InverseFourierY{
        \frac{\Sinh{2\pi u (z+h)}}{2\pi u \Sinh{2\pi u h}}
        \FourierY{\zeta_t}{u}
    }{x}.
\end{equation*}
Подстановка формулы для прогрессивной плоской волны вместо $\zeta(x,t)$ дает
равенство
\begin{equation}
    \label{eq:solution-2d-linear}
    \phi(x,z,t)=\frac{A}{k}
    \frac{\Sinh{2 \pi k (z+h)}}{ \Sinh{2 \pi k h} }
    \sin(2 \pi (k x-t)),
\end{equation}
что соответствует формуле линейной теории для конечной глубины.

Различные записи решения уравнения Лапласа, в которых затухающая экспонента
может встречаться как со знаком "+", так и со знаком "-", могут стать причиной
разницы между формулами линейно теории и формулами, выведенными в данной работе,
где вместо $\sinh$ используется $\cosh$. Выражение
$\frac{\Sinh{2\pi{k}(z+h)}}{\Sinh{2\pi{k}{h}}}\approx\frac{\sinh(2\pi{k}(z+h))}{\sinh(2\pi{k}{h})}$
превращается в строгое равенство на поверхности, и разница между правой левой
частью увеличивается при приближении к дну водоема (для достаточно большой
глубины ошибка вблизи поверхности жидкости незначительна). Поэтому для
достаточно большой глубины можно использовать любую из функций ($\cosh$ или
$\sinh$) для вычисления потенциала скорости вблизи взволнованной поверхности.

Сведение формул eqref:eq:solution-2d и eqref:eq:solution-2d-full к формулам
линейной теории волн показывает, что формула eqref:eq:solution-2d для жидкости
бесконечной глубины не подходит для вычисления потенциала скорости с
использованием метода Фурье, т.к. не обладает необходимой для преобразования
Фурье симметрией. Однако, для такого случая можно использовать формулу для
конечной глубины, полагая $h$ равным характерному значению глубины исследуемого
водоема. Для стоячих волн сведение к формулам линейной теории происходит с
аналогичными предположениями.

*** Трехмерное поле скоростей
В трех измерениях исходная система уравнений eqref:eq:problem переписывается как
\begin{align}
    \label{eq:problem-3d}
    & \phi_xx + \phi_yy + \phi_zz = 0,\\
    & \zeta_t + \zeta_x\phi_x + \zeta_y\phi_y
    =
    \frac{\zeta_x}{\sqrt{1 + \zeta_x^2}} \phi_x
    +\frac{\zeta_y}{\sqrt{\vphantom{\zeta_x^2}\smash[b]{1 + \zeta_y^2}}} \phi_y
    - \phi_z, & \text{на }z=\zeta(x,y,t).\nonumber
\end{align}
Для ее решения также воспользуемся методом Фурье. Возьмем преобразование Фурье
от обоих частей уравнений Лапласа и получим
\begin{equation*}
    -4 \pi^2 \left( u^2 + v^2 + w^2 \right)
    \FourierY{\phi(x,y,z)}{u,v,w} = 0,
\end{equation*}
откуда имеем $w=\pm{i}\sqrt{u^2+v^2}$. Решение уравнения будем искать в виде
обратного преобразования Фурье $\phi(x,y,z)=\InverseFourierY{E(u,v,w)}{x,y,z}$.
Применяя полученное равенство, получаем
\begin{equation*}
    \phi(x,y,z) = \InverseFourierY{
        \left(
            C_1 e^{2\pi \sqrt{u^2+v^2} z}
            -C_2 e^{-2\pi \sqrt{u^2+v^2} z}
        \right)
        E(u,v)
    }{x,y}.
\end{equation*}
Подставляя $\phi$ в условие на дне водоема аналогично двухмерному случаю,
получаем
\begin{equation}
    \label{eq:guessed-sol-3d}
    \phi(x,y,z) = \InverseFourierY{
        \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)
    }{x,y}.
\end{equation}
Подставляя выражение для $\phi$ в граничное условие, получим
\begin{equation*}
    \arraycolsep=1.4pt
    \begin{array}{rl}
        \zeta_t = & i f_1(x,y) \InverseFourierY{2 \pi u \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}{x,y} \\
        + & i f_2(x,y) \InverseFourierY{2 \pi v \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}{x,y} \\
        - & \InverseFourierY{2 \pi \sqrt{u^2+v^2} \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}{x,y}
    \end{array}
\end{equation*}
где $f_1(x,y)={\zeta_x}/{\sqrt{1+\zeta_x^2}}-\zeta_x$ и
$f_2(x,y)={\zeta_y}/{\sqrt{\vphantom{\zeta_x^2}\smash[b]{1+\zeta_y^2}}}-\zeta_y$.
Применяя преобразование Фурье к обеим частям, получаем выражение для
коэффициентов $E$:
\begin{equation*}
    \arraycolsep=1.4pt
    \begin{array}{rl}
        \FourierY{\zeta_t}{u,v} = &
        \FourierY{i f_1(x,y) \InverseFourierY{2 \pi u \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)}{x,y}}{u,v}  \\
        + & \FourierY{i f_2(x,y) \InverseFourierY{2 \pi v \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)}{x,y}}{u,v}  \\
        - & 2 \pi \sqrt{u^2+v^2} \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)
    \end{array}
\end{equation*}
Окончательное решение получается при подстановке выражения для $E(u,v)$
в eqref:eq:guessed-sol-3d.

* Численные методы и результаты экспериментов
** Форма АКФ для разных волновых профилей
*** Два метода для определения формы АКФ морских волн
**** Аналитический метод.
Прямой способ нахождения АКФ, соответствующей заданному профилю морской волны,
состоит в применении теоремы Винера---Хинчина. Согласно этой теореме
автокорреляционная функция $K$ функции $\zeta$ равна преобразованию Фурье от
квадрата модуля этой функции:
\begin{equation}
  K(t) = \Fourier{\left| \zeta(t) \right|^2}.
  \label{eq:wiener-khinchin}
\end{equation}
Если заменить $\zeta$ на формулу для волнового профиля, то это выражение даст
аналитическую формулу для соответствующей АКФ.

Для трехмерного волнового профиля (два пространственных и одно временное
измерение) аналитическая формула представляет собой многочлен высокой степени, и
ее лучше всего вычислять с помощью программы для символьных вычислений. Затем,
для практического применения она может быть аппроксимирована суперпозицией
экспоненциально затухающих косинусов (именно так выглядит АКФ стационарного
процесса АРСС cite:box1976time).

**** Эмпирический метод.
Впрочем, для трехмерного случая существует более простой эмпирический метод
нахождения формы АКФ, не требующий использования сложного программного
обеспечения. Известно, что АКФ, представляющая собой суперпозицию
экспоненциально затухающих косинусов, является решением уравнения Стокса для
гравитационных волн cite:boccotti1983wind. Значит, если в моделируемом морском
волнении важна только форма волны, а не точные ее характеристики, то заданный
волновой профиль можно просто домножить на затухающую экспоненту, чтобы получить
подходящую АКФ. Эта АКФ не отражает параметры волн, такие как высота и период,
зато это открывает возможность моделировать волны определенных неаналитических
форм, "рисуя" профиль волны, домножая его на экспоненту и используя
результирующую функцию в качестве АКФ. Таким образом, эмпирический метод
неточен, но более простой по сравнению с применением теоремы Винера---Хинчина;
он, в основном, полезен для тестирования модели АРСС.

*** Примеры АКФ для различных волновых профилей
**** АКФ стоячей волны.
Профиль трехмерной плоской стоячей волны задается как
\begin{equation}
  \zeta(t, x, y) = A \sin (k_x x + k_y y) \sin (\sigma t).
  \label{eq:standing-wave}
\end{equation}
Найдем АКФ с помощью аналитического метода. Домножив формулу на затухающую
экспоненту (поскольку преобразование Фурье определено для функции $f$, для
которой справедливо $f\underset{x\rightarrow\pm\infty}{\longrightarrow}0$),
получим
\begin{equation}
  \zeta(t, x, y) =
  A
  \exp\left[-\alpha (|t|+|x|+|y|) \right]
  \sin (k_x x + k_y y) \sin (\sigma t).
  \label{eq:decaying-standing-wave}
\end{equation}
Затем, применяя трехмерное преобразование Фурье к обоим частям уравнения с
помощью программы для символьных вычислений, получим многочлен высокой степени,
который аппроксимируем выражением
\begin{equation}
  K(t,x,y) =
  \gamma
  \exp\left[-\alpha (|t|+|x|+|y|) \right]
  \cos \beta t
  \cos \left[ \beta x + \beta y \right].
  \label{eq:standing-wave-acf}
\end{equation}
Таким образом, после применения теоремы Винера---Хинчина получаем исходную
формулу, но с косинусами вместо синусов. Это различие важно, поскольку значение
АКФ в точке $(0,0,0)$ равно дисперсии процесса АРСС, которое при использовании
синусов было бы неверным.

Если попытаться получить ту же самую формулу с помощью эмпирического метода, то
выражение eqref:eq:decaying-standing-wave необходимо адаптировать для
соответствия eqref:eq:standing-wave-acf. Это можно осуществить либо, изменяя
фазу синуса, либо заменой синуса на косинус, чтобы сдвинуть максимум функции в
начало координат.

**** АКФ прогрессивной волны.
Профиль трехмерной плоской прогрессивной волны задается как
\begin{equation}
  \zeta(t, x, y) = A \cos (\sigma t + k_x x + k_y y).
  \label{eq:propagating-wave}
\end{equation}
Для аналитического метода повторение шагов из предыдущих двух параграфов дает
\begin{equation}
  K(t,x,y) =
  \gamma
  \exp\left[-\alpha (|t|+|x|+|y|) \right]
  \cos\left[\beta (t+x+y) \right].
  \label{eq:propagating-wave-acf}
\end{equation}
Для эмпирического метода профиль волны можно просто домножить на затухающую
экспоненту, не изменяя положение максимума АКФ (как это требовалось для стоячей
волны).

*** Сравнение изученных методов
Итого, аналитический метод нахождения АКФ морских волн сводится к следующим
шагам.
- Обеспечить затухание выражения для профиля волны на $\pm\infty$, домножив его
  на затухающую экспоненту.
- Взять преобразование Фурье от квадрата модуля получившегося профиля,
  воспользовавшись программой для символьных вычислений.
- Аппроксимировать получившийся многочлен подходящим выражением для АКФ.

Два примера этого раздела показывают, что затухающие профили стоячих и
прогрессивных волн схожи по форме с соответствующими АКФ с тем лишь различием,
что максимум АКФ должен быть перенесен в начало координат, чтобы сохранить
дисперсию моделируемого процесса. Применение эмпирического метода нахождения АКФ
сводится к следующим шагам.
- Обеспечить затухание выражения для профиля волны на $\pm\infty$, домножив его
  на затухающую экспоненту.
- Перенести максимум получившейся функции в начало координат, используя свойства
  тригонометрических функций для сдвига фазы.

** Дополнительные формулы, методы и алгоритмы для модели АРСС
*** Аппроксимация распределения аппликат
Одним из параметров генератора взволнованной морской поверхности служит функция
плотности распределения (ФПР) аппликат этой поверхности. Она задается либо
полиномиальной аппроксимацией натурных данных, либо аналитически.

**** Разложение в ряд Грама---Шарлье.
В cite:huang1980experimental было экспериментально показано, что распределение
аппликат морской поверхности отличается от нормального ненулевым эксцессом и
асимметрией. В cite:рожков1996теория показано, что такое распределение
раскладывается в ряд Грама---Шарлье:
\begin{align}
    \label{eq:skew-normal-1}
    F(z; \gamma_1, \gamma_2) & = \phi(z)
        - \gamma_1 \frac{\phi'''(z)}{3!}
        + \gamma_2 \frac{\phi''''(z)}{4!} \nonumber \\
    & =
    \frac{1}{2} \text{erf}\left[\frac{z}{\sqrt{2}}\right]
    -
    \frac{e^{-\frac{z^2}{2}}}{\sqrt{2\pi}}
    \left[
        \frac{1}{6} \gamma_1 \left(z^2-1\right)
        + \frac{1}{24} \gamma_2 z \left(z^2-3\right)
    \right]
    ,\nonumber \\
    f(z; \gamma_1, \gamma_2) & =
    \frac{e^{-\frac{z^2}{2}}}{\sqrt{2 \pi }}
    \left[
        \frac{1}{6} \gamma_1 z \left(z^2-3\right)
        + \frac{1}{24} \gamma_2 \left(z^4-6z^2+3\right)
        +1
    \right],
\end{align}
где $\phi(z)=\frac{1}{2}\mathrm{erf}(z/\sqrt{2})$, $\gamma_1$ --- асимметрия,
$\gamma_2$ --- эксцесс, $f$ --- ФПР, $F$ --- функция распределения (ФР).
Согласно cite:рожков1990вероятностные для аппликат морских волн значение
асимметрии выбирается на интервале $0,1\leq\gamma_1\leq{0,52}]$, а значение
эксцесса на интервале $0,1\leq\gamma_2\leq{0,7}$. Семейство плотностей
распределения при различных параметрах показано на [[fig:skew-normal-1]].

#+name: fig:skew-normal-1
#+begin_src R :results output graphics :exports results :file build/skew-normal-1.pdf
source(file.path("R", "common.R"))
x <- seq(-3, 3, length.out=100)
params <- data.frame(
  skewness = c(0.00, 0.52, 0.00, 0.52),
  kurtosis = c(0.00, 0.00, 0.70, 0.70),
  linetypes = c("solid", "dashed", "dotdash", "dotted")
)
arma.skew_normal_1_plot(x, params)
legend(
  "topleft",
  mapply(
    function (s, k) {
      as.expression(bquote(list(
        gamma[1] == .(arma.fmt(s, 2)),
        gamma[2] == .(arma.fmt(k, 2))
      )))
    },
    params$skewness,
    params$kurtosis
  ),
  lty = paste(params$linetypes)
)
#+end_src

#+caption: Вид плотности распределения eqref:eq:skew-normal-1 аппликат взволнованной морской поверхности при различных значениях асимметрии $\gamma_1$ и эксцесса $\gamma_2$.
#+RESULTS: fig:skew-normal-1
[[file:build/skew-normal-1.pdf]]

**** Асимметричное нормальное распределение.
Альтернативной аппроксимацией распределения волновых аппликат служит формула
асимметричного нормального распределения:
\begin{align}
    \label{eq:skew-normal-2}
    F(z; \alpha) & = \frac{1}{2}
   \mathrm{erfc}\left[-\frac{z}{\sqrt{2}}\right]-2 T(z,\alpha ), \nonumber \\
    f(z; \alpha) & = \frac{e^{-\frac{z^2}{2}}}{\sqrt{2 \pi }}
   \mathrm{erfc}\left[-\frac{\alpha z}{\sqrt{2}}\right],
\end{align}
где $T$ --- функция Оуэна cite:owen1956tables. Эта формула не позволяет задать
значения асимметрии и эксцесса по отдельности --- оба значения регулируются
параметром $\alpha$. Преимущество данной формулы лишь в относительной простоте
вычисления: эта функция встроена в некоторые программы и библиотеки
математических функций. График функции для разных значений $\alpha$ представлен
на [[fig:skew-normal-2]].

#+name: fig:skew-normal-2
#+begin_src R :results output graphics :exports results :file build/skew-normal-2.pdf
source(file.path("R", "common.R"))
x <- seq(-3, 3, length.out=100)
alpha <- c(0.00, 0.87, 2.25, 4.90)
params <- data.frame(
  alpha = alpha,
  skewness = arma.bits.skewness_2(alpha),
  kurtosis = arma.bits.kurtosis_2(alpha),
  linetypes = c("solid", "dashed", "dotdash", "dotted")
)
arma.skew_normal_2_plot(x, params)
legend(
  "topleft",
  mapply(
    function (a, s, k) {
      as.expression(bquote(list(
        alpha == .(arma.fmt(a, 2)),
        gamma[1] == .(arma.fmt(s, 2)),
        gamma[2] == .(arma.fmt(k, 2))
      )))
    },
    params$alpha,
    params$skewness,
    params$kurtosis
  ),
  lty = paste(params$linetypes)
)
#+end_src

#+caption: Вид плотности распределения eqref:eq:skew-normal-2 волновых аппликат при различных значениях коэффициента асимметрии $\alpha$.
#+RESULTS: fig:skew-normal-2
[[file:build/skew-normal-2.pdf]]

**** Тестирование.
Решение уравнения eqref:eq:distribution-transformation с выбранной функцией
распределения можно произвести либо в каждой точке генерируемой поверхности, что
даст наиболее точные результаты, либо в каждой точке фиксированной сетки,
интерполировав решение методом наименьших квадратов (МНК). Во втором случае
точность будет меньше. Например, интерполяция многочленом 12-го порядка на сетке
из 500 узлов, построенной на промежутке $-5\sigma_z\leq{z}\leq{5}\sigma_z$, дает
погрешность $\approx{0,43}\cdot10^{-3}$. Увеличение порядка многочлена приводит
либо к переполнениям при интерполяции МНК, либо к дополнительным коэффициентам
близким к нулю; увеличение размера сетки влияет на результат незначительно. В
большинстве случаев трех коэффициентов ряда Грама---Шарлье было достаточно для
преобразования АКФ; относительная погрешность без интерполяции составляет
$10^{-5}$.

*** Алгоритм генерации белого шума
Чтобы исключить периодичность из сгенерированной моделью ветрового волнения
реализации взволнованной поверхности, для генерации белого шума нужно
использовать ГПСЧ с достаточно большим периодом. В качестве такого генератора в
работе используется параллельная реализация вихря Мерсенна
cite:matsumoto1998mersenne с периодом $2^{19937}-1$. Это позволяет создавать
апериодичные реализации взволнованной морской поверхности для любых сценариев
применения, встречаемых на практике.

Запуск нескольких ГПСЧ с разными начальными состояниями в параллельных потоках
не гарантирует некоррелированность генерируемых последовательностей
псевдослучайных чисел, однако, можно воспользоваться алгоритмом динамического
создания вихрей Мерсенна cite:matsumoto1998dynamic, чтобы дать такую гарантию.
Суть алгоритма заключается в поиске таких матриц начальных состояний
генераторов, которые бы дали максимально некоррелированные последовательности
псевдослучайных чисел при параллельном запуске нескольких вихрей Мерсенна с
этими начальными состоянями. Поскольку на поиск начальных состояний можно
потратить значительное количество процессорного времени, то вектор состояний
создается предварительно для заведомо большего количества параллельных потоков и
сохраняется в файл, который впоследствиии считывается основной программой перед
началом генерации белого шума.

*** Алгоритм генерации взволнованной поверхности
В модели АРСС значение подъема взволнованной поверхности в каждой точке зависит
от предыдущих по пространству и времени значений, из-за чего в начале реализации
образуется так называемый /интервал разгона/ --- промежуток, на котором
реализация не соответствует заданной АКФ. Способ решения этой проблемы зависит
от контекста, в котором происходит моделирование.

Если реализация используется в контексте расчета остойчивости судна без учета
маневрирования, то интервал никак не повлияет результаты эксперимента, поскольку
находится на границе (далеко от исследуемого морского объекта). Если изучается
остойчивость судна в условиях маневрирования, то интервал проще всего исключить
из реализации (размер интервала примерно равен числу коэффициентов АР по каждому
из измерений). Однако, это приводит к потере большого числа точек, поскольку
исключение происходит по каждому из трех измерений. Альтернативным подходом
является генерация взволнованной поверхности на интервале разгона моделью ЛХ и
генерация остальной реализации с помощью модели АРСС.

В алгоритме генерации взволнованной поверхности используется параллелизм по
данным: реализация делится на равные части, каждая из которых генерируется
независимо, --- однако, в начале каждой из частей также присутствует интервал
разгона. Для его исключения используется метод /сшивания/, часто применяемый в
обработке цифровых сигналов
cite:oppenheim1989discrete,svoboda2011efficient,pavel2013algorithms. Суть метода
заключается в добавлении интервала равного по размеру интервалу разгона в конец
каждой из частей. Затем взволнованная поверхность генерируется в каждой точки
каждой из частей (включая добавленный интервал), интервал в конце части $N$
накладывается на интервал разгона в начале части $N+1$, и значения в
соответствующих точках складываются.

*** Формулы нормировки для потенциалов скоростей
:PROPERTIES:
:CUSTOM_ID: sec:compute-delta
:END:

В решениях eqref:eq:solution-2d и eqref:eq:solution-2d-full двухмерной задачи
определения поля давлений присутствуют функции
$\Fun{z}=\InverseFourierY{e^{2\pi{u}{z}}}{x}$ и
$\FunSecond{z}=\InverseFourierY{\Sinh{2\pi{u}{z}}}{x}$, которые могут быть
записаны аналитически различными выражениями и представляют сложность при
вычислении на компьютере. Каждая функция --- это преобразование Фурье от
линейной комбинации экспонент, которое сводится к плохо определенной дельта
функции комплексного аргумента (см. [[tab:delta-functions]]). Обычно такого типа
функции записывают как произведение дельта функций от действительной и мнимой
части, однако, такой подход не работает здесь, поскольку взятие обратного
преобразования Фурье не даст экспоненту, что сильно исказит результирующее поле
скоростей. Для получения однозначного аналитического выражения можно
воспользоваться нормировкой $1/\Sinh{2\pi{u}{h}}$ (которая также включается в
выражение для коэффициентов $E(u)$). Численные эксперименты показывают, что
нормировка хоть и позволяет получить адекватное поле скоростей, оно мало
отличается от выражений из линейной теории волн, в которых члены с $\zeta$
опускаются.

#+name: tab:delta-functions
#+caption: Формулы для вычисления $\Fun{z}$ и $\FunSecond{z}$ из [[#sec:pressure-2d]], использующие нормировку для исключения неоднозначности определения дельта функции комплексного аргумента.
#+attr_latex: :booktabs t
| Функция         | Без нормировки                                             | С нормировкой                                                                                                                        |
|-----------------+------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------|
| $\Fun{z}$       | $\delta (x+i z)$                                           | $\frac{1}{2 h}\mathrm{sech}\left(\frac{\pi  (x-i (h+z))}{2 h}\right)$                                                                |
| $\FunSecond{z}$ | $\frac{1}{2}\left[\delta (x-i z) + \delta (x+i z) \right]$ | $\frac{1}{4 h}\left[\text{sech}\left(\frac{\pi  (x-i (h+z))}{2 h}\right)+\text{sech}\left(\frac{\pi  (x+i(h+z))}{2 h}\right)\right]$ |

** Верификация модели АРСС
:PROPERTIES:
:CUSTOM_ID: sec:verification
:END:

Для модели АР в работах
cite:degtyarev2011modelling,degtyarev2013synoptic,boukhanovsky1997thesis
экспериментальным путем были верифицированы
- распределения различных характеристик волн (высоты волн, длины волн, длины
  гребней, период волн, уклон волн, показатель трехмерности),
- дисперсионное соотношение,
- сохранение интегральных характеристик для случая смешанного волнения.
В данной работе верифицируются как модель АР, так и СС путем сравнения
распределений различных характеристик волн.

*** Верификация интегральных характеристик взволнованной поверхности
В cite:рожков1990вероятностные авторы показывают, что некоторые характеристики
морских волн (перечисленные в таблице [[tab:weibull-shape]]) имеют распределение
Вейбулла, а подъем взволнованной поверхности --- нормальное распределение. Для
верификации генерируемых моделями АР и СС реализаций используются спрямленные
диаграммы (графики, в которых по оси $OX$ откладываются квантили функции
распределения, вычисленные аналитически, а по оси $OY$ --- вычисленные
экспериментально). Если экспериментально полученное распределение соответствует
аналитическому, то график представляет собой прямую линию. Концы графика могут
отклоняться от прямой линии, поскольку не могут быть надежно получены из
реализации конечной длины. Различные методы извлечения волн из реализации также
могут привести к вариациям на концах графиков, извлечь каждую волну из
реализации практически невозможно, поскольку они могут (и часто) накладываются
друг на друга.

#+name: tab:weibull-shape
#+caption: Значение коэффициента формы $k$ распределения Вейбулла для различных характеристик волн.
#+attr_latex: :booktabs t
| Характеристика          | Коэффициент формы $k$ |
|-------------------------+-----------------------|
| Высота волны            |                     2 |
| Длина волны             |                   2,3 |
| Длина гребня волны      |                   2,3 |
| Период волны            |                     3 |
| Уклон волны             |                   2,5 |
| Показатель трехмерности |                   2,5 |

Верификация производится для стоячих и прогрессивных волн. Соответствующие АКФ и
спрямленные диаграммы распределений характеристик волн представлены на рис.
[[acf-slices]], [[standing-wave-distributions]], [[propagating-wave-distributions]].

#+name: propagating-wave-distributions
#+begin_src R :results output graphics :exports results :file build/propagating-wave-qqplots.pdf
source(file.path("R", "common.R"))
par(pty="s", mfrow=c(2, 2))
arma.qqplot_grid(
  file.path("build", "propagating_wave"),
  c("elevation", "heights_y", "lengths_y", "periods")
)
#+end_src

#+caption: Спрямленные диаграммы для прогрессивных волн.
#+RESULTS: propagating-wave-distributions
[[file:build/propagating-wave-qqplots.pdf]]

#+name: standing-wave-distributions
#+begin_src R :results output graphics :exports results :file build/standing-wave-qqplots.pdf
source(file.path("R", "common.R"))
par(pty="s", mfrow=c(2, 2))
arma.qqplot_grid(
  file.path("build", "standing_wave"),
  c("elevation", "heights_y", "lengths_y", "periods")
)
#+end_src

#+caption: Спрямленные диаграммы для стоячих волн.
#+RESULTS: standing-wave-distributions
[[file:build/standing-wave-qqplots.pdf]]

#+name: acf-slices
#+header: :width 6 :height 9
#+begin_src R :results output graphics :exports results :file build/acf-slices.pdf
source(file.path("R", "common.R"))
propagating_acf <- read.csv(file.path("build", "propagating_wave", "acf.csv"))
standing_acf <- read.csv(file.path("build", "standing_wave", "acf.csv"))
par(mfrow=c(5, 2), mar=c(0,0,0,0))
for (i in seq(0, 4)) {
  arma.wavy_plot(standing_acf, i, zlim=c(-5,5))
  arma.wavy_plot(propagating_acf, i, zlim=c(-5,5))
}
#+end_src

#+caption: Временные срезы АКФ для стоячих (слева) и прогрессивных (справа) волн.
#+RESULTS: acf-slices
[[file:build/acf-slices.pdf]]

*** Верификация полей потенциалов скоростей
:PROPERTIES:
:CUSTOM_ID: sec:compare-formulae
:END:

Сравнение полученных общих формул eqref:eq:solution-2d и
eqref:eq:solution-2d-full с известными формулами линейной теории волн позволяет
оценить различие между полями скоростей для волн как больших, так и малых
амплитуд. В общем случае аналитическое выражение для потенциала скорости
неизвестно даже для плоских волн, поэтому сравнение производится численно. Имея
ввиду выводы раздела [[#sec:pressure-2d]], сравниваются только формулы для случая
конечной глубины.

**** Отличие от формул линейной теории волн.
Эксперимент показывает, что поля потенциалов скоростей, полученные по формуле
eqref:eq:solution-2d-full для конечной глубины и по формуле
eqref:eq:solution-2d-linear линейной теории, качественно отличаются (см.
[[fig:potential-field-nonlinear]]). Во-первых, контуры потенциала скорости имеют вид
затухающей синусоиды, что отличается от овальной формы, описываемой линейной
теории волн. Во-вторых, по мере приближения к дну водоема потенциал скорости
затухает гораздо быстрее, чем в линейной теории, а область, где сконцентрирована
большая часть энергии волны, еще больше приближена к ее гребню. Аналогичный
численный эксперимент, в котором из формулы eqref:eq:solution-2d-full были
исключены члены, которыми пренебрегают в рамках линейной теории волн, показал,
что полное соотвествие получившихся полей потенциалов скоростей (насколько это
позволяет сделать машинная точность).

#+name: fig:potential-field-nonlinear
#+caption: Поле потенциала скорости прогрессивной волны $\zeta(x,y,t) = \cos(2\pi x - t/2)$. Поле, полученное по формуле eqref:eq:solution-2d-full (слева) и по формуле линейной теории волн (справа).
#+attr_latex: :width 0.47\textwidth
#+begin_figure
[[file:graphics/pressure/potential-5.eps]]
[[file:graphics/pressure/potential-6.eps]]
#+end_figure

**** Отличие от формул теории волн малой амплитуды.
Эксперимент показывает, что поля скоростей, полученные по формуле
eqref:eq:solution-2d-full и формуле для волн малой амплитуды
eqref:eq:old-sol-2d, сопоставимы для волн малых амплитуд. В этом эксперименте
используются две реализации взволнованной морской поверхности, полученные по
модели АР: одна содержит волны малой амплитуды, другая --- большой.
Интегрирование в формуле eqref:eq:solution-2d-full ведется диапазону волновых
чисел, полученному из морской поверхности. Для волн малой амплитуды обе формулы
показывают сопоставимые результаты (разница в значениях скорости приписывается
стохастической природе модели АР), в то время как для волн больших амплитуд
устойчивое поле скоростей дает только формула eqref:eq:solution-2d-full (рис.
[[fig:velocity-field-2d]]). Таким образом, общая формула eqref:eq:solution-2d-full
показывает удовлетворительные результаты, не вводя ограничения на амплитуду
волн.

#+name: fig:velocity-field-2d
#+caption: Сравнение полей скоростей на поверхности моря, полученных по общей формуле ($u_1$) и формуле для волн малой амплитуды ($u_2$). Поле скоростей для поверхности волн малой амплитуды (слева) и большой амплитуды (справа).
#+begin_figure
[[file:build/low-amp-nocolor.eps]]
[[file:build/high-amp-nocolor.eps]]
#+end_figure

*** Нефизическая природа модели
Благодаря своей нефизической природе модель АРСС не включает в себя понятие
морской волны; вместо этого она моделирует взволнованную поверхность как единое
целое. Движения отдельных волн и их форма часто получаются грубыми, а точное
количество генерируемых волн неизвестно. Несмотря на это, интегральные
характеристики взволнованной поверхности соответствуют реальным морским волнам.

Теоретически, профили самих морских волн могут быть использованы в качестве АКФ,
если предварительно обеспечить их экспоненциальное затухание. Это может
позволить генерировать волны произвольных профилей и является одной из тем
дальнейших исследований.

* Высокопроизводительный программный комплекс для моделирования морского волнения
** Модель вычислений
*** Основополагающие принципы модели
*** Отображение алгоритма генерации взволнованной поверхности на вычислительную модель
#+name: fig:pipeline
#+begin_src dot :exports results :file build/pipeline-ru.pdf
digraph {

  node [fontsize=14,margin="0.055,0"]
  graph [nodesep="0.25",ranksep="0.25",rankdir="TB"]
  edge [arrowsize=0.66]

  # data
  subgraph xcluster_linear {
    label="Линейная модель"

    start [label="",shape=circle,style=filled,fillcolor=black,width=0.23]
    spectrum [label="S(ω,θ)",shape=box]
    acf [label="K(i,j,k)",shape=box]
    phi [label="Φ(i,j,k)",shape=box]

    # transformations
    fourier_transform [label="Преобразование Фурье",shape=box,style=rounded]
    solve_yule_walker [label="Решение уравнений\nЮла—Уокера",shape=box,style=rounded]

    subgraph cluster_nonlinear_1 {
      label="Моделир. нелинейности\l"
      labeljust=left
      style=filled
      color=lightgrey
      acf2 [label="K*(i,j,k)",shape=box]
      transform_acf [label="Преобразование АКФ",shape=box,style=rounded]
    }
  }

  subgraph xcluster_linear2 {

    eps_parts [label="<e1> ε₁|<e2> ε₂|<e3> …|<e4> εₙ|<e> ε(t,x,y)",shape=record]
    end [label="",shape=doublecircle,style=filled,fillcolor=black,width=0.23]

    generate_white_noise [label="<g1> g₁|<g2> g₂|<g3> …|<g4> gₙ|<gen> Генерация\lбелого шума",shape=record,style=rounded]
    generate_zeta [label="<g1> g₁|<g2> g₂|<g3> …|<g4> gₙ|<gen> Генерация частей\lвзволнованной мор-\lской поверхности\l",shape=record,style=rounded]

    zeta_parts [label="<g1> ζ₁|<g2> ζ₂|<g3> …|<g4> ζₙ|<gen> Несшитые части реализации",shape=record]
    overlap_add [label="<g1> ζ₁|<g2> ζ₂|<g3> …|<g4> ζₙ|<gen> Сшивание час-\lтей реализации\l",shape=record,style=rounded]

    zeta_parts:g1->overlap_add:g1
    zeta_parts:g2->overlap_add:g2
    zeta_parts:g3->overlap_add:g3
    zeta_parts:g4->overlap_add:g4

    zeta_parts:g2->overlap_add:g1 [constraint=false]
    zeta_parts:g3->overlap_add:g2 [constraint=false]
    zeta_parts:g4->overlap_add:g3 [constraint=false]

    overlap_add:g1->zeta2_parts:g1
    overlap_add:g2->zeta2_parts:g2
    overlap_add:g3->zeta2_parts:g3
    overlap_add:g4->zeta2_parts:g4

    zeta2_parts:g1->transform_zeta:g1->zeta3_parts:g1->write_zeta:g1->eps_end
    zeta2_parts:g2->transform_zeta:g2->zeta3_parts:g2->write_zeta:g2->eps_end
    zeta2_parts:g3->transform_zeta:g3->zeta3_parts:g3->write_zeta:g3->eps_end
    zeta2_parts:g4->transform_zeta:g4->zeta3_parts:g4->write_zeta:g4->eps_end

  }

  subgraph part3 {

    zeta2_parts [label="<g1> ζ₁|<g2> ζ₂|<g3> …|<g4> ζₙ|<gen> Поверхность с нормаль-\lным законом распреде-\lления\l",shape=record]

    subgraph cluster_nonlinear_2 {
      label="Моделир. нелинейности\r"
      labeljust=right
      style=filled
      color=lightgrey
      zeta3_parts [label="<g1> ζ₁|<g2> ζ₂|<g3> …|<g4> ζₙ|<gen> ζ(t,x,y)",shape=record]
      transform_zeta [label="<g1> g₁|<g2> g₂|<g3> …|<g4> gₙ|<gen> Преобразование за-\lкона распределения\lвзволнованной мор-\lской поверхности\l",shape=record,style=rounded]
    }

    # barriers
    eps_start [label="",shape=box,style=filled,fillcolor=black,height=0.05]
    eps_end [label="",shape=box,style=filled,fillcolor=black,height=0.05]

    write_zeta [label="<g1> g₁|<g2> g₂|<g3> …|<g4> gₙ|<gen> Запись готовых\lчастей в файл\l",shape=record,style=rounded]
  }

  # edges
  start->spectrum->fourier_transform->acf->transform_acf
  transform_acf->acf2
  acf2->solve_yule_walker
  solve_yule_walker->phi
  phi->eps_start [constraint=false]
  eps_start->generate_white_noise:g1
  eps_start->generate_white_noise:g2
  eps_start->generate_white_noise:g3
  eps_start->generate_white_noise:g4
  generate_white_noise:g1->eps_parts:e1->generate_zeta:g1->zeta_parts:g1
  generate_white_noise:g2->eps_parts:e2->generate_zeta:g2->zeta_parts:g2
  generate_white_noise:g3->eps_parts:e3->generate_zeta:g3->zeta_parts:g3
  generate_white_noise:g4->eps_parts:e4->generate_zeta:g4->zeta_parts:g4

  eps_end->end
}
#+end_src

#+caption: Схема конвейера обработки данных, реализующего генерацию взволнованной морской поверхности по АР модели.
#+RESULTS: fig:pipeline
[[file:build/pipeline-ru.pdf]]

** Реализация для систем с общей памятью (SMP)
*** Алгоритм распределения нагрузки
*** Результаты тестирования
**** Производительности реализаций на MPI, OpenMP и OpenCL.
**** Производительность алгоритма распределения нагрузки.
** Реализация для систем с распределенной памятью (MPP)
*** Алгоритм обнаружения узлов кластера
*** Алгоритм восстановления после сбоев
**** Обеспечение отказоустойчивости.
**** Обеспечение высокой доступности.
* Заключение
**** Итоги исследования.
В изучении возможностей математического аппарата для имитационного моделирования
морского волнения, выходящего за рамки линейной теории волн, были достигнуты
следующие основные результаты.
- Разработана модель ветрового волнения для генерации волн произвольных
  амплитуд.
- Разработан гибридный метод расчета давлений в двухмерной постановке,
  использующий как аналитические выражения, так и численное интегрирование по
  алгоритму быстрого преобразования Фурье.
- Разработанный метод позволил упростить программную реализацию комплекса, и
  свести реализацию алгоритма к параллельному вычислению большого количества
  преобразований Фурье.
- Предварительная апробация авторегрессионной модели и метода расчета давлений
  была произведена в пакете Large Amplitude Motion Program 4.

**** Перспективы дальнейших исследований.
Хотя задача генерации взволнованной морской поверхности была решена в трехмерной
постановке, для задачи расчета гидродинамических давлений было найдено
аналитическое решение только в двухмерном случае. В трехмерной постановке
полученные формулы не были всесторонне исследованы. Таким образом, дальнейшие
исследования предполагают изучение аналитического решения для трехмерный случая,
а также создание виртуального полигона на основе модели АРСС и метода расчета
давлений по результатам апробации в пакете Large Amplitude Motion Program 4.

* Выводы
Результаты исследования позволяют сделать вывод о том, что задача вычисления
давлений под реальной морской поверхностью может быть решена аналитически в
двухмерной постановке, минуя предположения линейной теории волн и теории волн
малой амплитуды. Это аналитическое решение в паре с моделью АРСС ветрового
волнения, способной генерировать волны произвольных амплитуд, может быть
использовано для расчета влияния колебаний волн на поведение динамического
объекта в открытом море, и дает более точные результаты чем аналогичное решение
для волн малых амплитуд. Результаты проведенных экспериментов позволяют сделать
вывод о том, что как генерация взволнованной поверхности так и расчет
гидродинамических давлений могут быть реализованы эффективно с использованием
алгоритмов быстрого преобразования Фурье, а распределенная система научных
расчетов может быть использвана для длительных сессий имитационного
моделирования. Разработанный в работе математический аппарат и его программная
реализация могут стать основой виртуального полигона, предназанченного для
расчетов динамики морских объектов.

* TODO Благодарности
Исследования были проведены с использованием вычислительных ресурсов Ресурсного
Центра "Вычислительный центр СПбГУ" ([[http://cc.spbu.ru/]]) при поддержке
грантами РФФИ №16-07-01111, №16-07-00886 и грантом СПбГУ №0.37.155.2014.

#+latex: \clearpage
* Список сокращений и условных обозначений

#+attr_latex: :booktabs t :align lp{0.8\linewidth}
| <<<MPP>>>  | Massively Parallel Processing, класс вычислительных систем с разделенной памятью            |
| <<<SMP>>>  | Symmetric Multi-Processing, класс вычислительных систем с общей памятью                     |
| <<<АКФ>>>  | автоковариационная функция                                                                  |
| <<<БПФ>>>  | быстрое преобразование Фурье                                                                |
| <<<ГПСЧ>>> | генератор псевдослучайных чисел                                                             |
| <<<ГУ>>>   | граничное условие                                                                           |
| <<<ДУЧП>>> | дифференциальное уравнение в частных производных                                            |
| <<<НБП>>>  | нелинейное безынерционное преобразование                                                    |
| <<<АР>>>   | процесс авторегрессии                                                                       |
| <<<АРСС>>> | процесс авторегрессии скользящего среднего                                                  |
| <<<СС>>>   | процесс скользящего среднего                                                                |
| <<<ЛХ>>>   | модель Лонге---Хиггинса                                                                     |
| <<<LAMP>>> | Large Amplitude Motion Programme, программа для моделирования качки судна на морских волнах |
| <<<ЦПТ>>>  | центральная предельная теорема                                                              |
| <<<ПМ>>>   | аппроксимация Пирсона---Московица для спектра морского волнения                             |
| <<<ЮУ>>>   | система уравнений Юла---Уокера                                                              |
| <<<МНК>>>  | метод наименьших квадратов                                                                  |
| <<<ФПР>>>  | функция плотности распределения                                                             |
| <<<ФР>>>   | функция распределения                                                                       |


#+begin_export latex
\input{postamble}
#+end_export

bibliographystyle:ugost2008
bibliography:bib/refs.bib

* Приложение
** TODO Вывод формулы модели Лонге---Хиггинса
