#+TITLE: Высокопроизводительная модель морского волнения для программ динамики морских объектов
#+AUTHOR: Иван Ганкевич
#+DATE: Санкт-Петербург, 2016
#+LANGUAGE: ru
#+LATEX_CLASS: gost
#+LATEX_CLASS_OPTIONS: [hidelinks,fontsize=14pt,paper=a4,pagesize,DIV=calc]
#+LATEX_HEADER: \IfFileExists{./preamble.tex}{\input{preamble}
#+LATEX_HEADER: \organization{Санкт-Петербургский государственный университет}
#+LATEX_HEADER: \manuscript{на правах рукописи}
#+LATEX_HEADER: \degree{Диссертация на соискание ученой степени\\кандидата физико-математических наук}
#+LATEX_HEADER: \speciality{Специальность 05.13.18\\Математическое моделирование, численные методы и комплексы программ}
#+LATEX_HEADER: \supervisor{Научный руководитель\\д.т.н Дегтярев Александр Борисович}
#+LATEX_HEADER: \newcites{published}{Список опубликованных по теме диссертации работ}
#+LATEX_HEADER: }{}
#+OPTIONS: todo:nil title:nil H:5

#+begin_latex
\clearpage
#+end_latex

# default export options
#+begin_src emacs-lisp :exports none
;; For the full list of options see
;; http://orgmode.org/manual/Publishing-options.html
;; move table/figure captions to the bottom
(setq org-latex-caption-above nil)
;; preserve original image width
(setq org-latex-image-default-width nil)
#+end_src

#+RESULTS:

* Введение
**** Актуальность темы.
Программы, моделирующие воздействие морских волн на судно, плавучую платформу
или какой-либо другой морской объект, широко используются для расчета качки
судна, определения воздействия внешних сил на структуру морского объекта, а
также для моделирования затопления и других процессов, вызываемых
взаимодействием объекта с морскими волнами; однако, большинство из них
используют линейную теорию для моделирования морского волнения
cite:shin2003nonlinear,van2007forensic,kat2001prediction,van2002development, что
не позволяет моделировать некоторые особенности ветроволнового климата. Среди
них можно выделить переход от нормальных погодных условий к шторму и волнение,
вызванное наложением множества систем ветровых волн и волн зыби,
распространяющихся в разных направлениях. Другой особенностью этих программ
является использование теории волн малой амплитуды, т.е. волн, амплитуда которых
много меньше, чем их длина. Это делает расчеты грубыми, и не позволяет
моделировать качку судна в условиях нерегулярного волнения, когда такое
предположение несправедливо. Ввиду описанных сложностей разработка более
совершенных моделей и методов, используемых при расчете динамики судна, является
актуальной задачей на сегодняшний день.
**** Степень разработанности.
Особенностью комплексов расчета динамики судов является использование линейных
моделей ветрового волнения, и, хотя эти модели хорошо исследованы, их
вычислительная эффективность не всегда достаточна для проведения длительных
численных экспериментов. Например, в случае модели Лонге---Хиггинса для
увеличения временной протяженности реализации морского волнения может
понадобится увеличить количество частот спектра на входе для исключения
периодичности, что приводит к нелинейному увеличению времени генерации с ростом
длины реализации. В случае альтернативных моделей ветрового
волнения для расчета давлений используются методы вычислительной гидродинамики,
обладающие меньшей эффективностью, чем аналитические методы, разработанные для
для линейной модели. Таким образом, степень разработанности используемых на
практике моделей ветрового волнения и методов расчета давлений не позволяет
эффективно проводить длительные численные эксперименты, а уход от линейной
модели приведет к качественному улучшению результатов экспериментов и будет
способствовать проведению исследований возникающих редко экстремальных ситуаций,
связанных с потерей остойчивости (например, опрокидывание и брочинг).
**** Цели и задачи.
Основной целью работы является разработка математического и численного аппарата
имитационного моделирования морских волн для проведения длительных численных
экспериментов и определения величины создаваемого морскими волнами воздействия
на морские объекты. Основные задачи, решаемые в рамках работы:
- разработка модели ветрового волнения, способной генерировать реализации
  взволнованной морской поверхности, имеющие сверхбольшой период и состоящие из
  волн произвольной амплитуды;
- разработка метода расчета давлений, работающего с этой моделью и не
  использующего теорию волн малой амплитуды;
- разработка комплекса программ, реализующего созданную модель и метод расчета
  давлений и позволяющего проводить расчеты как на многопроцессорной машине с
  общей памятью, так и на компьютерном кластере.
**** Научная новизна.
Авторегрессионная модель в отличие от других моделей ветрового волнения не
основана на теории волн малой амплитуды, что позволяет учесть такие аспекты
океанских волн, как асимметричность распределения волновых аппликат. В то же
время математический аппарат этой модели хорошо разработан в других научных
областях, что позволяет обобщить модель для моделирования развития морского
волнения в условиях шторма с учетом климатических спектров и данных ассимиляции
определенных районов мирового океана.
**** Теоретическая и практическая значимость работы.
Применение альтернативной модели морского волнения и метода расчета давлений, не
использующего предположения о малости амплитуд волн и линейной теории волн,
позволит качественно повысить работу комплексов программ для расчета воздействия
океанских волн на морские объекты.
**** Методология и методы исследования.
Программная реализация авторегрессионной модели и методы вычислений давлений
была создана поэтапно: сначала был создан прототип на инженерном языке
высокого уровня (Mathematica, Octave), который затем был преобразован в
программу на языке более низкого уровня (C++). Для вывода аналитической формулы
расчета давлений использовался математический аппарат, проверка полученных
выражений осуществлялась с помощью системы компьютерной алгебры Mathematica.
**** Положения, выносимые на защиту.
- Модель ветрового волнения, способная генерировать реализации взволнованной
  морской поверхности, имеющие сверхбольшой период и состоящие из волн
  произвольной амплитуды;
- Метод расчета давлений, работающий с этой моделью и не использующий теорию
  волн малой амплитуды;
- Комплекс программ, реализующий созданную модель и метод расчета давлений и
  позволяющий проводить расчеты как на многопроцессорной машине с общей памятью,
  так и на компьютерном кластере.
**** Степень достоверности и апробация результатов.
Достоверность полученных результатов как по авторегрессионной модели так и по методу
вычислений давлений подтверждается многочисленными и всесторонними численными
экспериментами, целью которых было сравнение полученных результатов с поведением
реальных морских волн на основе имеющихся натурных данных. Апробация
производилась на системе Large Amplitude Motion Program (LAMP), в которой модель
авторегрессии и метод вычислений давлений были реализованы и сопоставлены с
используемыми ранее методами, основанными на теории волн малой амплитуды. Эти
проверки показали целесообразность применения и более высокую эффективность
альтернативной модели и метода расчета давлений ввиду их гидродинамической
адекватности и более высокой производительности.
* Постановка задачи
Задача состоит в применении авторегрессионной модели ветрового волнения для
генерации морских волн произвольной амплитуды и в определении поля давлений под
взволнованной морской поверхностью, сгенерированной этой моделью. Поле давлений
для случая идеальной несжимаемой жидкости определяется уравнением Лапласа со
смешанным граничным условием. Для случая волн малых амплитуд полученный решение
должно быть сопоставимо с известными формулами линейной теории волн; для
остальных случаев решение не должно расходиться. Результатом работы должна стать
программная реализация авторегрессионной модели и метода вычисления давлений,
эффективно работающая в распределенной вычислительной среде и на
многопроцессорной системе с общей памятью.
* Обзор литературы
** Анализ моделей ветрового волнения
*** Модель Лонге---Хиггинса
Вычисление давлений возможно только при условии знания формы взволнованной
поверхности, которая задается либо дискретно в каждой точке пространственной
сетки, либо непрерывно с помощью аналитической формулы, используемой для
генерации поверхности. Как будет показано в разделе [[#linear-boundary]], знание
такой формулы может упростить вычисление давлений, фактически сведя задачу к
генерации поля давлений, а не самой взволнованной поверхности.

Наиболее изученной и широко распространенной моделью ветрового волнения
является модель Лонге---Хиггинса cite:longuet1957statistical. Подробный
сравнительный анализ этой модели и модели авторегрессии проведен в работах
cite:degtyarev2011modelling,boukhanovsky1997thesis.

Модель Лонге---Хиггинса представляет взволнованную морскую поверхность в виде
суперпозиции элементарных гармонических волн случайных амплитуд $c_n$ и фаз
$\epsilon_n$, непрерывно распределенных на интервале $[0,2\pi]$, определяемую
формулой
\begin{equation}
    \label{eq:longuet-higgins}
    \zeta(x,y,t) = \sum\limits_n c_n \cos(u_n x + v_n y - \omega_n t + \epsilon_n)
\end{equation}
Волновые числа $(u_n,v_n)$ непрерывно распределены на плоскости $(u,v)$, т.е.
площадка $du \times dv$ содержит бесконечно большое количество волновых чисел.
Частота связана с волновыми числами дисперсионным соотношением
$\omega_n=\omega(u_n,v_n)$. Функция $\zeta(x,y,t)$ является трехмерным
эргодическим стационарным однородным гауссовым процессом, определяемым
соотношением
\begin{equation*}
    2E_\zeta(u,v)\, du\,  dv = \sum\limits_n c_n^2
\end{equation*}
где $E_\zeta(u,v)$ --- двумерная спектральная плотность энергии волн.
Коэффициенты $c_n$ определяются из энергетического спектра волнения $S(\omega)$
по формуле
\begin{equation*}
    c_n = \sqrt{ \textstyle\int\limits_{\omega_n}^{\omega_{n+1}} S(\omega) d\omega}.
\end{equation*}

*** Основные недостатки модели
Модель Лонге---Хиггинса отличается простотой численного алгоритма и
наглядностью, моделируя физически адекватную морскую поверхность. Однако, на
практике она обладает рядом недостатков cite:degtyarev2011modelling.

Модель рассчитана на представление стационарного гауссова поля и не подходит для
решения более общих задач: сумма большого числа гармоник со случайной амплитудой
и фазой будет иметь нормальное распределение в независимости от исходного
распределения фаз и амплитуд, что является следствием центральной предельной
теоремы. Исследования показывают (XXX), что особенностью океанских волн и волн
на поверхности жидкости ограниченной глубины является асимметричное
распределение волновых аппликат, которое не воспроизводится моделью.

С вычислительной точки зрения, недостатком модели является нелинейный рост
времени генерации поверхности с ростом временной протяженности реализации. При
увеличении временной протяженности необходимо увеличивается количество гармоник,
которые требуется просуммировать для исключения периодичности. Другими словами,
для исключения периодичности модель требует высокой степени дискретизации
частотно‑направленного спектра волн, а значит и большого количества частот. Это
приводит к нелинейному росту времени генерации поверхности, что делает модель
неэффективной для проведения длительных численных экспериментов.

Наконец, с инженерной точки зрения, модель обладает рядом особенностей, которые
не позволяют использовать ее в качестве фундамента для построения более
совершенных моделей.
- В численных экспериментах скорость сходимости
  выражения eqref:eq:longuet-higgins низка и имеет вероятностный характер,
  т.к. не обеспечена сходимость по фазам $\epsilon_n$.
- Обобщение модели для негауссовых и нелинейных процессов сопряжено с большой
  трудоемкостью вычислений cite:рожков1990вероятностные.
 
Таким образом, модель Лонге---Хиггинса применима для решения задачи генерации
взволнованной морской поверхности только в линейной постановке (в рамках теории
волн малой амплитуды), неэффективна для длительных экспериментов и имеет ряд
недостатков, не позволяющих использовать ее в качестве основы для построения
более совершенных моделей.

** Известные методы определения поля давлений
*** Общая постановка задачи
Задача определения поля давлений под взволнованной морской поверхностью
представляет собой обратную задачу гидродинамики для несжимаемой невязкой
жидкости. Система уравнений для нее в общем виде записывается как
cite:kochin1966theoretical
\begin{align}
    & \nabla^2\phi = 0,\nonumber\\
    & \phi_t+\frac{1}{2} |\vec{\upsilon}|^2 + g\zeta=-\frac{p}{\rho}, & \text{на }z=\zeta(x,y,t),\label{eq:problem}\\
    & D\zeta = \nabla \phi \cdot \vec{n}, & \text{на }z=\zeta(x,y,t),\nonumber
\end{align}
где $\phi$ --- потенциал скорости, $\zeta$ --- подъем (аппликата) взволнованной
поверхности, $p$ --- давление жидкости, $\rho$ --- плотность жидкости,
$\vec{\upsilon} = (\phi_x, \phi_y, \phi_z)$ --- вектор скорости, $g$ ---
ускорение свободного падения и $D$ --- субстанциональная производная (производная
Лагранжа). Первое уравнение является уравнением неразрывности (уравнение
Лапласа), второе --- законом сохранения импульса, которое иногда называют
динамическим граничным условием; третье уравнение --- кинематическое граничное
условие, которое сводится к равенству нормальной составляющей скорости жидкости
($\nabla \phi \cdot \vec{n}$) в каждой точке взволнованной поверхности
$\zeta(x,y,t)$ скорости перемещения этой поверхности ($D\zeta$).

Обратная задача гидродинамики заключается в решении этой системы уравнений
относительно $\phi$. В такой постановке уравнение Лапласа и кинематическое ГУ
используются для нахождения потенциала скорости, а динамическое ГУ --- для
вычисления давлений по известным производным потенциала. Таким образом, с
математической точки зрения обратная задача гидродинамики сводится к решению
уравнения Лапласа со смешанным ГУ --- задаче Робена для уравнения Лапласа.

*** Теория волн малых амплитуд
В cite:stab2012 дается решение обратной задачи гидродинамики для случая
идеальной несжимаемой жидкости в рамках теории волн малых амплитуд (в
предположении, что длина волны много больше ее высоты: $\lambda \gg h$). В этом
случае обратная задача линейна и сводится к уравнению Лапласа со смешанным
граничным условием, а уравнение движения используется только для нахождения
давлений по известным значениям производных потенциала скорости. Предположение о
малости амплитуд волн означает слабое изменение локального волнового числа во
времени и пространстве по сравнению с подъемом (аппликатой) взволнованной
поверхности. Это позволяет определить специальную формулу производной
$\zeta_z=k\zeta$, где $k$ --- волновое число. Формула является основой
предлагаемого решения. В двухмерном случае решение записывается явной формулой
\begin{align}
    \left.\frac{\partial\phi}{\partial x}\right|_{x,t}= &
        -\frac{1}{\sqrt{1+\alpha^{2}}}e^{-I(x)}
            \int\limits_{0}^x\frac{\partial\dot{\zeta}/\partial      
                z+\alpha\dot{\alpha}}{\sqrt{1+\alpha^{2}}}e^{I(x)}dx,\label{eq:old-sol-2d}\\
    I(x)= & \int\limits_{0}^x\frac{\partial\alpha/\partial z}{1+\alpha^{2}}dx,\nonumber
\end{align}
где $\alpha$ --- уклоны волн. В трехмерном случае решение записывается в виде
эллиптического дифференциального уравнения в частных производных
\begin{align*}
    & \frac{\partial^2 \phi}{\partial x^2} \left( 1 + \alpha_x^2 \right) +
    \frac{\partial^2 \phi}{\partial y^2} \left( 1 + \alpha_y^2 \right) +
    2\alpha_x\alpha_y \frac{\partial^2 \phi}{\partial x \partial y} + \\
    & \left(
        \frac{\partial \alpha_x}{\partial z} +
        \alpha_x \frac{\partial \alpha_x}{\partial x} +
        \alpha_y \frac{\partial \alpha_x}{\partial y}
    \right) \frac{\partial \phi}{\partial x} + \\
    & \left(
        \frac{\partial \alpha_y}{\partial z} +
        \alpha_x \frac{\partial \alpha_y}{\partial x} +
        \alpha_y \frac{\partial \alpha_y}{\partial y}
    \right) \frac{\partial \phi}{\partial y} + \\
    & \frac{\partial \dot{\zeta}}{\partial z} + 
    \alpha_x \dot{\alpha_x} + \alpha_y \dot{\alpha_y} = 0.
\end{align*}
Уравнение предполагается решать численно путем сведения к разностному.

Как будет показано в [[#sec:compare-formulae]] формула eqref:eq:old-sol-2d
расходится при попытке вычислить поле скоростей для волн больших амплитуд, а
значит не может быть использована вместе с моделью ветрового волнения,
генерирующей волны произвольных амплитуд.

*** Линеаризация граничного условия
:PROPERTIES:
:CUSTOM_ID: linear-boundary
:END:
Модель Лонге---Хиггинса позволяет вывести явную формулу для поля
скоростей путем линеаризации кинематического граничного условия. Формула для
потенциала скорости запишется как
\begin{equation*}
\phi(x,y,z,t) = \sum_n \frac{c_n g}{\omega_n} 
     e^{\sqrt{u_n^2+v_n^2} z}
     \sin(u_n x + v_n y - \omega_n t + \epsilon_n).
\end{equation*}
Формула дифференцируется для получения производных потенциала, а полученные
значения подставляются в динамическое граничное условие для вычисления давлений.

* Модель АРСС в задаче имитационного моделирования морского волнения
** Предпосылки к поиску новой модели ветрового волнения
** Основные формулы трехмерного процесса AРСС
*** Три возможных процесса
**** Процесс авторегрессии (АР).
**** Процесс скользящего среднего (СС).
**** Смешанный процесс авторегрессии скользящего среднего (АРСС).
*** Критерии выбора процесса для моделирования разных профилей волн
** Моделирование нелинейности морских волн
Модель АРСС позволяет учесть асимметричность распределения волновых аппликат,
т.е. сгенерировать морские волны, закон распределения аппликат которых имеет
ненулевой экцесс и асимметрию. Такой закон распределения характерен для реальных
морских волн.

Асимметричность включается в модель нелинейным безынерционным преобразованием
случайного процесса. Однако, любое нелинейное преобразование случайного процесса
приводит к преобразованию его автоковариационной функции. Самый простой способ
подавить этот эффект состоит в предварительной трансформации автоковариационной
функции процесса. Подробный метод преобразования изложен в работе
cite:boukhanovsky1997thesis.

Формула $z=f(y)$ преобразования взволнованной поверхности к необходимому
одномерному закону распределения $F(z)$ получается путем решения нелинейного
трансцендентного уравнения $F(z) = \Phi(y)$, где $\Phi(y)$ --- функция
одномерного нормального закона распределения. Поскольку функция распределения
аппликат морских волн часто задается некоторой аппроксимацией, основанной на
натурных данных, то это уравнение целесообразно решать численно в каждой точке
$y_k|_{k=0}^N$ сетки сгенерированной поверхности относительно $z_k$, тогда оно
запишется в виде
\begin{equation}
    \label{eq:distribution-transformation}
    F(z_k)
    =
    \frac{1}{\sqrt{2\pi}}
    \int\limits_0^{y_k} \exp\left[ -\frac{t^2}{2} \right] dt
    ,
\end{equation}
а для его решения этого можно использовать простейший численный метод
половинного деления (метод бисекции).

Для предварительного преобразования автоковариационной функции $K_z$ процесса ее
необходимо разложить в ряд по полиномам Эрмита (ряд Грама---Шарлье)
\begin{equation*}
    K_z \left( \vec u \right)
    =
    \sum\limits_{m=0}^{\infty}
    C_m^2 \frac{K_y^m \left( \vec u \right)}{m!},
\end{equation*}
где
\begin{equation*}
    C_m = \frac{1}{\sqrt{2\pi}}
  \int\limits_{0}^\infty
    f(y) H_m(y) \exp\left[ -\frac{y^2}{2} \right],
\end{equation*}
$H_m$ --- полином Эрмита, а $f(y)$ --- решение
уравнения eqref:eq:distribution-transformation. Воспользовавшись
полиномиальной аппроксимацией $f(y) \approx \sum\limits_i d_i y^i$ и
аналитическими выражениями для полнимов Эрмита, формулу определения
коэффициентов можно упростить, используя следующее равенство:
\begin{equation*}
    \frac{1}{\sqrt{2\pi}}
    \int\limits_\infty^\infty
    y^k \exp\left[ -\frac{y^2}{2} \right]
    =
    \begin{cases}
        (k-1)!! & \text{для четных }k,\\
        0       & \text{для нечетных }k.
    \end{cases}
\end{equation*}
Вычисление коэффициентов $C_m$ ведется последовательно и критерий прекращения
счета определяется совпадением дисперсий обоих полей с требуемой точностью
$\epsilon$:
\begin{equation*}
    \left| \Var{z} - \sum\limits_{k=0}^m
    \frac{C_k^2}{k!} \right| \leq \epsilon.
\end{equation*}

В cite:boukhanovsky1997thesis автор предлагает использовать полиномиальную
аппроксимацию для $f(y)$ также для преобразования поверхности, однако на
практике в реализации взволнованной поверхности всегда находятся точки,
выпадающие за промежуток на котором построена аппроксимация, что приводит к
резкому уменьшению точности аппроксимации. В этих точках
уравнение eqref:eq:distribution-transformation эффективнее решать методом
бисекции. Использование полиномиальной аппроксимацией в формулах для
коэффициентов ряда Грама---Шарлье не приводит к аналогичным ошибкам.

** Определение поля давлений под дискретно заданной взволнованной поверхностью
Поиск аналитических решений граничных задач для классических уравнений часто
связан с исследованием различных свойств решения, и для таких исследований
запись формулы общего решения неудобна ввиду своей сложности и наличия
интегралов от неизвестных функций. Одним из методов нахождения аналитических
решений ДУЧП является метод Фурье. Основой метода служит преобразование Фурье,
применение которого к любому ДУЧП позволяет свести его к алгебраическому, а его
решение записывается как обратное преобразование Фурье от некоторой функции
(которая часто содержит преобразования Фурье от других функций). Поскольку
преобразования не всегда можно записать аналитически, то вместо этого ищутся
частные решения задачи и анализируется их поведение в различных областях. В то
же время, вычисление дискретных преобразований Фурье на компьютере не
представляет сложности ввиду наличия многочисленного семейства алгоритмов БПФ.
Эти алгоритмы используют симметрию для понижения асимптотической сложности с
квадратичной $\mathcal{O}(n^2)$ до $\mathcal{O}(n \log_2 n)$. Таким образом,
метод Фурье подходит для поиска аналитических частных решений ДУЧП, а общее
решение, полученное этим методом, может стать основой для построения
высокопроизводительных \emph{гибридных} методов решения ДУЧП, в которых
преобразования Фурье от неизвестных функций производятся численно.

Альтернативным подходом, который повсеместно применяется в решении ДУЧП,
является сведение их к разностным уравнениям, решаемым с помощью построения
различных численных схем. При этом решение получается приближенным, а сложность
алгоритмов сопоставима со сложностью алгоритма БПФ. Например, стационарное
эллиптическое уравнение в частных производных преобразуется в неявную разностную
схему, решаемую итерационным методом, на каждом шаге которого ищется решение
трехдиагональной или пятидиагональной СЛАУ методом прогонки (алгоритм Томаса).
Асимптотическая сложность алгоритма составляет $\mathcal{O}(n m)$, где $n$ ---
количество точек на сетке взволнованной поверхности, $m$ --- число итераций.

С вычислительной точки зрения наличие большого количества преобразований Фурье в
решении является преимуществом. Решения полученные с помощью метода Фурье явные,
а значит хорошо масштабируются на большое количество параллельно работающих
вычислительных ядер с использованием простейших приемов параллельного
программирования. Эти преимущества обусловили выбор метода Фурье в качестве
рабочего для получения явного аналитического решения задачи определения давлений
под взволнованной морской поверхностью.

*** Двухмерное поле скоростей
:PROPERTIES:
:CUSTOM_ID: sec:pressure-2d
:END:
**** Формула для жидкости бесконечной глубины.
Задача Робена для уравнения Лапласа в двух измерениях записывается как
\begin{align}
    \label{eq:problem-2d}
    & \phi_{xx}+\phi_{zz}=0,\\
    & \zeta_t + \zeta_x\phi_x = \frac{\zeta_x}{\sqrt{1 + \zeta_x^2}} \phi_x - \phi_z, & \text{на }z=\zeta(x,t).\nonumber
\end{align}
Для ее решения воспользуемся методом Фурье. Возьмем преобразование Фурье от
обоих частей уравнений Лапласа и получим
\begin{equation*}
    -4 \pi^2 \left( u^2 + v^2 \right)
    \Fourier{\phi(x,z)}(u,v) = 0,
\end{equation*}
откуда имеем $v = \pm i u$. Здесь и далее будет использоваться следующая
симметричная форма преобразования Фурье:
\begin{equation*}
    \Fourier{f(x,y)}(u,v) =
    \iint\limits_{-\infty}^{\phantom{--}\infty}
    f(x,y)
    e^{-2\pi i (x u + y v)}
    dx dy
\end{equation*}
Решение уравнения будем искать в виде обратного преобразования Фурье
$\phi(x,z) = \InverseFourier{E(u,v)}(x,z)$. Применяя полученное равенство со знаком
"+"\footnote{Выражение $v = - i u$ не подходит в данной задаче, поскольку
потенциал скорости должен стремиться к нулю с увеличением глубины (с уменьшением
$z$).}, решение можно переписать как
\begin{equation}
    \label{eq:guessed-sol-2d}
    \phi(x,z) = \InverseFourier{e^{2\pi u z}E(u)}(x).
\end{equation}
Для того чтобы подстановка $z=\zeta(x,t)$ не помешала использованию
преобразований Фурье в решении, перепишем eqref:eq:guessed-sol-2d в виде
свертки:
\begin{equation*}
    \phi(x,z)
    =
    \Fun{z}
    \ast
    \InverseFourier{E(u)}(x),
\end{equation*}
где $\Fun{z}$ --- некоторая функция, вид которой будет определен в
[[#sec:compute-delta]] и для которой выполняется соотношение
$\Fourier{\Fun{z}}(u) = e^{2\pi u z}$. Подставляя выражение для
$\phi$ в граничное условие, получим
\begin{equation*}
    \zeta_t
    =
    \left( i f(x) - 1 \right)
    \left[
        \Fun{z}
        \ast
        \InverseFourier{2\pi u E(u)}(x)
    \right],
\end{equation*}
где $f(x) = {\zeta_x}/{\sqrt{1 + \zeta_x^2}} - \zeta_x$. Применяя преобразование
Фурье к обеим частям, получаем выражение для коэффициентов $E$:
\begin{equation*}
    E(u) =
    \frac{1}{2\pi u}
    \frac{
    \Fourier{\zeta_t / \left(i f(x) - 1\right)}(u)
    }{
    \Fourier{\Fun{z}}(u)
    }
\end{equation*}
Выполняя подстановку $z=\zeta(x,t)$ и подставляя полученное выражение в
eqref:eq:guessed-sol-2d, получаем окончательное выражение для $\phi(x,z)$:
\begin{equation}
    \label{eq:solution-2d}
    \boxed{
        \phi(x,z)
        =
        \InverseFourier{
            \frac{e^{2\pi u z}}{2\pi u}
            \frac{
            \Fourier{ \zeta_t / \left(i f(x) - 1\right) }(u)
            }{
            \Fourier{ \Fun{\zeta(x,t)} }(u)
            }
        }(x).
    }
\end{equation}

Множитель $e^{2\pi u z}/(2\pi u)$ делает график функции от которой берется
обратное преобразования Фурье несимметричным относительно оси OY. Это затрудняет
применение БПФ, поскольку оно требует периодичную функцию, которая на концах
промежутка принимает нулевое значение. Реализация же этого обратного
преобразования с помощью численного интегрирования не позволит получить
преимущество над решением всей системы уравнений с помощью разностных схем.
Решением проблемы является использование формулы eqref:eq:solution-2d-full для
жидкости конечной глубины с заведомо большим значением глубины водоема $h$.

**** Формула для жидкости конечной глубины.
На дне водоема вертикальная составляющая скорости перемещения жидкости должна
равняться нулю, т.е. $\phi_z=0$ на $z=-h$, где $h$ --- глубина водоема. В этом
случае пренебречь равенством $v = -i u$, полученным из уравнения Лапласа,
нельзя, и решение ищется в виде
\begin{equation}
    \phi(x,z)
    =
    \InverseFourier{
        \left( C_1 e^{2\pi u z} + C_2 e^{-2\pi u z} \right)
        E(u)
    }(x).
    \label{eq:guessed-sol-2d-full}
\end{equation}
Подставляя $\phi$ в условие на дне водоема, получим
\begin{equation*}
    C_1 e^{-2\pi u h} - C_2 e^{2\pi u h} = 0,
\end{equation*}
откуда имеем $C_1=\frac{1}{2} C e^{2\pi u h}$ и $C_2=-\frac{1}{2}C e^{-2\pi u
h}$. Константа $C$ здесь произвольна, поскольку при подстановке станет частью
неизвестных коэффициентов $E(u)$. Подставляя полученные выражения для $C_1$ и
$C_2$ в eqref:eq:guessed-sol-2d-full, получаем выражение
\begin{equation*}
    \phi(x,z) = \InverseFourier{ \Sinh{2\pi u (z+h)} E(u) }(x).
\end{equation*}
Выполняя аналогичные предыдущему разделу операции, получаем окончательное
выражение для $\phi(x,z)$:
\begin{equation}
\boxed{
    \phi(x,z,t)
    =
  \InverseFourier{
        \frac{\Sinh{2\pi u (z+h)}}{2\pi u}
        \frac{
            \Fourier{ \zeta_t / \left(i f(x) - 1\right) }(u)
        }{
            \Fourier{ \FunSecond{\zeta(x,t)} }(u)
        }
    }(x),
}
    \label{eq:solution-2d-full}
\end{equation}
где $\FunSecond{z}$ --- некоторая функция, вид которой будет определен в
[[#sec:compute-delta]] и для которой выполняется соотношение
$\Fourier{\FunSecond{z}}(u) = \Sinh{2\pi u z}$.

**** Сведение к формулам линейной теории волн.
Справедливость полученных формул проверим, подставив в качестве $\zeta(x,t)$
известные аналитические выражения для плоских волн. Для вычисления
преобразований Фурье символьно воспользуемся пакетом Mathematica
cite:mathematica10. В линейной теории широко используется предположение о
малости амплитуд волн, что позволяет упростить исходную систему уравнений
eqref:eq:problem-2d до
\begin{align*}
    & \phi_{xx}+\phi_{zz}=0,\\
    & \zeta_t = -\phi_z & \text{на }z=\zeta(x,t),
\end{align*}
решение которой запишется как
\begin{equation*}
    \phi(x,z,t)
    =
    -\InverseFourier{
        \frac{e^{2\pi u z}}{2\pi u}
        \Fourier{\zeta_t}(u)
    }(x)
    .
\end{equation*}
# Таким образом, в линейном случае потенциал скорости волн малых амплитуд равен
# свертке производной по времени от функции, описывающей взволнованную
# поверхность, с ... (TODO).

\noindent Профиль прогрессивной волны описывается формулой
$\zeta(x,t)=A\cos(2\pi (k x - t))$. Подстановка этого выражения в формулу для
бесконечной глубины дает равенство $\phi(x,z,t)=-\frac{A}{k} \sin (2 \pi (k x -
t)) \Sinh{2 \pi k z}$. Чтобы свести его к формуле линейной теории волн,
необходимо представить гиперболический синус в экспоненциальной форме и
отбросить член, содержащий $e^{-2\pi k z}$, как противоречащий условию
$\phi\underset{z\rightarrow-\infty}{\longrightarrow}0$. После взятия
действительной части выражения получится формула линейной теории $\phi(x,z,t) =
\frac{A}{k} e^{2 \pi k z} \sin(2 \pi (k x - t))$. Аналогично, предположение о
малости амплитуд волн позволяет упростить формулу eqref:eq:solution-2d-full до
\begin{equation*}
    \phi(x,z,t)
    =
    -\InverseFourier{
        \frac{\Sinh{2\pi u (z+h)}}{2\pi u \Sinh{2\pi u h}}
        \Fourier{\zeta_t}(u)
    }(x).
\end{equation*}
Подстановка формулы для прогрессивной плоской волны в это выражение дает
равенство
\begin{equation}
\label{eq:solution-2d-linear}
\phi(x,z,t)=\frac{A}{k} \frac{\Sinh{2 \pi k (z+h)}}{ \Sinh{2 \pi k h} } \sin (2 \pi (k x-t)),
\end{equation}
что соответствует формуле линейной теории для конечной глубины.

Различная запись решения уравнения Лапласа, в котором затухающая экспонента
может встречаться как со знаком "+", так и со знаком "-", может стать
причиной разницы в формуле, где вместо $\cosh$ будет использоваться $\sinh$.
Выражение $\frac{\Sinh{2 \pi k (z+h)}}{ \Sinh{2 \pi k h} } \approx \frac{\cosh
(2 \pi k (z+h))}{ \cosh (2 \pi k h) }$ превращается в строгое равенство на
поверхности, и разница между правой левой частью увеличивается при приближении к
дну водоема (для достаточно большой глубины ошибка вблизи поверхности жидкости
незначительна), поэтому на практике для расчетов вблизи взволнованной поверности
можно использовать любую из функций.

Сведение формул eqref:eq:solution-2d и eqref:eq:solution-2d-full к формулам
линейной теории волн показало, что формула eqref:eq:solution-2d не подходит для
расчета потенциала на бесконечной глубине с использованием численных методов,
т.к. не обладает необходимой для применения быстрого преобразования Фурье
симметрией. Для такого случая можно использовать формулу для конечной глубины,
полагая $h$ равным характерному значению глубины исследуемого водоема. Для
стоячих волн сведение к формулам линейной теории происходит с аналогичными
предположениями.
*** Трехмерное поле скоростей
В трех измерениях исходная система уравнений eqref:eq:problem переписывается как
\begin{align}
    \label{eq:problem-3d}
    & \phi_xx + \phi_yy + \phi_zz = 0,\\
    & \zeta_t + \zeta_x\phi_x + \zeta_y\phi_y
    =
    \frac{\zeta_x}{\sqrt{1 + \zeta_x^2}} \phi_x
    +\frac{\zeta_y}{\sqrt{\vphantom{\zeta_x^2}\smash[b]{1 + \zeta_y^2}}} \phi_y
    - \phi_z, & \text{на }z=\zeta(x,y,t).\nonumber
\end{align}
Для ее решения воспользуемся методом Фурье. Возьмем преобразование Фурье от
обоих частей уравнений Лапласа и получим
\begin{equation*}
    -4 \pi^2 \left( u^2 + v^2 + w^2 \right)
    \Fourier{\phi(x,y,z)}(u,v,w) = 0,
\end{equation*}
откуда имеем $w = \pm i \sqrt{u^2 + v^2}$. Решение уравнения будем искать в виде
обратного преобразования Фурье $\phi(x,y,z) = \InverseFourier{E(u,v,w)}(x,y,z)$.
Применяя полученное равенство, получаем
\begin{equation*}
    \phi(x,y,z) = \InverseFourier{
        \left(
            C_1 e^{2\pi \sqrt{u^2+v^2} z}
            -C_2 e^{-2\pi \sqrt{u^2+v^2} z}
        \right)
        E(u,v)
    }(x,y).
\end{equation*}
Подставляя $\phi$ в условие на дне водоема аналогично двухмерному случаю,
получаем
\begin{equation}
    \label{eq:guessed-sol-3d}
    \phi(x,y,z) = \InverseFourier{
        \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)
    }(x,y).
\end{equation}
Подставляя выражение для $\phi$ в граничное условие, получим
\begin{equation*}
    \arraycolsep=1.4pt
    \begin{array}{rl}
        \zeta_t = & i f_1(x) \InverseFourier{2 \pi u \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}(x,y) \\
        + & i f_2(x) \InverseFourier{2 \pi v \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}(x,y) \\
        - & \InverseFourier{2 \pi \sqrt{u^2+v^2} \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}E(u,v)}(x,y)
    \end{array}
\end{equation*}
где $f_1(x,y) = {\zeta_x}/{\sqrt{1 + \zeta_x^2}} - \zeta_x$ и
$f_2(x,y) = {\zeta_y}/{\sqrt{\vphantom{\zeta_x^2}\smash[b]{1 + \zeta_y^2}}} - \zeta_y$.
Применяя преобразование Фурье к обеим частям, получаем выражение для коэффициентов $E$:
\begin{equation*}
    \arraycolsep=1.4pt
    \begin{array}{rl}
        \Fourier{\zeta_t}(u,v) = &
        \Fourier{i f_1(x) \InverseFourier{2 \pi u \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}}(x,y)}(u,v)  E(u,v)\\
        + & \Fourier{i f_2(x) \InverseFourier{2 \pi v \Sinh{2\pi \sqrt{u^2+v^2} (z+h)}}(x,y)}(u,v)  E(u,v)\\
        - & 2 \pi \sqrt{u^2+v^2} \Sinh{2\pi \sqrt{u^2+v^2} (z+h)} E(u,v)
    \end{array}
\end{equation*}
Окончательное решение получается при подстановке выражения для $E(u,v)$
в eqref:eq:guessed-sol-3d.

* Численные методы и результаты экспериментов
** Форма АКФ для разных волновых профилей
*** Два метода для определения формы АКФ
**** Аналитический метод.
**** Эмпирический метод.
*** Примеры АКФ для различных волновых профилей
**** АКФ стоячей волны.
**** АКФ прогрессивной волны.
*** Сравнение изученных методов
** Дополнительные формулы, методы и алгоритмы для модели АРСС
*** Аппроксимация распределения аппликат
Одним из входных параметров генератора взволвнованной морской поверхности служит
фнукция распределения волновых аппликат, которая может быть задана
полиномиальной аппроксимацией натурных данных или аналитически.

В cite:huang1980experimental было экспериментально показано, что распределение
аппликат взволнованной морской поверхности отличается от нормального ненулевым
экцессом и асимметрией. В cite:рожков1996теория показано, что такое
распределение можно разложить в ряд Грама---Шарлье:
\begin{align}
    \label{eq:skew-normal-1}
    F(z; \gamma_1, \gamma_2) & = \phi(z) - \gamma_1 \frac{\phi'''(z)}{3!} + \gamma_2 \frac{\phi''''(z)}{4!} \nonumber \\
    & =
    \frac{1}{2} \text{erf}\left[\frac{z}{\sqrt{2}}\right]
    -
    \frac{e^{-\frac{z^2}{2}}}{\sqrt{2\pi}}
    \left[
        \frac{1}{6} \gamma_1 \left(z^2-1\right)
        + \frac{1}{24} \gamma_2 z \left(z^2-3\right)
    \right]
    ,\nonumber \\
    f(z; \gamma_1, \gamma_2) & =
    \frac{e^{-\frac{z^2}{2}}}{\sqrt{2 \pi }}
    \left[
        \frac{1}{6} \gamma_1 z \left(z^2-3\right)
        + \frac{1}{24} \gamma_2 \left(z^4-6z^2+3\right)
        +1
    \right],
\end{align}
где $\phi(z)=\frac{1}{2}\mathrm{erf}(z/\sqrt{2})$, $\gamma_1$ --- асимметрия,
$\gamma_2$ --- эксцесс, $f$ --- плотность распределения, $F$ --- функция
распределения. Согласно cite:рожков1990вероятностные для аппликат морских волн
значение асимметрии выбирается на интервале $0.1 \leq \gamma_1 \leq 0,52]$, а
значение эксцесса на интервале $0,1 \leq \gamma_2 \leq 0,7$. Вид плотности
распределения при различных параметрах показан на [[fig:skew-normal-1]].

#+begin_src gnuplot :exports none
set loadpath GPVAL_PWD."/gnuplot"
system "mkdir -p build"
cd "build"

load 'style.gnuplot'
#load 'style-paper.gnuplot'

set terminal svg fixed enhanced size 1920/5,900/3 font 'Old Standard, 12' dashed rounded
set key top center Left reverse width -10 maxrows 2
set xlabel 'z' offset 0,0.33
set ylabel 'f(z)' offset 2,0

set xrange [-3:3]
set ytics 0,0.1
set yrange [0:0.6]

skew_normal_1(z, skewness, kurtosis) = (24 + 4*z*(-3 + z**2)* \
      skewness + (3 - 6*z**2 + z**4)* kurtosis)/(24*(exp((z**2)/2)*sqrt(2*pi)))

#print skew_normal_1(1, 0.6, 1.0)
# regular gamma γ

set output 'skew-normal-1.svg'
plot \
skew_normal_1(x, 0, 0) with lines ls 1 title '𝛾_1=0, 𝛾_2=0', \
skew_normal_1(x, 0.52, 0) with lines ls 2 title '𝛾_1=0.52, 𝛾_2=0', \
skew_normal_1(x, 0, 0.7) with lines ls 3 title '𝛾_1=0, 𝛾_2=0.7', \
skew_normal_1(x, 0.52, 0.7) with lines ls 4 title '𝛾_1=0.52, 𝛾_2=0.7'
system "inkscape --without-gui --export-eps=skew-normal-1.eps skew-normal-1.svg

skew_normal_2(z, alpha) = \
  erfc( -((z*alpha)/sqrt(2)) ) / \
  (exp((z**2)/2)*sqrt(2*pi))

skewness(alpha) = \
  (sqrt(2) * (4 - pi) * (alpha**3)) \
  / \
  (sqrt(pi + (pi-2) * (alpha**2))**3)

kurtosis(alpha) = \
  (8*(-3 + pi)*(alpha**4))/ \
  ((pi + (-2 + pi)*(alpha**2))**2)

set terminal svg fixed enhanced size 1920/4,900/3 font 'Times, 12' dashed rounded
set key top left Left reverse maxcols 1 maxrows 4
set yrange [0:0.8]
set output 'skew-normal-2.svg'
alphas="0.00 0.87 2.25 4.90"
a(i) = word(alphas, i)
plot for [i=1:words(alphas)] \
skew_normal_2(x, a(i)) with lines ls i \
title 'α='.a(i).', 𝛾_1='.sprintf('%.2f',skewness(a(i))).', 𝛾_2='.sprintf('%.2f',kurtosis(a(i)))
system "inkscape --without-gui --export-eps=skew-normal-2.eps skew-normal-2.svg

exit
#+end_src

#+RESULTS:


#+name: fig:skew-normal-1
#+caption: Вид плотности распределения eqref:eq:skew-normal-1 волновых аппликат при различных значениях асимметрии $\gamma_1$ и эксцесса $\gamma_2$.
[[file:build/skew-normal-1.eps]]

Альтернативной аппроксимацией распределения волновых аппликат служит формула
асимметричного нормального распределения:
\begin{align}
    \label{eq:skew-normal-2}
    F(z; \alpha) & = \frac{1}{2}
   \mathrm{erfc}\left[-\frac{z}{\sqrt{2}}
   \right]-2 T(z,\alpha ), \nonumber \\
    f(z; \alpha) & = \frac{e^{-\frac{z^2}{2}}}{\sqrt{2 \pi }}
   \mathrm{erfc}\left[-\frac{\alpha z}{\sqrt{2}}\right],
\end{align}
где $T$ --- функция Оуэна cite:owen1956tables. Эта формула не позволяет задать
значения аимметрии и эксцесса по отдельности --- оба значения регулируются
параметром $\alpha$. Преимущество данной формулы лишь в относительной простоте
вычисления: в некоторые программы и библиотеки математических функций встроена
либо она сама, либо функция Оуэна и функция ошибки. График функции для разных
значений $\alpha$ представлен на рис. [[fig:skew-normal-2]].

#+name: fig:skew-normal-2
#+caption: Вид плотности распределения eqref:eq:skew-normal-2 волновых аппликат при различных значениях коэффициента асимметрии $\alpha$.
[[file:build/skew-normal-2.eps]]

Решение уравнения eqref:eq:distribution-transformation с выбранной функцией
распределения можно произвести в каждой точке сгенерированной поверхности, что
даст наиболее точные результаты, но с вычислительной точки зрения эффективнее
решить это уравнение в фиксированных узлах, а затем интерполировать решение
методом наименьших квадратов (МНК). В этом случае точность будет меньше. Так для
многочлена 12-го порядка и интерполяционной сетке из 500 узлов, построенной на
промежутке $-5\sigma_z \leq z \leq 5\sigma_z$, погрешность составляет
$\approx0,43\cdot10^{-3}$. Увеличение порядка многочлена приводит либо к переполнениям
при интерполяции МНК, либо к дополнительным коэффициентам близким к нулю;
увеличение количества узлов влияет на результат незначительно. В большинстве
случаев трех коэффициентов ряда Грама---Шарлье было достаточно для
преобразования автоковариационной функции; относительная погрешность без
интерполяции составляет $10^{-5}$.

*** Алгоритм генерации белого шума
Чтобы исключить периодичность из сгенерированной моделью ветрового волнения
реализации взволнованной поверхности, нужно использовать ГПСЧ с достаточно
большим периодом. В качестве такого генератора в работе используется
параллельная реализация вихря Мерсенна cite:matsumoto1998mersenne с периодом
$2^{19937}-1$. Если предположить, что взволнованная поверхность генерируется на
сетке размера $1000\times1000$ и шаг по времени составляет 1 сек., то вихрь
Мерсенна позволяет сгенерировать неповторяющуюся последовательность
астрономической временной протяженности. Этого более чем достаточно для
практического применения генератора в задаче моделирования морского волнения.

Запуск нескольких ГПСЧ с разными начальными состояниями в параллельных
потоках не гарантирует некоррелированность генерируемых последовательностей
псевдослучайных чисел, и, чтобы избежать этого, в работе используется алгоритм
динамического создания вихрей Мерсенна cite:matsumoto1998dynamic. Суть
алгоритма заключается в поиске таких матриц начальных состояний генераторов,
которые бы дали максимально некоррелированные последовательности
псевдослучайных чисел при параллельном запуске нескольких вихрей Мерсенна с
этими начальными состоянями. Поскольку поиск начальных состояний может занимать
значительно большее время чем генерация белого шума, то вектор состояний
создается предварительно для заведомо большего количества параллельных потоков.
Вектор состояний сохраняется в файл, который впоследствиии считывается основной
программой перед началом генерации псевдослучаных чисел.

*** Алгоритм генерации взволнованной поверхности
В модели АРСС значение подъема взволнованной поверхности в каждой точке зависит
от предыдующих по пространству и времени значений, из-за чего в начале
реализации образуется \emph{интервал разгона} --- промежуток, на котором
реализация не соответствуют заданной АКФ. Способ решения этой проблемы зависит
от контекста, в котором используется реализация.
- Если реализация используется в контексте расчета остойчивости судна без учета
  маневрирования, то интервал никак не повлияет результаты эксперимента,
  поскольку находится на границе (далеко от исследуемого морского объекта).
- Если изучается остойчивость судна в условиях маневрирования, то интервал проще
  всего исключить из реализации (размер интервала примерно равен числу
  коэффициентов авторегрессии по каждому из измерений). Однако, это приводит к
  потере большого числа точек, поскольку исключение происходит по каждому из
  трех измерений.
- Альтернативным подходом является предварительная генерация
  взволнованной поверхности на интервале разгона моделью Лонге---Хиггинса
  и генерация остальной реализации с помощью авторегрессионной модели.

В алгоритме генерации взволнованной поверхности используется
параллелизм по данным: реализация делится на равные части, каждая из которых
генерируется независимо, --- однако, в начале каждой из частей также
присутствует интервал разгона. Для его исключения подходит метод
\emph{сшивания}, часто применяемый в обработке цифровых
сигналов cite:oppenheim1989discrete,svoboda2011efficient,pavel2013algorithms.
Суть метода заключается в добавлении интервала равного по размеру интервалу
разгона в конец каждой из частей. На этом интервале также генерируется
взволнованная поверхность, а после генерации интервал в конце части $N$
накладывается на интервал разгона в начале части $N+1$, и значения в
соответсвтующих точках складываются.

*** Формулы нормировки для потенциалов скоростей
:PROPERTIES:
:CUSTOM_ID: sec:compute-delta
:END:

В решениях двухмерной задачи eqref:eq:solution-2d и eqref:eq:solution-2d-full
присутствуют функции $\Fun{z}=\InverseFourier{e^{2\pi u z}}(x)$ и
$\FunSecond{z}=\InverseFourier{\Sinh{2\pi u z}}(x)$, которые могут быть
представлены аналитически различными выражениями, представляющими сложность для
вычислений на компьютере. Каждая из функций является преобразованием Фурье от
линейной комбинации экспонент, которое для таких функций определено неоднозначно
(см. [[tab:delta-functions]]). Для получения однозначного аналитического выражения
можно воспользоваться нормировкой $1/\Sinh{2 \pi u h}$, которая также включается
в выражение для коэффициентов $E(u)$. Численные эксперименты показывают, что
нормировка хоть и позволяет получить решение с адекватными величинами
потенциалов скорости, оно мало отличается от выражений из линейной теории волн,
в которых члены с $\zeta$ опускаются.

#+name: tab:delta-functions
#+caption: Формулы вычисления функций $\Fun{z}$ и $\FunSecond{z}$ из [[#sec:pressure-2d]], использующие нормировку для исключения неоднозначности определения дельта функции комплексного аргумента.
#+attr_latex: :booktabs t
| Функция         | Без нормировки                                             | С нормировкой                                                                                                                        |
|-----------------+------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------|
| $\Fun{z}$       | $\delta (x+i z)$                                           | $\frac{1}{2 h}\mathrm{sech}\left(\frac{\pi  (x-i (h+z))}{2 h}\right)$                                                                |
| $\FunSecond{z}$ | $\frac{1}{2}\left[\delta (x-i z) + \delta (x+i z) \right]$ | $\frac{1}{4 h}\left[\text{sech}\left(\frac{\pi  (x-i (h+z))}{2 h}\right)+\text{sech}\left(\frac{\pi  (x+i(h+z))}{2 h}\right)\right]$ |

** Верификация модели АРСС
*** Методика постановки численных экспериментов
*** Верификация интегральных характеристик взволнованной поверхности
*** Верификация полей потенциалов скоростей
:PROPERTIES:
:CUSTOM_ID: sec:compare-formulae
:END:
Сравнение полученных общих формул eqref:eq:solution-2d и
eqref:eq:solution-2d-full с известными формулами линейной теории волн позволяет
оценить различие между полями скоростей для волн как больших, так и малых
амплитуд. В общем случае получить аналитическое выражение даже для плоских волн
не представляется возможным, поэтому сравнение производится численно. Имея ввиду
выводы раздела [[#sec:pressure-2d]], сравниваются только формулы для случая конечной
глубины.

**** Отличие от формул линейной теории.
В ходе численного эксперимента результаты, полученные по формуле
eqref:eq:solution-2d-full для конечной глубины были сопоставлены с результатами,
полученными по соответсвующей формуле eqref:eq:solution-2d-linear линейной
теории, и проверка показала качественные различия в получившихся полях
потенциалов скоростей (см. [[fig:potential-field-nonlinear]]). Во-первых,
потенциальные линии имеют вид затухающей синусоиды, что отличается от овальной
формы, описываемой в линейой теории волн. Во-вторых, по мере приближения к дну
водоема потенциал гораздо быстрее затухает, чем описывается в линейной теории, а
область, где сконцентрирована большая часть энергии волны, еще больше приближена
к ее гребню. Аналогичный численный эксперимент, в котором из формулы
eqref:eq:solution-2d-full были исключены члены, которыми пренебрегают в рамках
линейной теории волн, показал, что полное соотвествие получившихся полей
потенциалов скоростей (насколько это позволяет сделать машинная точность).

#+name: fig:potential-field-nonlinear
#+caption: Поле потенциала скорости прогрессивной волны $\zeta(x,y,t) = \cos(2\pi x - t/2)$. Поле, полученное по формуле eqref:eq:solution-2d-full (слева) и по формуле линейной теории волн (справа).
#+begin_figure
[[file:graphics/pressure/potential-5.eps]]
[[file:graphics/pressure/potential-6.eps]]
#+end_figure

**** Отличие от формул теории волн малой амплитуды.
В ходе численного эксперимента результаты, полученные по формуле
eqref:eq:solution-2d-full были сопоставлены с результатами, полученными по
формуле для волн малой амплитуды eqref:eq:old-sol-2d, и проверка показала
схожесть полей скоростей, вычисленных этими методами. Для определения скоростей
использовалась реализации морской поверхности, построенные по авторегрессионной
модели и различающиеся амплитудой волн. При этом интегрирование в формуле
eqref:eq:solution-2d-full велось по соответствующему сгенерированной морской
поверхности интервал волновых чисел. Эксперименты проводились для волн разных
амплитуд, и для волн малой амплитуды оба метода показывают сопоставимые
результаты, в то время как для волн высоких амплитуд стабильное поле скоростей
дает только формула eqref:eq:solution-2d-full (см. [[fig:velocity-field-2d]]). Таким
образом, полученная формула показывает удовлетворительные результаты для
различных морских поверхностей, не вводя ограничения на величины амплитуд волн.

#+begin_src gnuplot :exports none
set loadpath GPVAL_PWD."/gnuplot" GPVAL_PWD."/data/velocity"
system "mkdir -p build"
cd "build"

set terminal svg size 320, 200 font "Open Sans Regular, 12" linewidth 1 enhanced rounded dashed

load 'linestyle.gnuplot'

unset border
set border 3
set xtics nomirror out offset 0,0.5
set ytics nomirror out offset 0.5,0

set xrange [0:90]
set yrange [-2:4]
set xtics 0,30
set ytics -2,2,4
set xlabel 'x' offset 0,1
set ylabel 'u(x)' offset 1.75,0

set output 'high-amp-nocolor.svg'
plot 'high-amp'   title 'u_1(x)' ls 1 smooth csplines, \
     'high-amp-0' title 'u_2(x)' ls 2 smooth csplines
system "inkscape --without-gui --export-eps=high-amp-nocolor.eps high-amp-nocolor.svg

set output 'low-amp-nocolor.svg'
plot 'low-amp'   title 'u_1(x)' ls 1 smooth csplines, \
     'low-amp-0' title 'u_2(x)' ls 2 smooth csplines
system "inkscape --without-gui --export-eps=low-amp-nocolor.eps low-amp-nocolor.svg

exit
#+end_src

#+RESULTS:

#+name: fig:velocity-field-2d
#+caption: Сравнение полей скоростей на поверхности моря, полученных по общей формуле ($u_1$) и формуле для волн малой амплитуды ($u_2$). Поле скоростей для поверхности волн малой амплитуды (слева) и большой амплитуды (справа).
#+begin_figure
[[file:build/low-amp-nocolor.eps]]
[[file:build/high-amp-nocolor.eps]]
#+end_figure

*** TODO Нефизическая природа модели
* Высокопроизводительный программный комплекс для моделирования морского волнения
** Модель вычислений
*** Основополагающие принципы модели
*** Отображение алгоритма генерации взволнованной поверхности на вычислительную модель
** Реализация для систем с общей памятью (SMP)
*** Алгоритм распределения нагрузки
*** Результаты тестирования
**** Производительности реализаций на MPI, OpenMP и OpenCL.
**** Производительность алгоритма распределения нагрузки.
** Реализация для систем с распределенной памятью (MPP)
*** Алгоритм обнаружения узлов кластера
*** Алгоритм восстановления после сбоев
**** Обеспечение отказоустойчивости.
**** Обеспечение высокой доступности.
* Заключение
**** Итоги исследования.
В изучении возможностей математического аппарата для имитационного моделирования
морского волнения, выходящего за рамки линейной теории волн, были достигнуты
следующие основные результаты.
- Разработана модель ветрового волнения для генерации волн произвольных
  амплитуд.
- Разработан гибридный метод расчета давлений в двухмерной постановке,
  использующий как аналитические выражения, так и численное интегрирование по
  алгоритму быстрого преобразования Фурье.
- Разработанный метод позволил упростить программную реализацию комплекса, и
  свести реализацию алгоритма к параллельному вычислению большого количества
  преобразований Фурье.
- Предварительная апробация авторегрессионной модели и метода расчета давлений
  была произведена в пакете Large Amplitude Motion Program 4.

**** Перспективы дальнейших исследований.
Хотя задача генерации взволнованной морской поверхности была решена в трехмерной
постановке, для задачи расчета гидродинамических давлений было найдено
аналитическое решение только в двухмерном случае. В трехмерной постановке
полученные формулы не были всесторонне исследованы. Таким образом, дальнейшие
исследования предполагают изучение аналитического решения для трехмерный случая,
а также создание виртуального полигона на основе модели АРСС и метода расчета
давлений по результатам апробации в пакете Large Amplitude Motion Program 4.

* Выводы
Результаты исследования позволяют сделать вывод о том, что задача вычисления
давлений под реальной морской поверхностью может быть решена аналитически в
двухмерной постановке, минуя предположения линейной теории волн и теории волн
малой амплитуды. Это аналитическое решение в паре с моделью АРСС ветрового
волнения, способной генерировать волны произвольных амплитуд, может быть
использовано для расчета влияния колебаний волн на поведение динамического
объекта в открытом море, и дает более точные результаты чем аналогичное решение
для волн малых амплитуд. Результаты проведенных экспериментов позволяют сделать
вывод о том, что как генерация взволнованной поверхности так и расчет
гидродинамических давлений могут быть реализованы эффективно с использованием
алгоритмов быстрого преобразования Фурье, а распределенная система научных
расчетов может быть использвана для длительных сессий имитационного
моделирования. Разработанный в работе математический аппарат и его программная
реализация могут стать основой виртуального полигона, предназанченного для
расчетов динамики морских объектов.

* Благодарности
* Список сокращений и условных обозначений

#+attr_latex: :booktabs t
| Аббревиатура | Значение                                                                         |
|--------------+----------------------------------------------------------------------------------|
| процесс АРСС | процесс авторегрессии скользящего среднего                                       |
| ГПСЧ         | генератор псевдослучайных чисел                                                  |
| процесс АР   | процесс авторегрессии                                                            |
| процесс СС   | процесс скользящего среднего                                                     |
| АКФ          | автоковариационная функция                                                       |
| НБП          | нелинейное безынерционное преобразование                                         |
| ГУ           | граничное условие                                                                |
| БПФ          | быстрое преобразование Фурье                                                     |
| ДУЧП         | дифференциальное уравнение в частных производных                                 |
| SMP          | Symmetric Multi-Processing, класс вычислительных систем с общей памятью          |
| MPP          | Massively Parallel Processing, класс вычислительных систем с разделенной памятью |

#+begin_latex
\input{postamble}
#+end_latex

* Приложение
** TODO Вывод формулы модели Лонге---Хиггинса
